export interface Book {
  title: string;
  author: string;
  year: number; // Year of first publication
}

export const books: Book[] = [
  { title: "The Divine Comedy", author: "Dante Alighieri", year: 1321 },
  { title: "The Canterbury Tales", author: "Geoffrey Chaucer", year: 1400 },
  { title: "The Prince", author: "Niccolò Machiavelli", year: 1532 },
  { title: "Gargantua and Pantagruel", author: "François Rabelais", year: 1532 },
  { title: "Essays", author: "Michel de Montaigne", year: 1580 },
  { title: "Romeo and Juliet", author: "William Shakespeare", year: 1597 },
  { title: "Hamlet", author: "William Shakespeare", year: 1603 },
  { title: "Don Quixote", author: "Miguel de Cervantes", year: 1605 },
  { title: "Macbeth", author: "William Shakespeare", year: 1623 },
  { title: "Paradise Lost", author: "John Milton", year: 1667 },
  { title: "The Pilgrim's Progress", author: "John Bunyan", year: 1678 },
  { title: "Robinson Crusoe", author: "Daniel Defoe", year: 1719 },
  { title: "Gulliver's Travels", author: "Jonathan Swift", year: 1726 },
  { title: "Candide", author: "Voltaire", year: 1759 },
  { title: "The Sorrows of Young Werther", author: "Johann Wolfgang von Goethe", year: 1774 },
  { title: "The Wealth of Nations", author: "Adam Smith", year: 1776 },
  { title: "Critique of Pure Reason", author: "Immanuel Kant", year: 1781 },
  { title: "Pride and Prejudice", author: "Jane Austen", year: 1813 },
  { title: "Frankenstein", author: "Mary Shelley", year: 1818 },
  { title: "Faust, Part One", author: "Johann Wolfgang von Goethe", year: 1808 },
  { title: "The Hunchback of Notre-Dame", author: "Victor Hugo", year: 1831 },
  { title: "Eugene Onegin", author: "Alexander Pushkin", year: 1833 },
  { title: "Oliver Twist", author: "Charles Dickens", year: 1838 },
  { title: "The Count of Monte Cristo", author: "Alexandre Dumas", year: 1844 },
  { title: "The Three Musketeers", author: "Alexandre Dumas", year: 1844 },
  { title: "Jane Eyre", author: "Charlotte Brontë", year: 1847 },
  { title: "Wuthering Heights", author: "Emily Brontë", year: 1847 },
  { title: "The Communist Manifesto", author: "Karl Marx and Friedrich Engels", year: 1848 },
  { title: "The Scarlet Letter", author: "Nathaniel Hawthorne", year: 1850 },
  { title: "Moby-Dick", author: "Herman Melville", year: 1851 },
  { title: "Uncle Tom's Cabin", author: "Harriet Beecher Stowe", year: 1852 },
  { title: "Walden", author: "Henry David Thoreau", year: 1854 },
  { title: "Leaves of Grass", author: "Walt Whitman", year: 1855 },
  { title: "Madame Bovary", author: "Gustave Flaubert", year: 1857 },
  { title: "On the Origin of Species", author: "Charles Darwin", year: 1859 },
  { title: "A Tale of Two Cities", author: "Charles Dickens", year: 1859 },
  { title: "Great Expectations", author: "Charles Dickens", year: 1861 },
  { title: "Les Misérables", author: "Victor Hugo", year: 1862 },
  { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", year: 1865 },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky", year: 1866 },
  { title: "War and Peace", author: "Leo Tolstoy", year: 1869 },
  { title: "Twenty Thousand Leagues Under the Seas", author: "Jules Verne", year: 1870 },
  { title: "Middlemarch", author: "George Eliot", year: 1872 },
  { title: "Around the World in Eighty Days", author: "Jules Verne", year: 1873 },
  { title: "Anna Karenina", author: "Leo Tolstoy", year: 1878 },
  { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", year: 1880 },
  { title: "Treasure Island", author: "Robert Louis Stevenson", year: 1883 },
  { title: "Adventures of Huckleberry Finn", author: "Mark Twain", year: 1884 },
  { title: "Thus Spoke Zarathustra", author: "Friedrich Nietzsche", year: 1885 },
  { title: "Strange Case of Dr Jekyll and Mr Hyde", author: "Robert Louis Stevenson", year: 1886 },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde", year: 1890 },
  { title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", year: 1892 },
  { title: "Dracula", author: "Bram Stoker", year: 1897 },
  { title: "The War of the Worlds", author: "H. G. Wells", year: 1898 },
  { title: "The Interpretation of Dreams", author: "Sigmund Freud", year: 1899 },
  { title: "Heart of Darkness", author: "Joseph Conrad", year: 1899 },
  { title: "The Call of the Wild", author: "Jack London", year: 1903 },
  { title: "In Search of Lost Time (Swann's Way)", author: "Marcel Proust", year: 1913 },
  { title: "The Metamorphosis", author: "Franz Kafka", year: 1915 },
  { title: "Ulysses", author: "James Joyce", year: 1922 },
  { title: "Siddhartha", author: "Hermann Hesse", year: 1922 },
  { title: "The Magic Mountain", author: "Thomas Mann", year: 1924 },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", year: 1925 },
  { title: "The Trial", author: "Franz Kafka", year: 1925 },
  { title: "Mrs Dalloway", author: "Virginia Woolf", year: 1925 },
  { title: "The Sun Also Rises", author: "Ernest Hemingway", year: 1926 },
  { title: "Steppenwolf", author: "Hermann Hesse", year: 1927 },
  { title: "All Quiet on the Western Front", author: "Erich Maria Remarque", year: 1929 },
  { title: "The Sound and the Fury", author: "William Faulkner", year: 1929 },
  { title: "Brave New World", author: "Aldous Huxley", year: 1932 },
  { title: "Gone with the Wind", author: "Margaret Mitchell", year: 1936 },
  { title: "The Hobbit", author: "J. R. R. Tolkien", year: 1937 },
  { title: "Of Mice and Men", author: "John Steinbeck", year: 1937 },
  { title: "The Grapes of Wrath", author: "John Steinbeck", year: 1939 },
  { title: "For Whom the Bell Tolls", author: "Ernest Hemingway", year: 1940 },
  { title: "The Stranger", author: "Albert Camus", year: 1942 },
  { title: "The Little Prince", author: "Antoine de Saint-Exupéry", year: 1943 },
  { title: "Animal Farm", author: "George Orwell", year: 1945 },
  { title: "The Diary of a Young Girl", author: "Anne Frank", year: 1947 },
  { title: "The Plague", author: "Albert Camus", year: 1947 },
  { title: "Nineteen Eighty-Four", author: "George Orwell", year: 1949 },
  { title: "The Catcher in the Rye", author: "J. D. Salinger", year: 1951 },
  { title: "The Old Man and the Sea", author: "Ernest Hemingway", year: 1952 },
  { title: "Fahrenheit 451", author: "Ray Bradbury", year: 1953 },
  { title: "The Lord of the Rings", author: "J. R. R. Tolkien", year: 1954 },
  { title: "Lolita", author: "Vladimir Nabokov", year: 1955 },
  { title: "Doctor Zhivago", author: "Boris Pasternak", year: 1957 },
  { title: "Things Fall Apart", author: "Chinua Achebe", year: 1958 },
  { title: "To Kill a Mockingbird", author: "Harper Lee", year: 1960 },
  { title: "Catch-22", author: "Joseph Heller", year: 1961 },
  { title: "One Day in the Life of Ivan Denisovich", author: "Aleksandr Solzhenitsyn", year: 1962 },
  { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez", year: 1967 },
  { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", year: 1969 },
  { title: "The Gulag Archipelago", author: "Aleksandr Solzhenitsyn", year: 1973 },
  { title: "The Name of the Rose", author: "Umberto Eco", year: 1980 },
  { title: "The House of the Spirits", author: "Isabel Allende", year: 1982 },
  { title: "Love in the Time of Cholera", author: "Gabriel García Márquez", year: 1985 },
  { title: "Beloved", author: "Toni Morrison", year: 1987 },
  { title: "Harry Potter and the Philosopher's Stone", author: "J. K. Rowling", year: 1997 },
];
