import {type Difficulty} from './difficulty.js';

export interface FamousBirth {
  name: string;
  value: number;
  id: number;
  difficulty: Difficulty;
  link: string;
}

export const famousBirths: FamousBirth[] = [
  {
    name: 'Ramses II',
    value: -1303,
    id: 4205,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Ramesses_II',
  },
  {
    name: 'Homer',
    value: -750,
    id: 4206,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Homer',
  },
  {
    name: 'Pythagoras',
    value: -570,
    id: 4207,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Pythagoras',
  },
  {
    name: 'Gautama Buddha',
    value: -563,
    id: 4000,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Gautama_Buddha',
  },
  {
    name: 'Confucius',
    value: -551,
    id: 4001,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Confucius',
  },
  {
    name: 'Sun Tzu',
    value: -544,
    id: 4208,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Sun_Tzu',
  },
  {
    name: 'Herodotus',
    value: -484,
    id: 4209,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Herodotus',
  },
  {
    name: 'Socrates',
    value: -470,
    id: 4002,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Socrates',
  },
  {
    name: 'Hippocrates',
    value: -460,
    id: 4210,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Hippocrates',
  },
  {
    name: 'Plato',
    value: -428,
    id: 4003,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Plato',
  },
  {
    name: 'Aristotle',
    value: -384,
    id: 4004,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Aristotle',
  },
  {
    name: 'Alexander the Great',
    value: -356,
    id: 4005,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Alexander_the_Great',
  },
  {
    name: 'Euclid',
    value: -325,
    id: 4211,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Euclid',
  },
  {
    name: 'Archimedes',
    value: -287,
    id: 4006,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Archimedes',
  },
  {
    name: 'Qin Shi Huang',
    value: -259,
    id: 4007,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Qin_Shi_Huang',
  },
  {
    name: 'Hannibal',
    value: -247,
    id: 4008,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Hannibal',
  },
  {
    name: 'Spartacus',
    value: -111,
    id: 4212,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Spartacus',
  },
  {
    name: 'Cicero',
    value: -106,
    id: 4009,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Cicero',
  },
  {
    name: 'Julius Caesar',
    value: -100,
    id: 4010,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Julius_Caesar',
  },
  {
    name: 'Virgil',
    value: -70,
    id: 4011,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Virgil',
  },
  {
    name: 'Cleopatra',
    value: -69,
    id: 4012,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Cleopatra',
  },
  {
    name: 'Augustus',
    value: -63,
    id: 4013,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Augustus',
  },
  {
    name: 'Jesus of Nazareth',
    value: -4,
    id: 4014,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Jesus',
  },
  {
    name: 'Saint Peter',
    value: 1,
    id: 4213,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Saint_Peter',
  },
  {
    name: 'Paul the Apostle',
    value: 5,
    id: 4214,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Paul_the_Apostle',
  },
  {
    name: 'Pliny the Elder',
    value: 23,
    id: 4215,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Pliny_the_Elder',
  },
  {
    name: 'Nero',
    value: 37,
    id: 4015,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Nero',
  },
  {
    name: 'Marcus Aurelius',
    value: 121,
    id: 4016,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Marcus_Aurelius',
  },
  {
    name: 'Constantine the Great',
    value: 272,
    id: 4017,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Constantine_the_Great',
  },
  {
    name: 'Attila the Hun',
    value: 406,
    id: 4216,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Attila',
  },
  {
    name: 'Justinian I',
    value: 482,
    id: 4217,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Justinian_I',
  },
  {
    name: 'Muhammad',
    value: 570,
    id: 4018,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Muhammad',
  },
  {
    name: 'Charlemagne',
    value: 748,
    id: 4019,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Charlemagne',
  },
  {
    name: 'Leif Erikson',
    value: 970,
    id: 4218,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Leif_Erikson',
  },
  {
    name: 'Avicenna',
    value: 980,
    id: 4219,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Avicenna',
  },
  {
    name: 'William the Conqueror',
    value: 1028,
    id: 4020,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/William_the_Conqueror',
  },
  {
    name: 'Eleanor of Aquitaine',
    value: 1122,
    id: 4220,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Eleanor_of_Aquitaine',
  },
  {
    name: 'Saladin',
    value: 1137,
    id: 4021,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Saladin',
  },
  {
    name: 'Richard the Lionheart',
    value: 1157,
    id: 4221,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Richard_I_of_England',
  },
  {
    name: 'Genghis Khan',
    value: 1162,
    id: 4022,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Genghis_Khan',
  },
  {
    name: 'Francis of Assisi',
    value: 1181,
    id: 4222,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Francis_of_Assisi',
  },
  {
    name: 'Rumi',
    value: 1207,
    id: 4223,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Rumi',
  },
  {
    name: 'Kublai Khan',
    value: 1215,
    id: 4224,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Kublai_Khan',
  },
  {
    name: 'Thomas Aquinas',
    value: 1225,
    id: 4023,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Thomas_Aquinas',
  },
  {
    name: 'Marco Polo',
    value: 1254,
    id: 4024,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Marco_Polo',
  },
  {
    name: 'Dante Alighieri',
    value: 1265,
    id: 4025,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Dante_Alighieri',
  },
  {
    name: 'Mansa Musa',
    value: 1280,
    id: 4225,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Mansa_Musa',
  },
  {
    name: 'Petrarch',
    value: 1304,
    id: 4226,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Petrarch',
  },
  {
    name: 'Ibn Battuta',
    value: 1304,
    id: 4227,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Ibn_Battuta',
  },
  {
    name: 'Timur',
    value: 1336,
    id: 4228,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Timur',
  },
  {
    name: 'Geoffrey Chaucer',
    value: 1343,
    id: 4026,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Geoffrey_Chaucer',
  },
  {
    name: 'Zheng He',
    value: 1371,
    id: 4229,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Zheng_He',
  },
  {
    name: 'Johannes Gutenberg',
    value: 1400,
    id: 4027,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Johannes_Gutenberg',
  },
  {
    name: 'Joan of Arc',
    value: 1412,
    id: 4028,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Joan_of_Arc',
  },
  {
    name: 'Sandro Botticelli',
    value: 1445,
    id: 4230,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Sandro_Botticelli',
  },
  {
    name: 'Christopher Columbus',
    value: 1451,
    id: 4029,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Christopher_Columbus',
  },
  {
    name: 'Leonardo da Vinci',
    value: 1452,
    id: 4030,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Leonardo_da_Vinci',
  },
  {
    name: 'Erasmus',
    value: 1466,
    id: 4231,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Erasmus',
  },
  {
    name: 'Niccolò Machiavelli',
    value: 1469,
    id: 4031,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Niccol%C3%B2_Machiavelli',
  },
  {
    name: 'Vasco da Gama',
    value: 1469,
    id: 4232,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Vasco_da_Gama',
  },
  {
    name: 'Albrecht Dürer',
    value: 1471,
    id: 4233,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Albrecht_D%C3%BCrer',
  },
  {
    name: 'Nicolaus Copernicus',
    value: 1473,
    id: 4032,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Nicolaus_Copernicus',
  },
  {
    name: 'Michelangelo',
    value: 1475,
    id: 4033,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Michelangelo',
  },
  {
    name: 'Francisco Pizarro',
    value: 1478,
    id: 4034,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Francisco_Pizarro',
  },
  {
    name: 'Thomas More',
    value: 1478,
    id: 4234,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Thomas_More',
  },
  {
    name: 'Ferdinand Magellan',
    value: 1480,
    id: 4035,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Ferdinand_Magellan',
  },
  {
    name: 'Martin Luther',
    value: 1483,
    id: 4037,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Martin_Luther',
  },
  {
    name: 'Raphael',
    value: 1483,
    id: 4235,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Raphael',
  },
  {
    name: 'Hernán Cortés',
    value: 1485,
    id: 4036,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Hern%C3%A1n_Cort%C3%A9s',
  },
  {
    name: 'Henry VIII',
    value: 1491,
    id: 4038,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Henry_VIII_of_England',
  },
  {
    name: 'Suleiman the Magnificent',
    value: 1494,
    id: 4039,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Suleiman_the_Magnificent',
  },
  {
    name: 'John Calvin',
    value: 1509,
    id: 4236,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/John_Calvin',
  },
  {
    name: 'Ivan the Terrible',
    value: 1530,
    id: 4040,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Ivan_the_Terrible',
  },
  {
    name: 'Elizabeth I',
    value: 1533,
    id: 4041,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Elizabeth_I',
  },
  {
    name: 'Akbar the Great',
    value: 1542,
    id: 4042,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Akbar',
  },
  {
    name: 'Mary, Queen of Scots',
    value: 1542,
    id: 4237,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Mary,_Queen_of_Scots',
  },
  {
    name: 'Miguel de Cervantes',
    value: 1547,
    id: 4043,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Miguel_de_Cervantes',
  },
  {
    name: 'Francis Bacon',
    value: 1561,
    id: 4238,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Francis_Bacon',
  },
  {
    name: 'William Shakespeare',
    value: 1564,
    id: 4044,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/William_Shakespeare',
  },
  {
    name: 'Galileo Galilei',
    value: 1564,
    id: 4045,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Galileo_Galilei',
  },
  {
    name: 'Johannes Kepler',
    value: 1571,
    id: 4046,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Johannes_Kepler',
  },
  {
    name: 'Caravaggio',
    value: 1571,
    id: 4239,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Caravaggio',
  },
  {
    name: 'Thomas Hobbes',
    value: 1588,
    id: 4240,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Thomas_Hobbes',
  },
  {
    name: 'René Descartes',
    value: 1596,
    id: 4047,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Ren%C3%A9_Descartes',
  },
  {
    name: 'Gian Lorenzo Bernini',
    value: 1598,
    id: 4241,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Gian_Lorenzo_Bernini',
  },
  {
    name: 'Oliver Cromwell',
    value: 1599,
    id: 4242,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Oliver_Cromwell',
  },
  {
    name: 'Rembrandt',
    value: 1606,
    id: 4048,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Rembrandt',
  },
  {
    name: 'John Milton',
    value: 1608,
    id: 4243,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/John_Milton',
  },
  {
    name: 'Molière',
    value: 1622,
    id: 4244,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Moli%C3%A8re',
  },
  {
    name: 'Blaise Pascal',
    value: 1623,
    id: 4245,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Blaise_Pascal',
  },
  {
    name: 'John Locke',
    value: 1632,
    id: 4049,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/John_Locke',
  },
  {
    name: 'Baruch Spinoza',
    value: 1632,
    id: 4246,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Baruch_Spinoza',
  },
  {
    name: 'Antonie van Leeuwenhoek',
    value: 1632,
    id: 4247,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Antonie_van_Leeuwenhoek',
  },
  {
    name: 'Louis XIV',
    value: 1638,
    id: 4050,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Louis_XIV',
  },
  {
    name: 'Isaac Newton',
    value: 1642,
    id: 4051,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Isaac_Newton',
  },
  {
    name: 'Jonathan Swift',
    value: 1667,
    id: 4248,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Jonathan_Swift',
  },
  {
    name: 'Peter the Great',
    value: 1672,
    id: 4052,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Peter_the_Great',
  },
  {
    name: 'Antonio Vivaldi',
    value: 1678,
    id: 4053,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Antonio_Vivaldi',
  },
  {
    name: 'Johann Sebastian Bach',
    value: 1685,
    id: 4054,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Johann_Sebastian_Bach',
  },
  {
    name: 'George Frideric Handel',
    value: 1685,
    id: 4055,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/George_Frideric_Handel',
  },
  {
    name: 'Montesquieu',
    value: 1689,
    id: 4249,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Montesquieu',
  },
  {
    name: 'Voltaire',
    value: 1694,
    id: 4056,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Voltaire',
  },
  {
    name: 'Benjamin Franklin',
    value: 1706,
    id: 4057,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Benjamin_Franklin',
  },
  {
    name: 'Carl Linnaeus',
    value: 1707,
    id: 4250,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Carl_Linnaeus',
  },
  {
    name: 'David Hume',
    value: 1711,
    id: 4251,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/David_Hume',
  },
  {
    name: 'Jean-Jacques Rousseau',
    value: 1712,
    id: 4058,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Jean-Jacques_Rousseau',
  },
  {
    name: 'Adam Smith',
    value: 1723,
    id: 4059,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Adam_Smith',
  },
  {
    name: 'Immanuel Kant',
    value: 1724,
    id: 4060,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Immanuel_Kant',
  },
  {
    name: 'Casanova',
    value: 1725,
    id: 4252,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Giacomo_Casanova',
  },
  {
    name: 'James Cook',
    value: 1728,
    id: 4253,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/James_Cook',
  },
  {
    name: 'Catherine the Great',
    value: 1729,
    id: 4061,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Catherine_the_Great',
  },
  {
    name: 'George Washington',
    value: 1732,
    id: 4062,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/George_Washington',
  },
  {
    name: 'Joseph Haydn',
    value: 1732,
    id: 4254,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Joseph_Haydn',
  },
  {
    name: 'James Watt',
    value: 1736,
    id: 4255,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/James_Watt',
  },
  {
    name: 'Thomas Jefferson',
    value: 1743,
    id: 4063,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Thomas_Jefferson',
  },
  {
    name: 'Francisco Goya',
    value: 1746,
    id: 4256,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Francisco_Goya',
  },
  {
    name: 'Johann Wolfgang von Goethe',
    value: 1749,
    id: 4064,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Johann_Wolfgang_von_Goethe',
  },
  {
    name: 'Marie Antoinette',
    value: 1755,
    id: 4065,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Marie_Antoinette',
  },
  {
    name: 'Wolfgang Amadeus Mozart',
    value: 1756,
    id: 4066,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart',
  },
  {
    name: 'Mary Wollstonecraft',
    value: 1759,
    id: 4257,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Mary_Wollstonecraft',
  },
  {
    name: 'Robert Burns',
    value: 1759,
    id: 4258,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Robert_Burns',
  },
  {
    name: 'Hokusai',
    value: 1760,
    id: 4259,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Hokusai',
  },
  {
    name: 'Napoleon Bonaparte',
    value: 1769,
    id: 4067,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Napoleon',
  },
  {
    name: 'Ludwig van Beethoven',
    value: 1770,
    id: 4068,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Ludwig_van_Beethoven',
  },
  {
    name: 'Jane Austen',
    value: 1775,
    id: 4069,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Jane_Austen',
  },
  {
    name: 'Simón Bolívar',
    value: 1783,
    id: 4070,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Sim%C3%B3n_Bol%C3%ADvar',
  },
  {
    name: 'Lord Byron',
    value: 1788,
    id: 4260,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Lord_Byron',
  },
  {
    name: 'Arthur Schopenhauer',
    value: 1788,
    id: 4261,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Arthur_Schopenhauer',
  },
  {
    name: 'Michael Faraday',
    value: 1791,
    id: 4071,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Michael_Faraday',
  },
  {
    name: 'Gioachino Rossini',
    value: 1792,
    id: 4262,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Gioachino_Rossini',
  },
  {
    name: 'Mary Shelley',
    value: 1797,
    id: 4263,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Mary_Shelley',
  },
  {
    name: 'Franz Schubert',
    value: 1797,
    id: 4264,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Franz_Schubert',
  },
  {
    name: 'Alexander Pushkin',
    value: 1799,
    id: 4265,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Alexander_Pushkin',
  },
  {
    name: 'Victor Hugo',
    value: 1802,
    id: 4072,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Victor_Hugo',
  },
  {
    name: 'Alexandre Dumas',
    value: 1802,
    id: 4266,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Alexandre_Dumas',
  },
  {
    name: 'Ralph Waldo Emerson',
    value: 1803,
    id: 4267,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Ralph_Waldo_Emerson',
  },
  {
    name: 'Hans Christian Andersen',
    value: 1805,
    id: 4073,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Hans_Christian_Andersen',
  },
  {
    name: 'Giuseppe Garibaldi',
    value: 1807,
    id: 4268,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Giuseppe_Garibaldi',
  },
  {
    name: 'Abraham Lincoln',
    value: 1809,
    id: 4074,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Abraham_Lincoln',
  },
  {
    name: 'Charles Darwin',
    value: 1809,
    id: 4075,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Charles_Darwin',
  },
  {
    name: 'Edgar Allan Poe',
    value: 1809,
    id: 4076,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Edgar_Allan_Poe',
  },
  {
    name: 'Frédéric Chopin',
    value: 1810,
    id: 4077,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Chopin',
  },
  {
    name: 'Charles Dickens',
    value: 1812,
    id: 4078,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Charles_Dickens',
  },
  {
    name: 'Richard Wagner',
    value: 1813,
    id: 4079,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Richard_Wagner',
  },
  {
    name: 'Søren Kierkegaard',
    value: 1813,
    id: 4269,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/S%C3%B8ren_Kierkegaard',
  },
  {
    name: 'Otto von Bismarck',
    value: 1815,
    id: 4080,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Otto_von_Bismarck',
  },
  {
    name: 'Ada Lovelace',
    value: 1815,
    id: 4081,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Ada_Lovelace',
  },
  {
    name: 'Charlotte Brontë',
    value: 1816,
    id: 4270,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Charlotte_Bront%C3%AB',
  },
  {
    name: 'Karl Marx',
    value: 1818,
    id: 4082,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Karl_Marx',
  },
  {
    name: 'Frederick Douglass',
    value: 1818,
    id: 4083,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Frederick_Douglass',
  },
  {
    name: 'Queen Victoria',
    value: 1819,
    id: 4084,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Queen_Victoria',
  },
  {
    name: 'Herman Melville',
    value: 1819,
    id: 4271,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Herman_Melville',
  },
  {
    name: 'Walt Whitman',
    value: 1819,
    id: 4272,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Walt_Whitman',
  },
  {
    name: 'Florence Nightingale',
    value: 1820,
    id: 4085,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Florence_Nightingale',
  },
  {
    name: 'Fyodor Dostoevsky',
    value: 1821,
    id: 4086,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Fyodor_Dostoevsky',
  },
  {
    name: 'Louis Pasteur',
    value: 1822,
    id: 4087,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Louis_Pasteur',
  },
  {
    name: 'Harriet Tubman',
    value: 1822,
    id: 4088,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Harriet_Tubman',
  },
  {
    name: 'Gregor Mendel',
    value: 1822,
    id: 4273,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Gregor_Mendel',
  },
  {
    name: 'Anton Bruckner',
    value: 1824,
    id: 4338,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Anton_Bruckner',
  },
  {
    name: 'Leo Tolstoy',
    value: 1828,
    id: 4089,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Leo_Tolstoy',
  },
  {
    name: 'Jules Verne',
    value: 1828,
    id: 4274,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Jules_Verne',
  },
  {
    name: 'Gustave Eiffel',
    value: 1832,
    id: 4275,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Gustave_Eiffel',
  },
  {
    name: 'Lewis Carroll',
    value: 1832,
    id: 4276,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Lewis_Carroll',
  },
  {
    name: 'Johannes Brahms',
    value: 1833,
    id: 4277,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Johannes_Brahms',
  },
  {
    name: 'Alfred Nobel',
    value: 1833,
    id: 4278,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Alfred_Nobel',
  },
  {
    name: 'Mark Twain',
    value: 1835,
    id: 4090,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mark_Twain',
  },
  {
    name: 'John D. Rockefeller',
    value: 1839,
    id: 4091,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/John_D._Rockefeller',
  },
  {
    name: 'Paul Cézanne',
    value: 1839,
    id: 4279,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Paul_C%C3%A9zanne',
  },
  {
    name: 'Claude Monet',
    value: 1840,
    id: 4092,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Claude_Monet',
  },
  {
    name: 'Pyotr Tchaikovsky',
    value: 1840,
    id: 4093,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pyotr_Ilyich_Tchaikovsky',
  },
  {
    name: 'Friedrich Nietzsche',
    value: 1844,
    id: 4094,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Friedrich_Nietzsche',
  },
  {
    name: 'Thomas Edison',
    value: 1847,
    id: 4095,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Thomas_Edison',
  },
  {
    name: 'Alexander Graham Bell',
    value: 1847,
    id: 4096,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Alexander_Graham_Bell',
  },
  {
    name: 'Vincent van Gogh',
    value: 1853,
    id: 4097,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Vincent_van_Gogh',
  },
  {
    name: 'Sigmund Freud',
    value: 1856,
    id: 4098,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Sigmund_Freud',
  },
  {
    name: 'Nikola Tesla',
    value: 1856,
    id: 4099,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Nikola_Tesla',
  },
  {
    name: 'Max Planck',
    value: 1858,
    id: 4100,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Max_Planck',
  },
  {
    name: 'Arthur Conan Doyle',
    value: 1859,
    id: 4101,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Arthur_Conan_Doyle',
  },
  {
    name: 'Anton Chekhov',
    value: 1860,
    id: 4280,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Anton_Chekhov',
  },
  {
    name: 'Gustav Mahler',
    value: 1860,
    id: 4281,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Gustav_Mahler',
  },
  {
    name: 'Claude Debussy',
    value: 1862,
    id: 4282,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Claude_Debussy',
  },
  {
    name: 'Henry Ford',
    value: 1863,
    id: 4102,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Henry_Ford',
  },
  {
    name: 'Edvard Munch',
    value: 1863,
    id: 4283,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Edvard_Munch',
  },
  {
    name: 'H.G. Wells',
    value: 1866,
    id: 4284,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/H._G._Wells',
  },
  {
    name: 'Marie Curie',
    value: 1867,
    id: 4103,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Marie_Curie',
  },
  {
    name: 'Wilbur Wright (Wright brothers)',
    value: 1867,
    id: 4104,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Wright_brothers',
  },
  {
    name: 'Frank Lloyd Wright',
    value: 1867,
    id: 4285,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Frank_Lloyd_Wright',
  },
  {
    name: 'Mahatma Gandhi',
    value: 1869,
    id: 4105,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mahatma_Gandhi',
  },
  {
    name: 'Vladimir Lenin',
    value: 1870,
    id: 4106,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Vladimir_Lenin',
  },
  {
    name: 'Orville Wright (Wright brothers)',
    value: 1871,
    id: 4107,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Wright_brothers',
  },
  {
    name: 'Sergei Rachmaninoff',
    value: 1873,
    id: 4286,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Sergei_Rachmaninoff',
  },
  {
    name: 'Winston Churchill',
    value: 1874,
    id: 4108,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Winston_Churchill',
  },
  {
    name: 'Guglielmo Marconi',
    value: 1874,
    id: 4109,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Guglielmo_Marconi',
  },
  {
    name: 'Thomas Mann',
    value: 1875,
    id: 4287,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Thomas_Mann',
  },
  {
    name: 'Carl Jung',
    value: 1875,
    id: 4288,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Carl_Jung',
  },
  {
    name: 'Joseph Stalin',
    value: 1878,
    id: 4110,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Joseph_Stalin',
  },
  {
    name: 'Albert Einstein',
    value: 1879,
    id: 4111,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Albert_Einstein',
  },
  {
    name: 'Pablo Picasso',
    value: 1881,
    id: 4112,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pablo_Picasso',
  },
  {
    name: 'Mustafa Kemal Atatürk',
    value: 1881,
    id: 4113,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Mustafa_Kemal_Atat%C3%BCrk',
  },
  {
    name: 'James Joyce',
    value: 1882,
    id: 4114,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/James_Joyce',
  },
  {
    name: 'Virginia Woolf',
    value: 1882,
    id: 4115,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Virginia_Woolf',
  },
  {
    name: 'Franklin D. Roosevelt',
    value: 1882,
    id: 4116,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Franklin_D._Roosevelt',
  },
  {
    name: 'Franz Kafka',
    value: 1883,
    id: 4117,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Franz_Kafka',
  },
  {
    name: 'Coco Chanel',
    value: 1883,
    id: 4118,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Coco_Chanel',
  },
  {
    name: 'Benito Mussolini',
    value: 1883,
    id: 4119,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Benito_Mussolini',
  },
  {
    name: 'Niels Bohr',
    value: 1885,
    id: 4120,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Niels_Bohr',
  },
  {
    name: 'Georgia O\'Keeffe',
    value: 1887,
    id: 4289,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Georgia_O%27Keeffe',
  },
  {
    name: 'T. S. Eliot',
    value: 1888,
    id: 4290,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/T._S._Eliot',
  },
  {
    name: 'Adolf Hitler',
    value: 1889,
    id: 4121,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Adolf_Hitler',
  },
  {
    name: 'Charlie Chaplin',
    value: 1889,
    id: 4122,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Charlie_Chaplin',
  },
  {
    name: 'Charles de Gaulle',
    value: 1890,
    id: 4123,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Charles_de_Gaulle',
  },
  {
    name: 'Agatha Christie',
    value: 1890,
    id: 4124,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Agatha_Christie',
  },
  {
    name: 'Ho Chi Minh',
    value: 1890,
    id: 4291,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Ho_Chi_Minh',
  },
  {
    name: 'J.R.R. Tolkien',
    value: 1892,
    id: 4125,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/J._R._R._Tolkien',
  },
  {
    name: 'Mao Zedong',
    value: 1893,
    id: 4126,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mao_Zedong',
  },
  {
    name: 'Amelia Earhart',
    value: 1897,
    id: 4127,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Amelia_Earhart',
  },
  {
    name: 'Ernest Hemingway',
    value: 1899,
    id: 4128,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Ernest_Hemingway',
  },
  {
    name: 'Alfred Hitchcock',
    value: 1899,
    id: 4129,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Alfred_Hitchcock',
  },
  {
    name: 'Louis Armstrong',
    value: 1901,
    id: 4130,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Louis_Armstrong',
  },
  {
    name: 'Walt Disney',
    value: 1901,
    id: 4131,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Walt_Disney',
  },
  {
    name: 'Werner Heisenberg',
    value: 1901,
    id: 4292,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Werner_Heisenberg',
  },
  {
    name: 'Enrico Fermi',
    value: 1901,
    id: 4293,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Enrico_Fermi',
  },
  {
    name: 'George Orwell',
    value: 1903,
    id: 4132,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/George_Orwell',
  },
  {
    name: 'John von Neumann',
    value: 1903,
    id: 4294,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/John_von_Neumann',
  },
  {
    name: 'Salvador Dalí',
    value: 1904,
    id: 4133,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Salvador_Dal%C3%AD',
  },
  {
    name: 'J. Robert Oppenheimer',
    value: 1904,
    id: 4134,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/J._Robert_Oppenheimer',
  },
  {
    name: 'Frida Kahlo',
    value: 1907,
    id: 4135,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Frida_Kahlo',
  },
  {
    name: 'Simone de Beauvoir',
    value: 1908,
    id: 4295,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Simone_de_Beauvoir',
  },
  {
    name: 'Lyndon B. Johnson',
    value: 1908,
    id: 4296,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Lyndon_B._Johnson',
  },
  {
    name: 'Mother Teresa',
    value: 1910,
    id: 4136,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Mother_Teresa',
  },
  {
    name: 'Akira Kurosawa',
    value: 1910,
    id: 4297,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Akira_Kurosawa',
  },
  {
    name: 'Ronald Reagan',
    value: 1911,
    id: 4137,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Ronald_Reagan',
  },
  {
    name: 'Alan Turing',
    value: 1912,
    id: 4138,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Alan_Turing',
  },
  {
    name: 'Rosa Parks',
    value: 1913,
    id: 4139,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Rosa_Parks',
  },
  {
    name: 'Richard Nixon',
    value: 1913,
    id: 4140,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Richard_Nixon',
  },
  {
    name: 'Albert Camus',
    value: 1913,
    id: 4298,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Albert_Camus',
  },
  {
    name: 'Frank Sinatra',
    value: 1915,
    id: 4141,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Frank_Sinatra',
  },
  {
    name: 'Billie Holiday',
    value: 1915,
    id: 4299,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Billie_Holiday',
  },
  {
    name: 'John F. Kennedy',
    value: 1917,
    id: 4142,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/John_F._Kennedy',
  },
  {
    name: 'Nelson Mandela',
    value: 1918,
    id: 4143,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Nelson_Mandela',
  },
  {
    name: 'Richard Feynman',
    value: 1918,
    id: 4144,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Richard_Feynman',
  },
  {
    name: 'Eva Perón',
    value: 1919,
    id: 4300,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Eva_Per%C3%B3n',
  },
  {
    name: 'Pope John Paul II',
    value: 1920,
    id: 4145,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pope_John_Paul_II',
  },
  {
    name: 'Isaac Asimov',
    value: 1920,
    id: 4301,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Isaac_Asimov',
  },
  {
    name: 'Stan Lee',
    value: 1922,
    id: 4302,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Stan_Lee',
  },
  {
    name: 'Marlon Brando',
    value: 1924,
    id: 4146,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Marlon_Brando',
  },
  {
    name: 'Margaret Thatcher',
    value: 1925,
    id: 4147,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Margaret_Thatcher',
  },
  {
    name: 'Malcolm X',
    value: 1925,
    id: 4148,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Malcolm_X',
  },
  {
    name: 'Queen Elizabeth II',
    value: 1926,
    id: 4149,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Elizabeth_II',
  },
  {
    name: 'Marilyn Monroe',
    value: 1926,
    id: 4150,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Marilyn_Monroe',
  },
  {
    name: 'Fidel Castro',
    value: 1926,
    id: 4151,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Fidel_Castro',
  },
  {
    name: 'Miles Davis',
    value: 1926,
    id: 4303,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Miles_Davis',
  },
  {
    name: 'Gabriel García Márquez',
    value: 1927,
    id: 4152,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Gabriel_Garc%C3%ADa_M%C3%A1rquez',
  },
  {
    name: 'Che Guevara',
    value: 1928,
    id: 4153,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Che_Guevara',
  },
  {
    name: 'Andy Warhol',
    value: 1928,
    id: 4154,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Andy_Warhol',
  },
  {
    name: 'Stanley Kubrick',
    value: 1928,
    id: 4155,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Stanley_Kubrick',
  },
  {
    name: 'Anne Frank',
    value: 1929,
    id: 4156,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Anne_Frank',
  },
  {
    name: 'Martin Luther King Jr.',
    value: 1929,
    id: 4157,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Martin_Luther_King_Jr.',
  },
  {
    name: 'Audrey Hepburn',
    value: 1929,
    id: 4158,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Audrey_Hepburn',
  },
  {
    name: 'Neil Armstrong',
    value: 1930,
    id: 4159,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Neil_Armstrong',
  },
  {
    name: 'Warren Buffett',
    value: 1930,
    id: 4160,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Warren_Buffett',
  },
  {
    name: 'Clint Eastwood',
    value: 1930,
    id: 4161,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Clint_Eastwood',
  },
  {
    name: 'Sean Connery',
    value: 1930,
    id: 4304,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Sean_Connery',
  },
  {
    name: 'Ray Charles',
    value: 1930,
    id: 4305,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Ray_Charles',
  },
  {
    name: 'Mikhail Gorbachev',
    value: 1931,
    id: 4162,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mikhail_Gorbachev',
  },
  {
    name: 'Yuri Gagarin',
    value: 1934,
    id: 4163,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Yuri_Gagarin',
  },
  {
    name: 'Jane Goodall',
    value: 1934,
    id: 4306,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Jane_Goodall',
  },
  {
    name: 'Elvis Presley',
    value: 1935,
    id: 4164,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Elvis_Presley',
  },
  {
    name: 'The 14th Dalai Lama',
    value: 1935,
    id: 4165,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/14th_Dalai_Lama',
  },
  {
    name: 'Luciano Pavarotti',
    value: 1935,
    id: 4307,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Luciano_Pavarotti',
  },
  {
    name: 'Pope Francis',
    value: 1936,
    id: 4166,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pope_Francis',
  },
  {
    name: 'Bruce Lee',
    value: 1940,
    id: 4167,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Bruce_Lee',
  },
  {
    name: 'John Lennon',
    value: 1940,
    id: 4168,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/John_Lennon',
  },
  {
    name: 'Pelé',
    value: 1940,
    id: 4169,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pel%C3%A9',
  },
  {
    name: 'Bob Dylan',
    value: 1941,
    id: 4170,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Bob_Dylan',
  },
  {
    name: 'Muhammad Ali',
    value: 1942,
    id: 4171,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Muhammad_Ali',
  },
  {
    name: 'Stephen Hawking',
    value: 1942,
    id: 4172,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Stephen_Hawking',
  },
  {
    name: 'Paul McCartney',
    value: 1942,
    id: 4173,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Paul_McCartney',
  },
  {
    name: 'Joe Biden',
    value: 1942,
    id: 4174,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Joe_Biden',
  },
  {
    name: 'Jimi Hendrix',
    value: 1942,
    id: 4308,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Jimi_Hendrix',
  },
  {
    name: 'Mick Jagger',
    value: 1943,
    id: 4175,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mick_Jagger',
  },
  {
    name: 'Bob Marley',
    value: 1945,
    id: 4309,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Bob_Marley',
  },
  {
    name: 'Freddie Mercury',
    value: 1946,
    id: 4176,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Freddie_Mercury',
  },
  {
    name: 'Donald Trump',
    value: 1946,
    id: 4177,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Donald_Trump',
  },
  {
    name: 'Steven Spielberg',
    value: 1946,
    id: 4178,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Steven_Spielberg',
  },
  {
    name: 'Bill Clinton',
    value: 1946,
    id: 4179,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Bill_Clinton',
  },
  {
    name: 'David Bowie',
    value: 1947,
    id: 4180,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/David_Bowie',
  },
  {
    name: 'Arnold Schwarzenegger',
    value: 1947,
    id: 4181,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Arnold_Schwarzenegger',
  },
  {
    name: 'Stephen King',
    value: 1947,
    id: 4310,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Stephen_King',
  },
  {
    name: 'Elton John',
    value: 1947,
    id: 4311,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Elton_John',
  },
  {
    name: 'Hillary Clinton',
    value: 1947,
    id: 4312,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Hillary_Clinton',
  },
  {
    name: 'George R.R. Martin',
    value: 1948,
    id: 4313,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/George_R._R._Martin',
  },
  {
    name: 'Meryl Streep',
    value: 1949,
    id: 4314,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Meryl_Streep',
  },
  {
    name: 'Narendra Modi',
    value: 1950,
    id: 4182,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Narendra_Modi',
  },
  {
    name: 'Robin Williams',
    value: 1951,
    id: 4315,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Robin_Williams',
  },
  {
    name: 'Vladimir Putin',
    value: 1952,
    id: 4183,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Vladimir_Putin',
  },
  {
    name: 'Xi Jinping',
    value: 1953,
    id: 4184,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Xi_Jinping',
  },
  {
    name: 'Oprah Winfrey',
    value: 1954,
    id: 4185,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Oprah_Winfrey',
  },
  {
    name: 'Angela Merkel',
    value: 1954,
    id: 4186,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Angela_Merkel',
  },
  {
    name: 'Denzel Washington',
    value: 1954,
    id: 4316,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Denzel_Washington',
  },
  {
    name: 'Bill Gates',
    value: 1955,
    id: 4187,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Bill_Gates',
  },
  {
    name: 'Steve Jobs',
    value: 1955,
    id: 4188,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Steve_Jobs',
  },
  {
    name: 'Tom Hanks',
    value: 1956,
    id: 4317,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Tom_Hanks',
  },
  {
    name: 'Michael Jackson',
    value: 1958,
    id: 4189,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Michael_Jackson',
  },
  {
    name: 'Madonna',
    value: 1958,
    id: 4190,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Madonna',
  },
  {
    name: 'Prince',
    value: 1958,
    id: 4318,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Prince_(musician)',
  },
  {
    name: 'Diego Maradona',
    value: 1960,
    id: 4191,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Diego_Maradona',
  },
  {
    name: 'Princess Diana',
    value: 1961,
    id: 4192,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Diana,_Princess_of_Wales',
  },
  {
    name: 'Barack Obama',
    value: 1961,
    id: 4193,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Barack_Obama',
  },
  {
    name: 'Michael Jordan',
    value: 1963,
    id: 4194,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Michael_Jordan',
  },
  {
    name: 'Quentin Tarantino',
    value: 1963,
    id: 4319,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Quentin_Tarantino',
  },
  {
    name: 'Jeff Bezos',
    value: 1964,
    id: 4195,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Jeff_Bezos',
  },
  {
    name: 'Keanu Reeves',
    value: 1964,
    id: 4320,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Keanu_Reeves',
  },
  {
    name: 'J.K. Rowling',
    value: 1965,
    id: 4196,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/J._K._Rowling',
  },
  {
    name: 'Kurt Cobain',
    value: 1967,
    id: 4321,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Kurt_Cobain',
  },
  {
    name: 'Celine Dion',
    value: 1968,
    id: 4322,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Celine_Dion',
  },
  {
    name: 'Elon Musk',
    value: 1971,
    id: 4197,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Elon_Musk',
  },
  {
    name: 'Eminem',
    value: 1972,
    id: 4323,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Eminem',
  },
  {
    name: 'Leonardo DiCaprio',
    value: 1974,
    id: 4324,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Leonardo_DiCaprio',
  },
  {
    name: 'Tiger Woods',
    value: 1975,
    id: 4198,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Tiger_Woods',
  },
  {
    name: 'Angelina Jolie',
    value: 1975,
    id: 4325,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Angelina_Jolie',
  },
  {
    name: 'Shakira',
    value: 1977,
    id: 4326,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Shakira',
  },
  {
    name: 'Beyoncé',
    value: 1981,
    id: 4199,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Beyonc%C3%A9',
  },
  {
    name: 'Roger Federer',
    value: 1981,
    id: 4200,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Roger_Federer',
  },
  {
    name: 'Serena Williams',
    value: 1981,
    id: 4327,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Serena_Williams',
  },
  {
    name: 'Anne Hathaway',
    value: 1982,
    id: 4339,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Anne_Hathaway',
  },
  {
    name: 'Mark Zuckerberg',
    value: 1984,
    id: 4201,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mark_Zuckerberg',
  },
  {
    name: 'LeBron James',
    value: 1984,
    id: 4202,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/LeBron_James',
  },
  {
    name: 'Cristiano Ronaldo',
    value: 1985,
    id: 4203,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Cristiano_Ronaldo',
  },
  {
    name: 'Lewis Hamilton',
    value: 1985,
    id: 4328,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Lewis_Hamilton',
  },
  {
    name: 'Usain Bolt',
    value: 1986,
    id: 4329,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Usain_Bolt',
  },
  {
    name: 'Lionel Messi',
    value: 1987,
    id: 4204,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Lionel_Messi',
  },
  {
    name: 'Adele',
    value: 1988,
    id: 4330,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Adele',
  },
  {
    name: 'Taylor Swift',
    value: 1989,
    id: 4331,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Taylor_Swift',
  },
  {
    name: 'Ed Sheeran',
    value: 1991,
    id: 4332,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Ed_Sheeran',
  },
  {
    name: 'Selena Gomez',
    value: 1992,
    id: 4333,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Selena_Gomez',
  },
  {
    name: 'Justin Bieber',
    value: 1994,
    id: 4334,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Justin_Bieber',
  },
  {
    name: 'Timothée Chalamet',
    value: 1995,
    id: 4335,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Timoth%C3%A9e_Chalamet',
  },
  {
    name: 'Tom Holland',
    value: 1996,
    id: 4336,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Tom_Holland',
  },
  {
    name: 'Billie Eilish',
    value: 2001,
    id: 4337,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Billie_Eilish',
  },
];