import {type Difficulty} from './difficulty.js';

export interface FamousBirth {
  name: string;
  value: number;
  difficulty: Difficulty;
}

export const famousBirths: FamousBirth[] = [
  {name: 'Gautama Buddha', value: -563, difficulty: 'easy'},
  {name: 'Confucius', value: -551, difficulty: 'medium'},
  {name: 'Socrates', value: -470, difficulty: 'easy'},  // c. 470 BC
  {name: 'Plato', value: -428, difficulty: 'medium'},   // c. 428 BC
  {name: 'Aristotle', value: -384, difficulty: 'easy'},
  {name: 'Alexander the Great', value: -356, difficulty: 'medium'},
  {name: 'Archimedes', value: -287, difficulty: 'hard'},  // c. 287 BC
  {name: 'Qin Shi Huang', value: -259, difficulty: 'hard'},
  {name: 'Hannibal', value: -247, difficulty: 'hard'},
  {name: 'Cicero', value: -106, difficulty: 'hard'},
  {name: 'Julius Caesar', value: -100, difficulty: 'easy'},
  {name: 'Virgil', value: -70, difficulty: 'hard'},
  {name: 'Cleopatra', value: -69, difficulty: 'medium'},
  {name: 'Augustus', value: -63, difficulty: 'medium'},
  {name: 'Jesus of Nazareth', value: -4, difficulty: 'easy'},  // c. 4 BC
  {name: 'Nero', value: 37, difficulty: 'medium'},
  {name: 'Marcus Aurelius', value: 121, difficulty: 'easy'},
  {name: 'Constantine the Great', value: 272, difficulty: 'hard'},
  {name: 'Muhammad', value: 570, difficulty: 'easy'},  // c. 570
  {name: 'Charlemagne', value: 748, difficulty: 'hard'},
  {name: 'William the Conqueror', value: 1028, difficulty: 'hard'},  // c. 1028
  {name: 'Saladin', value: 1137, difficulty: 'hard'},
  {name: 'Genghis Khan', value: 1162, difficulty: 'easy'},  // c. 1162
  {name: 'Thomas Aquinas', value: 1225, difficulty: 'medium'},
  {name: 'Marco Polo', value: 1254, difficulty: 'medium'},
  {name: 'Dante Alighieri', value: 1265, difficulty: 'easy'},     // c. 1265
  {name: 'Geoffrey Chaucer', value: 1343, difficulty: 'hard'},    // c. 1343
  {name: 'Johannes Gutenberg', value: 1400, difficulty: 'easy'},  // c. 1400
  {name: 'Joan of Arc', value: 1412, difficulty: 'medium'},       // c. 1412
  {name: 'Christopher Columbus', value: 1451, difficulty: 'easy'},
  {name: 'Leonardo da Vinci', value: 1452, difficulty: 'easy'},
  {name: 'Niccolò Machiavelli', value: 1469, difficulty: 'medium'},
  {name: 'Nicolaus Copernicus', value: 1473, difficulty: 'easy'},
  {name: 'Michelangelo', value: 1475, difficulty: 'easy'},
  {name: 'Francisco Pizarro', value: 1478, difficulty: 'hard'},
  {name: 'Ferdinand Magellan', value: 1480, difficulty: 'hard'},
  {name: 'Hernán Cortés', value: 1485, difficulty: 'hard'},
  {name: 'Martin Luther', value: 1483, difficulty: 'medium'},
  {name: 'Henry VIII', value: 1491, difficulty: 'hard'},
  {name: 'Suleiman the Magnificent', value: 1494, difficulty: 'hard'},
  {name: 'Ivan the Terrible', value: 1530, difficulty: 'hard'},
  {name: 'Elizabeth I', value: 1533, difficulty: 'hard'},
  {name: 'Akbar the Great', value: 1542, difficulty: 'hard'},
  {name: 'Miguel de Cervantes', value: 1547, difficulty: 'easy'},
  {name: 'William Shakespeare', value: 1564, difficulty: 'easy'},
  {name: 'Galileo Galilei', value: 1564, difficulty: 'medium'},
  {name: 'Johannes Kepler', value: 1571, difficulty: 'hard'},
  {name: 'René Descartes', value: 1596, difficulty: 'medium'},
  {name: 'Rembrandt', value: 1606, difficulty: 'medium'},
  {name: 'John Locke', value: 1632, difficulty: 'medium'},
  {name: 'Louis XIV', value: 1638, difficulty: 'hard'},
  {name: 'Isaac Newton', value: 1642, difficulty: 'easy'},
  {name: 'Peter the Great', value: 1672, difficulty: 'hard'},
  {name: 'Antonio Vivaldi', value: 1678, difficulty: 'medium'},
  {name: 'Johann Sebastian Bach', value: 1685, difficulty: 'easy'},
  {name: 'George Frideric Handel', value: 1685, difficulty: 'hard'},
  {name: 'Voltaire', value: 1694, difficulty: 'medium'},
  {name: 'Benjamin Franklin', value: 1706, difficulty: 'medium'},
  {name: 'Jean-Jacques Rousseau', value: 1712, difficulty: 'hard'},
  {name: 'Adam Smith', value: 1723, difficulty: 'medium'},
  {name: 'Immanuel Kant', value: 1724, difficulty: 'medium'},
  {name: 'Catherine the Great', value: 1729, difficulty: 'hard'},
  {name: 'George Washington', value: 1732, difficulty: 'easy'},
  {name: 'Thomas Jefferson', value: 1743, difficulty: 'medium'},
  {name: 'Johann Wolfgang von Goethe', value: 1749, difficulty: 'easy'},
  {name: 'Marie Antoinette', value: 1755, difficulty: 'hard'},
  {name: 'Wolfgang Amadeus Mozart', value: 1756, difficulty: 'easy'},
  {name: 'Napoleon Bonaparte', value: 1769, difficulty: 'easy'},
  {name: 'Ludwig van Beethoven', value: 1770, difficulty: 'easy'},
  {name: 'Jane Austen', value: 1775, difficulty: 'hard'},
  {name: 'Simón Bolívar', value: 1783, difficulty: 'medium'},
  {name: 'Michael Faraday', value: 1791, difficulty: 'medium'},
  {name: 'Victor Hugo', value: 1802, difficulty: 'medium'},
  {name: 'Hans Christian Andersen', value: 1805, difficulty: 'medium'},
  {name: 'Abraham Lincoln', value: 1809, difficulty: 'easy'},
  {name: 'Charles Darwin', value: 1809, difficulty: 'easy'},
  {name: 'Edgar Allan Poe', value: 1809, difficulty: 'easy'},
  {name: 'Frédéric Chopin', value: 1810, difficulty: 'easy'},
  {name: 'Charles Dickens', value: 1812, difficulty: 'medium'},
  {name: 'Richard Wagner', value: 1813, difficulty: 'medium'},
  {name: 'Otto von Bismarck', value: 1815, difficulty: 'hard'},
  {name: 'Ada Lovelace', value: 1815, difficulty: 'medium'},
  {name: 'Karl Marx', value: 1818, difficulty: 'medium'},
  {name: 'Frederick Douglass', value: 1818, difficulty: 'hard'},  // c. 1818
  {name: 'Queen Victoria', value: 1819, difficulty: 'medium'},
  {name: 'Florence Nightingale', value: 1820, difficulty: 'hard'},
  {name: 'Fyodor Dostoevsky', value: 1821, difficulty: 'easy'},
  {name: 'Louis Pasteur', value: 1822, difficulty: 'medium'},
  {name: 'Harriet Tubman', value: 1822, difficulty: 'hard'},  // c. 1822
  {name: 'Leo Tolstoy', value: 1828, difficulty: 'easy'},
  {name: 'Mark Twain', value: 1835, difficulty: 'medium'},
  {name: 'John D. Rockefeller', value: 1839, difficulty: 'medium'},
  {name: 'Claude Monet', value: 1840, difficulty: 'easy'},
  {name: 'Pyotr Tchaikovsky', value: 1840, difficulty: 'easy'},
  {name: 'Friedrich Nietzsche', value: 1844, difficulty: 'easy'},
  {name: 'Thomas Edison', value: 1847, difficulty: 'easy'},
  {name: 'Alexander Graham Bell', value: 1847, difficulty: 'easy'},
  {name: 'Vincent van Gogh', value: 1853, difficulty: 'easy'},
  {name: 'Sigmund Freud', value: 1856, difficulty: 'easy'},
  {name: 'Nikola Tesla', value: 1856, difficulty: 'easy'},
  {name: 'Max Planck', value: 1858, difficulty: 'medium'},
  {name: 'Arthur Conan Doyle', value: 1859, difficulty: 'easy'},
  {name: 'Henry Ford', value: 1863, difficulty: 'easy'},
  {name: 'Marie Curie', value: 1867, difficulty: 'medium'},
  {name: 'Wilbur Wright (Wright brothers)', value: 1867, difficulty: 'easy'},
  {name: 'Mahatma Gandhi', value: 1869, difficulty: 'easy'},
  {name: 'Vladimir Lenin', value: 1870, difficulty: 'easy'},
  {name: 'Orville Wright (Wright brothers)', value: 1871, difficulty: 'easy'},
  {name: 'Winston Churchill', value: 1874, difficulty: 'easy'},
  {name: 'Guglielmo Marconi', value: 1874, difficulty: 'medium'},
  {name: 'Joseph Stalin', value: 1878, difficulty: 'easy'},
  {name: 'Albert Einstein', value: 1879, difficulty: 'easy'},
  {name: 'Pablo Picasso', value: 1881, difficulty: 'easy'},
  {name: 'Mustafa Kemal Atatürk', value: 1881, difficulty: 'medium'},
  {name: 'James Joyce', value: 1882, difficulty: 'medium'},
  {name: 'Virginia Woolf', value: 1882, difficulty: 'medium'},
  {name: 'Franklin D. Roosevelt', value: 1882, difficulty: 'medium'},
  {name: 'Franz Kafka', value: 1883, difficulty: 'easy'},
  {name: 'Coco Chanel', value: 1883, difficulty: 'medium'},
  {name: 'Benito Mussolini', value: 1883, difficulty: 'easy'},
  {name: 'Niels Bohr', value: 1885, difficulty: 'medium'},
  {name: 'Adolf Hitler', value: 1889, difficulty: 'easy'},
  {name: 'Charlie Chaplin', value: 1889, difficulty: 'easy'},
  {name: 'Charles de Gaulle', value: 1890, difficulty: 'medium'},
  {name: 'Agatha Christie', value: 1890, difficulty: 'medium'},
  {name: 'J.R.R. Tolkien', value: 1892, difficulty: 'easy'},
  {name: 'Mao Zedong', value: 1893, difficulty: 'easy'},
  {name: 'Amelia Earhart', value: 1897, difficulty: 'medium'},
  {name: 'Ernest Hemingway', value: 1899, difficulty: 'easy'},
  {name: 'Alfred Hitchcock', value: 1899, difficulty: 'easy'},
  {name: 'Louis Armstrong', value: 1901, difficulty: 'medium'},
  {name: 'Walt Disney', value: 1901, difficulty: 'easy'},
  {name: 'George Orwell', value: 1903, difficulty: 'medium'},
  {name: 'Salvador Dalí', value: 1904, difficulty: 'easy'},
  {name: 'J. Robert Oppenheimer', value: 1904, difficulty: 'easy'},
  {name: 'Frida Kahlo', value: 1907, difficulty: 'easy'},
  {name: 'Mother Teresa', value: 1910, difficulty: 'medium'},
  {name: 'Ronald Reagan', value: 1911, difficulty: 'easy'},
  {name: 'Alan Turing', value: 1912, difficulty: 'easy'},
  {name: 'Rosa Parks', value: 1913, difficulty: 'easy'},
  {name: 'Richard Nixon', value: 1913, difficulty: 'medium'},
  {name: 'Frank Sinatra', value: 1915, difficulty: 'easy'},
  {name: 'John F. Kennedy', value: 1917, difficulty: 'easy'},
  {name: 'Nelson Mandela', value: 1918, difficulty: 'easy'},
  {name: 'Richard Feynman', value: 1918, difficulty: 'easy'},
  {name: 'Pope John Paul II', value: 1920, difficulty: 'easy'},
  {name: 'Marlon Brando', value: 1924, difficulty: 'easy'},
  {name: 'Margaret Thatcher', value: 1925, difficulty: 'easy'},
  {name: 'Malcolm X', value: 1925, difficulty: 'medium'},
  {name: 'Queen Elizabeth II', value: 1926, difficulty: 'medium'},
  {name: 'Marilyn Monroe', value: 1926, difficulty: 'easy'},
  {name: 'Fidel Castro', value: 1926, difficulty: 'easy'},
  {name: 'Gabriel García Márquez', value: 1927, difficulty: 'easy'},
  {name: 'Che Guevara', value: 1928, difficulty: 'easy'},
  {name: 'Andy Warhol', value: 1928, difficulty: 'easy'},
  {name: 'Stanley Kubrick', value: 1928, difficulty: 'easy'},
  {name: 'Anne Frank', value: 1929, difficulty: 'easy'},
  {name: 'Martin Luther King Jr.', value: 1929, difficulty: 'easy'},
  {name: 'Audrey Hepburn', value: 1929, difficulty: 'easy'},
  {name: 'Neil Armstrong', value: 1930, difficulty: 'easy'},
  {name: 'Warren Buffett', value: 1930, difficulty: 'easy'},
  {name: 'Clint Eastwood', value: 1930, difficulty: 'easy'},
  {name: 'Mikhail Gorbachev', value: 1931, difficulty: 'easy'},
  {name: 'Yuri Gagarin', value: 1934, difficulty: 'medium'},
  {name: 'Elvis Presley', value: 1935, difficulty: 'easy'},
  {name: 'The 14th Dalai Lama', value: 1935, difficulty: 'medium'},
  {name: 'Pope Francis', value: 1936, difficulty: 'easy'},
  {name: 'Bruce Lee', value: 1940, difficulty: 'easy'},
  {name: 'John Lennon', value: 1940, difficulty: 'easy'},
  {name: 'Pelé', value: 1940, difficulty: 'easy'},
  {name: 'Bob Dylan', value: 1941, difficulty: 'easy'},
  {name: 'Muhammad Ali', value: 1942, difficulty: 'easy'},
  {name: 'Stephen Hawking', value: 1942, difficulty: 'medium'},
  {name: 'Paul McCartney', value: 1942, difficulty: 'easy'},
  {name: 'Joe Biden', value: 1942, difficulty: 'easy'},
  {name: 'Mick Jagger', value: 1943, difficulty: 'easy'},
  {name: 'Freddie Mercury', value: 1946, difficulty: 'easy'},
  {name: 'Donald Trump', value: 1946, difficulty: 'easy'},
  {name: 'Steven Spielberg', value: 1946, difficulty: 'easy'},
  {name: 'Bill Clinton', value: 1946, difficulty: 'easy'},
  {name: 'David Bowie', value: 1947, difficulty: 'easy'},
  {name: 'Arnold Schwarzenegger', value: 1947, difficulty: 'easy'},
  {name: 'Narendra Modi', value: 1950, difficulty: 'easy'},
  {name: 'Vladimir Putin', value: 1952, difficulty: 'easy'},
  {name: 'Xi Jinping', value: 1953, difficulty: 'easy'},
  {name: 'Oprah Winfrey', value: 1954, difficulty: 'medium'},
  {name: 'Angela Merkel', value: 1954, difficulty: 'easy'},
  {name: 'Bill Gates', value: 1955, difficulty: 'easy'},
  {name: 'Steve Jobs', value: 1955, difficulty: 'easy'},
  {name: 'Michael Jackson', value: 1958, difficulty: 'easy'},
  {name: 'Madonna', value: 1958, difficulty: 'easy'},
  {name: 'Diego Maradona', value: 1960, difficulty: 'easy'},
  {name: 'Princess Diana', value: 1961, difficulty: 'easy'},
  {name: 'Barack Obama', value: 1961, difficulty: 'easy'},
  {name: 'Michael Jordan', value: 1963, difficulty: 'easy'},
  {name: 'Jeff Bezos', value: 1964, difficulty: 'easy'},
  {name: 'J.K. Rowling', value: 1965, difficulty: 'easy'},
  {name: 'Elon Musk', value: 1971, difficulty: 'easy'},
  {name: 'Tiger Woods', value: 1975, difficulty: 'easy'},
  {name: 'Beyoncé', value: 1981, difficulty: 'medium'},
  {name: 'Roger Federer', value: 1981, difficulty: 'easy'},
  {name: 'Mark Zuckerberg', value: 1984, difficulty: 'easy'},
  {name: 'LeBron James', value: 1984, difficulty: 'medium'},
  {name: 'Cristiano Ronaldo', value: 1985, difficulty: 'easy'},
  {name: 'Lionel Messi', value: 1987, difficulty: 'easy'},
];
