import {type Difficulty} from './difficulty.js';

export interface FamousBirth {
  name: string;
  value: number;
  id: number, difficulty: Difficulty;
}

export const famousBirths: FamousBirth[] = [
  {
    name: 'Gautama Buddha',
    value: -563,
    id: 4000,
    difficulty: 'easy',
  },
  {
    name: 'Confucius',
    value: -551,
    id: 4001,
    difficulty: 'medium',
  },
  {
    name: 'Socrates',
    value: -470,
    id: 4002,
    difficulty: 'easy',
  },  // c. 470 BC
  {
    name: 'Plato',
    value: -428,
    id: 4003,
    difficulty: 'medium',
  },  // c. 428 BC
  {
    name: 'Aristotle',
    value: -384,
    id: 4004,
    difficulty: 'easy',
  },
  {
    name: 'Alexander the Great',
    value: -356,
    id: 4005,
    difficulty: 'medium',
  },
  {
    name: 'Archimedes',
    value: -287,
    id: 4006,
    difficulty: 'hard',
  },  // c. 287 BC
  {
    name: 'Qin Shi Huang',
    value: -259,
    id: 4007,
    difficulty: 'hard',
  },
  {
    name: 'Hannibal',
    value: -247,
    id: 4008,
    difficulty: 'hard',
  },
  {
    name: 'Cicero',
    value: -106,
    id: 4009,
    difficulty: 'hard',
  },
  {
    name: 'Julius Caesar',
    value: -100,
    id: 4010,
    difficulty: 'easy',
  },
  {
    name: 'Virgil',
    value: -70,
    id: 4011,
    difficulty: 'hard',
  },
  {
    name: 'Cleopatra',
    value: -69,
    id: 4012,
    difficulty: 'medium',
  },
  {
    name: 'Augustus',
    value: -63,
    id: 4013,
    difficulty: 'medium',
  },
  {
    name: 'Jesus of Nazareth',
    value: -4,
    id: 4014,
    difficulty: 'easy',
  },  // c. 4 BC
  {
    name: 'Nero',
    value: 37,
    id: 4015,
    difficulty: 'medium',
  },
  {
    name: 'Marcus Aurelius',
    value: 121,
    id: 4016,
    difficulty: 'easy',
  },
  {
    name: 'Constantine the Great',
    value: 272,
    id: 4017,
    difficulty: 'hard',
  },
  {
    name: 'Muhammad',
    value: 570,
    id: 4018,
    difficulty: 'easy',
  },  // c. 570
  {
    name: 'Charlemagne',
    value: 748,
    id: 4019,
    difficulty: 'hard',
  },
  {
    name: 'William the Conqueror',
    value: 1028,
    id: 4020,
    difficulty: 'hard',
  },  // c. 1028
  {
    name: 'Saladin',
    value: 1137,
    id: 4021,
    difficulty: 'hard',
  },
  {
    name: 'Genghis Khan',
    value: 1162,
    id: 4022,
    difficulty: 'easy',
  },  // c. 1162
  {
    name: 'Thomas Aquinas',
    value: 1225,
    id: 4023,
    difficulty: 'medium',
  },
  {
    name: 'Marco Polo',
    value: 1254,
    id: 4024,
    difficulty: 'medium',
  },
  {
    name: 'Dante Alighieri',
    value: 1265,
    id: 4025,
    difficulty: 'easy',
  },  // c. 1265
  {
    name: 'Geoffrey Chaucer',
    value: 1343,
    id: 4026,
    difficulty: 'hard',
  },  // c. 1343
  {
    name: 'Johannes Gutenberg',
    value: 1400,
    id: 4027,
    difficulty: 'easy',
  },  // c. 1400
  {
    name: 'Joan of Arc',
    value: 1412,
    id: 4028,
    difficulty: 'medium',
  },  // c. 1412
  {
    name: 'Christopher Columbus',
    value: 1451,
    id: 4029,
    difficulty: 'easy',
  },
  {
    name: 'Leonardo da Vinci',
    value: 1452,
    id: 4030,
    difficulty: 'easy',
  },
  {
    name: 'Niccolò Machiavelli',
    value: 1469,
    id: 4031,
    difficulty: 'medium',
  },
  {
    name: 'Nicolaus Copernicus',
    value: 1473,
    id: 4032,
    difficulty: 'easy',
  },
  {
    name: 'Michelangelo',
    value: 1475,
    id: 4033,
    difficulty: 'easy',
  },
  {
    name: 'Francisco Pizarro',
    value: 1478,
    id: 4034,
    difficulty: 'hard',
  },
  {
    name: 'Ferdinand Magellan',
    value: 1480,
    id: 4035,
    difficulty: 'hard',
  },
  {
    name: 'Hernán Cortés',
    value: 1485,
    id: 4036,
    difficulty: 'hard',
  },
  {
    name: 'Martin Luther',
    value: 1483,
    id: 4037,
    difficulty: 'medium',
  },
  {
    name: 'Henry VIII',
    value: 1491,
    id: 4038,
    difficulty: 'hard',
  },
  {
    name: 'Suleiman the Magnificent',
    value: 1494,
    id: 4039,
    difficulty: 'hard',
  },
  {
    name: 'Ivan the Terrible',
    value: 1530,
    id: 4040,
    difficulty: 'hard',
  },
  {
    name: 'Elizabeth I',
    value: 1533,
    id: 4041,
    difficulty: 'hard',
  },
  {
    name: 'Akbar the Great',
    value: 1542,
    id: 4042,
    difficulty: 'hard',
  },
  {
    name: 'Miguel de Cervantes',
    value: 1547,
    id: 4043,
    difficulty: 'easy',
  },
  {
    name: 'William Shakespeare',
    value: 1564,
    id: 4044,
    difficulty: 'easy',
  },
  {
    name: 'Galileo Galilei',
    value: 1564,
    id: 4045,
    difficulty: 'medium',
  },
  {
    name: 'Johannes Kepler',
    value: 1571,
    id: 4046,
    difficulty: 'hard',
  },
  {
    name: 'René Descartes',
    value: 1596,
    id: 4047,
    difficulty: 'medium',
  },
  {
    name: 'Rembrandt',
    value: 1606,
    id: 4048,
    difficulty: 'medium',
  },
  {
    name: 'John Locke',
    value: 1632,
    id: 4049,
    difficulty: 'medium',
  },
  {
    name: 'Louis XIV',
    value: 1638,
    id: 4050,
    difficulty: 'hard',
  },
  {
    name: 'Isaac Newton',
    value: 1642,
    id: 4051,
    difficulty: 'easy',
  },
  {
    name: 'Peter the Great',
    value: 1672,
    id: 4052,
    difficulty: 'hard',
  },
  {
    name: 'Antonio Vivaldi',
    value: 1678,
    id: 4053,
    difficulty: 'medium',
  },
  {
    name: 'Johann Sebastian Bach',
    value: 1685,
    id: 4054,
    difficulty: 'easy',
  },
  {
    name: 'George Frideric Handel',
    value: 1685,
    id: 4055,
    difficulty: 'hard',
  },
  {
    name: 'Voltaire',
    value: 1694,
    id: 4056,
    difficulty: 'medium',
  },
  {
    name: 'Benjamin Franklin',
    value: 1706,
    id: 4057,
    difficulty: 'medium',
  },
  {
    name: 'Jean-Jacques Rousseau',
    value: 1712,
    id: 4058,
    difficulty: 'hard',
  },
  {
    name: 'Adam Smith',
    value: 1723,
    id: 4059,
    difficulty: 'medium',
  },
  {
    name: 'Immanuel Kant',
    value: 1724,
    id: 4060,
    difficulty: 'medium',
  },
  {
    name: 'Catherine the Great',
    value: 1729,
    id: 4061,
    difficulty: 'hard',
  },
  {
    name: 'George Washington',
    value: 1732,
    id: 4062,
    difficulty: 'easy',
  },
  {
    name: 'Thomas Jefferson',
    value: 1743,
    id: 4063,
    difficulty: 'medium',
  },
  {
    name: 'Johann Wolfgang von Goethe',
    value: 1749,
    id: 4064,
    difficulty: 'easy',
  },
  {
    name: 'Marie Antoinette',
    value: 1755,
    id: 4065,
    difficulty: 'hard',
  },
  {
    name: 'Wolfgang Amadeus Mozart',
    value: 1756,
    id: 4066,
    difficulty: 'easy',
  },
  {
    name: 'Napoleon Bonaparte',
    value: 1769,
    id: 4067,
    difficulty: 'easy',
  },
  {
    name: 'Ludwig van Beethoven',
    value: 1770,
    id: 4068,
    difficulty: 'easy',
  },
  {
    name: 'Jane Austen',
    value: 1775,
    id: 4069,
    difficulty: 'hard',
  },
  {
    name: 'Simón Bolívar',
    value: 1783,
    id: 4070,
    difficulty: 'medium',
  },
  {
    name: 'Michael Faraday',
    value: 1791,
    id: 4071,
    difficulty: 'medium',
  },
  {
    name: 'Victor Hugo',
    value: 1802,
    id: 4072,
    difficulty: 'medium',
  },
  {
    name: 'Hans Christian Andersen',
    value: 1805,
    id: 4073,
    difficulty: 'medium',
  },
  {
    name: 'Abraham Lincoln',
    value: 1809,
    id: 4074,
    difficulty: 'easy',
  },
  {
    name: 'Charles Darwin',
    value: 1809,
    id: 4075,
    difficulty: 'easy',
  },
  {
    name: 'Edgar Allan Poe',
    value: 1809,
    id: 4076,
    difficulty: 'easy',
  },
  {
    name: 'Frédéric Chopin',
    value: 1810,
    id: 4077,
    difficulty: 'easy',
  },
  {
    name: 'Charles Dickens',
    value: 1812,
    id: 4078,
    difficulty: 'medium',
  },
  {
    name: 'Richard Wagner',
    value: 1813,
    id: 4079,
    difficulty: 'medium',
  },
  {
    name: 'Otto von Bismarck',
    value: 1815,
    id: 4080,
    difficulty: 'hard',
  },
  {
    name: 'Ada Lovelace',
    value: 1815,
    id: 4081,
    difficulty: 'medium',
  },
  {
    name: 'Karl Marx',
    value: 1818,
    id: 4082,
    difficulty: 'medium',
  },
  {
    name: 'Frederick Douglass',
    value: 1818,
    id: 4083,
    difficulty: 'hard',
  },  // c. 1818
  {
    name: 'Queen Victoria',
    value: 1819,
    id: 4084,
    difficulty: 'medium',
  },
  {
    name: 'Florence Nightingale',
    value: 1820,
    id: 4085,
    difficulty: 'hard',
  },
  {
    name: 'Fyodor Dostoevsky',
    value: 1821,
    id: 4086,
    difficulty: 'easy',
  },
  {
    name: 'Louis Pasteur',
    value: 1822,
    id: 4087,
    difficulty: 'medium',
  },
  {
    name: 'Harriet Tubman',
    value: 1822,
    id: 4088,
    difficulty: 'hard',
  },  // c. 1822
  {
    name: 'Leo Tolstoy',
    value: 1828,
    id: 4089,
    difficulty: 'easy',
  },
  {
    name: 'Mark Twain',
    value: 1835,
    id: 4090,
    difficulty: 'medium',
  },
  {
    name: 'John D. Rockefeller',
    value: 1839,
    id: 4091,
    difficulty: 'medium',
  },
  {
    name: 'Claude Monet',
    value: 1840,
    id: 4092,
    difficulty: 'easy',
  },
  {
    name: 'Pyotr Tchaikovsky',
    value: 1840,
    id: 4093,
    difficulty: 'easy',
  },
  {
    name: 'Friedrich Nietzsche',
    value: 1844,
    id: 4094,
    difficulty: 'easy',
  },
  {
    name: 'Thomas Edison',
    value: 1847,
    id: 4095,
    difficulty: 'easy',
  },
  {
    name: 'Alexander Graham Bell',
    value: 1847,
    id: 4096,
    difficulty: 'easy',
  },
  {
    name: 'Vincent van Gogh',
    value: 1853,
    id: 4097,
    difficulty: 'easy',
  },
  {
    name: 'Sigmund Freud',
    value: 1856,
    id: 4098,
    difficulty: 'easy',
  },
  {
    name: 'Nikola Tesla',
    value: 1856,
    id: 4099,
    difficulty: 'easy',
  },
  {
    name: 'Max Planck',
    value: 1858,
    id: 4100,
    difficulty: 'medium',
  },
  {
    name: 'Arthur Conan Doyle',
    value: 1859,
    id: 4101,
    difficulty: 'easy',
  },
  {
    name: 'Henry Ford',
    value: 1863,
    id: 4102,
    difficulty: 'easy',
  },
  {
    name: 'Marie Curie',
    value: 1867,
    id: 4103,
    difficulty: 'medium',
  },
  {
    name: 'Wilbur Wright (Wright brothers)',
    value: 1867,
    id: 4104,
    difficulty: 'easy',
  },
  {
    name: 'Mahatma Gandhi',
    value: 1869,
    id: 4105,
    difficulty: 'easy',
  },
  {
    name: 'Vladimir Lenin',
    value: 1870,
    id: 4106,
    difficulty: 'easy',
  },
  {
    name: 'Orville Wright (Wright brothers)',
    value: 1871,
    id: 4107,
    difficulty: 'easy',
  },
  {
    name: 'Winston Churchill',
    value: 1874,
    id: 4108,
    difficulty: 'easy',
  },
  {
    name: 'Guglielmo Marconi',
    value: 1874,
    id: 4109,
    difficulty: 'medium',
  },
  {
    name: 'Joseph Stalin',
    value: 1878,
    id: 4110,
    difficulty: 'easy',
  },
  {
    name: 'Albert Einstein',
    value: 1879,
    id: 4111,
    difficulty: 'easy',
  },
  {
    name: 'Pablo Picasso',
    value: 1881,
    id: 4112,
    difficulty: 'easy',
  },
  {
    name: 'Mustafa Kemal Atatürk',
    value: 1881,
    id: 4113,
    difficulty: 'medium',
  },
  {
    name: 'James Joyce',
    value: 1882,
    id: 4114,
    difficulty: 'medium',
  },
  {
    name: 'Virginia Woolf',
    value: 1882,
    id: 4115,
    difficulty: 'medium',
  },
  {
    name: 'Franklin D. Roosevelt',
    value: 1882,
    id: 4116,
    difficulty: 'medium',
  },
  {
    name: 'Franz Kafka',
    value: 1883,
    id: 4117,
    difficulty: 'easy',
  },
  {
    name: 'Coco Chanel',
    value: 1883,
    id: 4118,
    difficulty: 'medium',
  },
  {
    name: 'Benito Mussolini',
    value: 1883,
    id: 4119,
    difficulty: 'easy',
  },
  {
    name: 'Niels Bohr',
    value: 1885,
    id: 4120,
    difficulty: 'medium',
  },
  {
    name: 'Adolf Hitler',
    value: 1889,
    id: 4121,
    difficulty: 'easy',
  },
  {
    name: 'Charlie Chaplin',
    value: 1889,
    id: 4122,
    difficulty: 'easy',
  },
  {
    name: 'Charles de Gaulle',
    value: 1890,
    id: 4123,
    difficulty: 'medium',
  },
  {
    name: 'Agatha Christie',
    value: 1890,
    id: 4124,
    difficulty: 'medium',
  },
  {
    name: 'J.R.R. Tolkien',
    value: 1892,
    id: 4125,
    difficulty: 'easy',
  },
  {
    name: 'Mao Zedong',
    value: 1893,
    id: 4126,
    difficulty: 'easy',
  },
  {
    name: 'Amelia Earhart',
    value: 1897,
    id: 4127,
    difficulty: 'medium',
  },
  {
    name: 'Ernest Hemingway',
    value: 1899,
    id: 4128,
    difficulty: 'easy',
  },
  {
    name: 'Alfred Hitchcock',
    value: 1899,
    id: 4129,
    difficulty: 'easy',
  },
  {
    name: 'Louis Armstrong',
    value: 1901,
    id: 4130,
    difficulty: 'medium',
  },
  {
    name: 'Walt Disney',
    value: 1901,
    id: 4131,
    difficulty: 'easy',
  },
  {
    name: 'George Orwell',
    value: 1903,
    id: 4132,
    difficulty: 'medium',
  },
  {
    name: 'Salvador Dalí',
    value: 1904,
    id: 4133,
    difficulty: 'easy',
  },
  {
    name: 'J. Robert Oppenheimer',
    value: 1904,
    id: 4134,
    difficulty: 'easy',
  },
  {
    name: 'Frida Kahlo',
    value: 1907,
    id: 4135,
    difficulty: 'easy',
  },
  {
    name: 'Mother Teresa',
    value: 1910,
    id: 4136,
    difficulty: 'medium',
  },
  {
    name: 'Ronald Reagan',
    value: 1911,
    id: 4137,
    difficulty: 'easy',
  },
  {
    name: 'Alan Turing',
    value: 1912,
    id: 4138,
    difficulty: 'easy',
  },
  {
    name: 'Rosa Parks',
    value: 1913,
    id: 4139,
    difficulty: 'easy',
  },
  {
    name: 'Richard Nixon',
    value: 1913,
    id: 4140,
    difficulty: 'medium',
  },
  {
    name: 'Frank Sinatra',
    value: 1915,
    id: 4141,
    difficulty: 'easy',
  },
  {
    name: 'John F. Kennedy',
    value: 1917,
    id: 4142,
    difficulty: 'easy',
  },
  {
    name: 'Nelson Mandela',
    value: 1918,
    id: 4143,
    difficulty: 'easy',
  },
  {
    name: 'Richard Feynman',
    value: 1918,
    id: 4144,
    difficulty: 'easy',
  },
  {
    name: 'Pope John Paul II',
    value: 1920,
    id: 4145,
    difficulty: 'easy',
  },
  {
    name: 'Marlon Brando',
    value: 1924,
    id: 4146,
    difficulty: 'easy',
  },
  {
    name: 'Margaret Thatcher',
    value: 1925,
    id: 4147,
    difficulty: 'easy',
  },
  {
    name: 'Malcolm X',
    value: 1925,
    id: 4148,
    difficulty: 'medium',
  },
  {
    name: 'Queen Elizabeth II',
    value: 1926,
    id: 4149,
    difficulty: 'medium',
  },
  {
    name: 'Marilyn Monroe',
    value: 1926,
    id: 4150,
    difficulty: 'easy',
  },
  {
    name: 'Fidel Castro',
    value: 1926,
    id: 4151,
    difficulty: 'easy',
  },
  {
    name: 'Gabriel García Márquez',
    value: 1927,
    id: 4152,
    difficulty: 'easy',
  },
  {
    name: 'Che Guevara',
    value: 1928,
    id: 4153,
    difficulty: 'easy',
  },
  {
    name: 'Andy Warhol',
    value: 1928,
    id: 4154,
    difficulty: 'easy',
  },
  {
    name: 'Stanley Kubrick',
    value: 1928,
    id: 4155,
    difficulty: 'easy',
  },
  {
    name: 'Anne Frank',
    value: 1929,
    id: 4156,
    difficulty: 'easy',
  },
  {
    name: 'Martin Luther King Jr.',
    value: 1929,
    id: 4157,
    difficulty: 'easy',
  },
  {
    name: 'Audrey Hepburn',
    value: 1929,
    id: 4158,
    difficulty: 'easy',
  },
  {
    name: 'Neil Armstrong',
    value: 1930,
    id: 4159,
    difficulty: 'easy',
  },
  {
    name: 'Warren Buffett',
    value: 1930,
    id: 4160,
    difficulty: 'easy',
  },
  {
    name: 'Clint Eastwood',
    value: 1930,
    id: 4161,
    difficulty: 'easy',
  },
  {
    name: 'Mikhail Gorbachev',
    value: 1931,
    id: 4162,
    difficulty: 'easy',
  },
  {
    name: 'Yuri Gagarin',
    value: 1934,
    id: 4163,
    difficulty: 'medium',
  },
  {
    name: 'Elvis Presley',
    value: 1935,
    id: 4164,
    difficulty: 'easy',
  },
  {
    name: 'The 14th Dalai Lama',
    value: 1935,
    id: 4165,
    difficulty: 'medium',
  },
  {
    name: 'Pope Francis',
    value: 1936,
    id: 4166,
    difficulty: 'easy',
  },
  {
    name: 'Bruce Lee',
    value: 1940,
    id: 4167,
    difficulty: 'easy',
  },
  {
    name: 'John Lennon',
    value: 1940,
    id: 4168,
    difficulty: 'easy',
  },
  {
    name: 'Pelé',
    value: 1940,
    id: 4169,
    difficulty: 'easy',
  },
  {
    name: 'Bob Dylan',
    value: 1941,
    id: 4170,
    difficulty: 'easy',
  },
  {
    name: 'Muhammad Ali',
    value: 1942,
    id: 4171,
    difficulty: 'easy',
  },
  {
    name: 'Stephen Hawking',
    value: 1942,
    id: 4172,
    difficulty: 'medium',
  },
  {
    name: 'Paul McCartney',
    value: 1942,
    id: 4173,
    difficulty: 'easy',
  },
  {
    name: 'Joe Biden',
    value: 1942,
    id: 4174,
    difficulty: 'easy',
  },
  {
    name: 'Mick Jagger',
    value: 1943,
    id: 4175,
    difficulty: 'easy',
  },
  {
    name: 'Freddie Mercury',
    value: 1946,
    id: 4176,
    difficulty: 'easy',
  },
  {
    name: 'Donald Trump',
    value: 1946,
    id: 4177,
    difficulty: 'easy',
  },
  {
    name: 'Steven Spielberg',
    value: 1946,
    id: 4178,
    difficulty: 'easy',
  },
  {
    name: 'Bill Clinton',
    value: 1946,
    id: 4179,
    difficulty: 'easy',
  },
  {
    name: 'David Bowie',
    value: 1947,
    id: 4180,
    difficulty: 'easy',
  },
  {
    name: 'Arnold Schwarzenegger',
    value: 1947,
    id: 4181,
    difficulty: 'easy',
  },
  {
    name: 'Narendra Modi',
    value: 1950,
    id: 4182,
    difficulty: 'easy',
  },
  {
    name: 'Vladimir Putin',
    value: 1952,
    id: 4183,
    difficulty: 'easy',
  },
  {
    name: 'Xi Jinping',
    value: 1953,
    id: 4184,
    difficulty: 'easy',
  },
  {
    name: 'Oprah Winfrey',
    value: 1954,
    id: 4185,
    difficulty: 'medium',
  },
  {
    name: 'Angela Merkel',
    value: 1954,
    id: 4186,
    difficulty: 'easy',
  },
  {
    name: 'Bill Gates',
    value: 1955,
    id: 4187,
    difficulty: 'easy',
  },
  {
    name: 'Steve Jobs',
    value: 1955,
    id: 4188,
    difficulty: 'easy',
  },
  {
    name: 'Michael Jackson',
    value: 1958,
    id: 4189,
    difficulty: 'easy',
  },
  {
    name: 'Madonna',
    value: 1958,
    id: 4190,
    difficulty: 'easy',
  },
  {
    name: 'Diego Maradona',
    value: 1960,
    id: 4191,
    difficulty: 'easy',
  },
  {
    name: 'Princess Diana',
    value: 1961,
    id: 4192,
    difficulty: 'easy',
  },
  {
    name: 'Barack Obama',
    value: 1961,
    id: 4193,
    difficulty: 'easy',
  },
  {
    name: 'Michael Jordan',
    value: 1963,
    id: 4194,
    difficulty: 'easy',
  },
  {
    name: 'Jeff Bezos',
    value: 1964,
    id: 4195,
    difficulty: 'easy',
  },
  {
    name: 'J.K. Rowling',
    value: 1965,
    id: 4196,
    difficulty: 'easy',
  },
  {
    name: 'Elon Musk',
    value: 1971,
    id: 4197,
    difficulty: 'easy',
  },
  {
    name: 'Tiger Woods',
    value: 1975,
    id: 4198,
    difficulty: 'easy',
  },
  {
    name: 'Beyoncé',
    value: 1981,
    id: 4199,
    difficulty: 'medium',
  },
  {
    name: 'Roger Federer',
    value: 1981,
    id: 4200,
    difficulty: 'easy',
  },
  {
    name: 'Mark Zuckerberg',
    value: 1984,
    id: 4201,
    difficulty: 'easy',
  },
  {
    name: 'LeBron James',
    value: 1984,
    id: 4202,
    difficulty: 'medium',
  },
  {
    name: 'Cristiano Ronaldo',
    value: 1985,
    id: 4203,
    difficulty: 'easy',
  },
  {
    name: 'Lionel Messi',
    value: 1987,
    id: 4204,
    difficulty: 'easy',
  },
];
