import {type Difficulty} from './difficulty.js';

export interface Film {
  title: string;
  director: string;
  year: number;  // Year of original theatrical release
  id: number;
  difficulty: Difficulty;
  link: string;
}

export const films: Film[] = [
  {
    title: 'A Trip to the Moon',
    director: 'Georges Méliès',
    year: 1902,
    id: 7000,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/A_Trip_to_the_Moon',
  },
  {
    title: 'The Birth of a Nation',
    director: 'D. W. Griffith',
    year: 1915,
    id: 7001,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Birth_of_a_Nation',
  },
  {
    title: 'The Cabinet of Dr. Caligari',
    director: 'Robert Wiene',
    year: 1920,
    id: 7002,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Cabinet_of_Dr._Caligari',
  },
  {
    title: 'Nosferatu',
    director: 'F. W. Murnau',
    year: 1922,
    id: 7003,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Nosferatu',
  },
  {
    title: 'Battleship Potemkin',
    director: 'Sergei Eisenstein',
    year: 1925,
    id: 7004,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Battleship_Potemkin',
  },
  {
    title: 'The Gold Rush',
    director: 'Charlie Chaplin',
    year: 1925,
    id: 7005,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Gold_Rush',
  },
  {
    title: 'Metropolis',
    director: 'Fritz Lang',
    year: 1927,
    id: 7006,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Metropolis_(1927_film)',
  },
  {
    title: 'The Jazz Singer',
    director: 'Alan Crosland',
    year: 1927,
    id: 7007,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Jazz_Singer',
  },
  {
    title: 'Un Chien Andalou',
    director: 'Luis Buñuel',
    year: 1929,
    id: 7008,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Un_Chien_Andalou',
  },
  {
    title: 'M',
    director: 'Fritz Lang',
    year: 1931,
    id: 7009,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/M_(1931_film)',
  },
  {
    title: 'City Lights',
    director: 'Charlie Chaplin',
    year: 1931,
    id: 7010,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/City_Lights',
  },
  {
    title: 'King Kong',
    director: 'Merian C. Cooper and Ernest B. Schoedsack',
    year: 1933,
    id: 7011,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/King_Kong_(1933_film)',
  },
  {
    title: 'Modern Times',
    director: 'Charlie Chaplin',
    year: 1936,
    id: 7012,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Modern_Times_(film)',
  },
  {
    title: 'Snow White and the Seven Dwarfs',
    director: 'David Hand',
    year: 1937,
    id: 7013,
    difficulty: 'medium',
    link:
        'https://en.wikipedia.org/wiki/Snow_White_and_the_Seven_Dwarfs_(1937_film)',
  },
  {
    title: 'The Wizard of Oz',
    director: 'Victor Fleming',
    year: 1939,
    id: 7014,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Wizard_of_Oz_(1939_film)',
  },
  {
    title: 'Gone with the Wind',
    director: 'Victor Fleming',
    year: 1939,
    id: 7015,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Gone_with_the_Wind_(film)',
  },
  {
    title: 'The Great Dictator',
    director: 'Charlie Chaplin',
    year: 1940,
    id: 7016,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Great_Dictator',
  },
  {
    title: 'Citizen Kane',
    director: 'Orson Welles',
    year: 1941,
    id: 7017,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Citizen_Kane',
  },
  {
    title: 'Casablanca',
    director: 'Michael Curtiz',
    year: 1942,
    id: 7018,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Casablanca_(film)',
  },
  {
    title: 'It\'s a Wonderful Life',
    director: 'Frank Capra',
    year: 1946,
    id: 7019,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/It%27s_a_Wonderful_Life',
  },
  {
    title: 'Bicycle Thieves',
    director: 'Vittorio De Sica',
    year: 1948,
    id: 7020,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Bicycle_Thieves',
  },
  {
    title: 'The Third Man',
    director: 'Carol Reed',
    year: 1949,
    id: 7021,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Third_Man',
  },
  {
    title: 'Rashomon',
    director: 'Akira Kurosawa',
    year: 1950,
    id: 7022,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Rashomon',
  },
  {
    title: 'Sunset Boulevard',
    director: 'Billy Wilder',
    year: 1950,
    id: 7023,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Sunset_Boulevard_(film)',
  },
  {
    title: 'Singin\' in the Rain',
    director: 'Stanley Donen and Gene Kelly',
    year: 1952,
    id: 7024,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Singin%27_in_the_Rain',
  },
  {
    title: 'Tokyo Story',
    director: 'Yasujirō Ozu',
    year: 1953,
    id: 7025,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Tokyo_Story',
  },
  {
    title: 'Seven Samurai',
    director: 'Akira Kurosawa',
    year: 1954,
    id: 7026,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Seven_Samurai',
  },
  {
    title: 'Rear Window',
    director: 'Alfred Hitchcock',
    year: 1954,
    id: 7027,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Rear_Window',
  },
  {
    title: 'The Seventh Seal',
    director: 'Ingmar Bergman',
    year: 1957,
    id: 7028,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Seventh_Seal',
  },
  {
    title: '12 Angry Men',
    director: 'Sidney Lumet',
    year: 1957,
    id: 7029,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/12_Angry_Men_(1957_film)',
  },
  {
    title: 'Vertigo',
    director: 'Alfred Hitchcock',
    year: 1958,
    id: 7030,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Vertigo_(film)',
  },
  {
    title: 'Some Like It Hot',
    director: 'Billy Wilder',
    year: 1959,
    id: 7031,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Some_Like_It_Hot',
  },
  {
    title: 'The 400 Blows',
    director: 'François Truffaut',
    year: 1959,
    id: 7032,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_400_Blows',
  },
  {
    title: 'Breathless',
    director: 'Jean-Luc Godard',
    year: 1960,
    id: 7033,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Breathless_(1960_film)',
  },
  {
    title: 'Psycho',
    director: 'Alfred Hitchcock',
    year: 1960,
    id: 7034,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Psycho_(1960_film)',
  },
  {
    title: 'La Dolce Vita',
    director: 'Federico Fellini',
    year: 1960,
    id: 7035,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/La_Dolce_Vita',
  },
  {
    title: 'Lawrence of Arabia',
    director: 'David Lean',
    year: 1962,
    id: 7036,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Lawrence_of_Arabia_(film)',
  },
  {
    title: '8½',
    director: 'Federico Fellini',
    year: 1963,
    id: 7037,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/8%C2%BD',
  },
  {
    title: 'Dr. Strangelove',
    director: 'Stanley Kubrick',
    year: 1964,
    id: 7038,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Dr._Strangelove',
  },
  {
    title: 'The Sound of Music',
    director: 'Robert Wise',
    year: 1965,
    id: 7039,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Sound_of_Music_(film)',
  },
  {
    title: 'The Good, the Bad and the Ugly',
    director: 'Sergio Leone',
    year: 1966,
    id: 7040,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Good,_the_Bad_and_the_Ugly',
  },
  {
    title: 'The Graduate',
    director: 'Mike Nichols',
    year: 1967,
    id: 7041,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Graduate',
  },
  {
    title: '2001: A Space Odyssey',
    director: 'Stanley Kubrick',
    year: 1968,
    id: 7042,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/2001:_A_Space_Odyssey_(film)',
  },
  {
    title: 'Easy Rider',
    director: 'Dennis Hopper',
    year: 1969,
    id: 7043,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Easy_Rider',
  },
  {
    title: 'A Clockwork Orange',
    director: 'Stanley Kubrick',
    year: 1971,
    id: 7044,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/A_Clockwork_Orange_(film)',
  },
  {
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    year: 1972,
    id: 7045,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Godfather',
  },
  {
    title: 'The Exorcist',
    director: 'William Friedkin',
    year: 1973,
    id: 7046,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Exorcist_(film)',
  },
  {
    title: 'Chinatown',
    director: 'Roman Polanski',
    year: 1974,
    id: 7047,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Chinatown_(1974_film)',
  },
  {
    title: 'Jaws',
    director: 'Steven Spielberg',
    year: 1975,
    id: 7048,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Jaws_(film)',
  },
  {
    title: 'One Flew Over the Cuckoo\'s Nest',
    director: 'Miloš Forman',
    year: 1975,
    id: 7049,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/One_Flew_Over_the_Cuckoo%27s_Nest_(film)',
  },
  {
    title: 'Taxi Driver',
    director: 'Martin Scorsese',
    year: 1976,
    id: 7050,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Taxi_Driver',
  },
  {
    title: 'Rocky',
    director: 'John G. Avildsen',
    year: 1976,
    id: 7051,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Rocky',
  },
  {
    title: 'Star Wars',
    director: 'George Lucas',
    year: 1977,
    id: 7052,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Star_Wars_(film)',
  },
  {
    title: 'Annie Hall',
    director: 'Woody Allen',
    year: 1977,
    id: 7053,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Annie_Hall',
  },
  {
    title: 'Alien',
    director: 'Ridley Scott',
    year: 1979,
    id: 7054,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Alien_(film)',
  },
  {
    title: 'Apocalypse Now',
    director: 'Francis Ford Coppola',
    year: 1979,
    id: 7055,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Apocalypse_Now',
  },
  {
    title: 'The Shining',
    director: 'Stanley Kubrick',
    year: 1980,
    id: 7056,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Shining_(film)',
  },
  {
    title: 'Raiders of the Lost Ark',
    director: 'Steven Spielberg',
    year: 1981,
    id: 7057,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Raiders_of_the_Lost_Ark',
  },
  {
    title: 'Blade Runner (original)',
    director: 'Ridley Scott',
    year: 1982,
    id: 7058,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Blade_Runner',
  },
  {
    title: 'E.T. the Extra-Terrestrial',
    director: 'Steven Spielberg',
    year: 1982,
    id: 7059,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/E.T._the_Extra-Terrestrial',
  },
  {
    title: 'Scarface',
    director: 'Brian De Palma',
    year: 1983,
    id: 7060,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Scarface_(1983_film)',
  },
  {
    title: 'The Terminator',
    director: 'James Cameron',
    year: 1984,
    id: 7061,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Terminator',
  },
  {
    title: 'Back to the Future',
    director: 'Robert Zemeckis',
    year: 1985,
    id: 7062,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Back_to_the_Future',
  },
  {
    title: 'My Neighbor Totoro',
    director: 'Hayao Miyazaki',
    year: 1988,
    id: 7063,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/My_Neighbor_Totoro',
  },
  {
    title: 'Cinema Paradiso',
    director: 'Giuseppe Tornatore',
    year: 1988,
    id: 7064,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Cinema_Paradiso',
  },
  {
    title: 'Die Hard',
    director: 'John McTiernan',
    year: 1988,
    id: 7065,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Die_Hard',
  },
  {
    title: 'Goodfellas',
    director: 'Martin Scorsese',
    year: 1990,
    id: 7066,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Goodfellas',
  },
  {
    title: 'The Silence of the Lambs',
    director: 'Jonathan Demme',
    year: 1991,
    id: 7067,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Silence_of_the_Lambs_(film)',
  },
  {
    title: 'Terminator 2: Judgment Day',
    director: 'James Cameron',
    year: 1991,
    id: 7068,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Terminator_2:_Judgment_Day',
  },
  {
    title: 'Jurassic Park',
    director: 'Steven Spielberg',
    year: 1993,
    id: 7069,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Jurassic_Park_(film)',
  },
  {
    title: 'Schindler\'s List',
    director: 'Steven Spielberg',
    year: 1993,
    id: 7070,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Schindler%27s_List',
  },
  {
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    year: 1994,
    id: 7071,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pulp_Fiction',
  },
  {
    title: 'The Shawshank Redemption',
    director: 'Frank Darabont',
    year: 1994,
    id: 7072,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Shawshank_Redemption',
  },
  {
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    year: 1994,
    id: 7073,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Forrest_Gump',
  },
  {
    title: 'The Lion King',
    director: 'Roger Allers and Rob Minkoff',
    year: 1994,
    id: 7074,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Lion_King',
  },
  {
    title: 'Toy Story',
    director: 'John Lasseter',
    year: 1995,
    id: 7075,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Toy_Story',
  },
  {
    title: 'Se7en',
    director: 'David Fincher',
    year: 1995,
    id: 7076,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Seven_(1995_film)',
  },
  {
    title: 'Fargo',
    director: 'Joel and Ethan Coen',
    year: 1996,
    id: 7077,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Fargo_(1996_film)',
  },
  {
    title: 'Titanic',
    director: 'James Cameron',
    year: 1997,
    id: 7078,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Titanic_(1997_film)',
  },
  {
    title: 'The Big Lebowski',
    director: 'Joel and Ethan Coen',
    year: 1998,
    id: 7079,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Big_Lebowski',
  },
  {
    title: 'The Matrix',
    director: 'The Wachowskis',
    year: 1999,
    id: 7080,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Matrix',
  },
  {
    title: 'Fight Club',
    director: 'David Fincher',
    year: 1999,
    id: 7081,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Fight_Club',
  },
  {
    title: 'The Sixth Sense',
    director: 'M. Night Shyamalan',
    year: 1999,
    id: 7082,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Sixth_Sense',
  },
  {
    title: 'Gladiator',
    director: 'Ridley Scott',
    year: 2000,
    id: 7083,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Gladiator_(2000_film)',
  },
  {
    title: 'Crouching Tiger, Hidden Dragon',
    director: 'Ang Lee',
    year: 2000,
    id: 7084,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Crouching_Tiger,_Hidden_Dragon',
  },
  {
    title: 'Amélie',
    director: 'Jean-Pierre Jeunet',
    year: 2001,
    id: 7085,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Am%C3%A9lie',
  },
  {
    title: 'Spirited Away',
    director: 'Hayao Miyazaki',
    year: 2001,
    id: 7086,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Spirited_Away',
  },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    director: 'Peter Jackson',
    year: 2001,
    id: 7087,
    difficulty: 'easy',
    link:
        'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Fellowship_of_the_Ring',
  },
  {
    title: 'City of God',
    director: 'Fernando Meirelles and Kátia Lund',
    year: 2002,
    id: 7088,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/City_of_God_(2002_film)',
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    director: 'Peter Jackson',
    year: 2003,
    id: 7089,
    difficulty: 'easy',
    link:
        'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Return_of_the_King',
  },
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    director: 'Michel Gondry',
    year: 2004,
    id: 7090,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Eternal_Sunshine_of_the_Spotless_Mind',
  },
  {
    title: 'Pan\'s Labyrinth',
    director: 'Guillermo del Toro',
    year: 2006,
    id: 7091,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Pan%27s_Labyrinth',
  },
  {
    title: 'The Lives of Others',
    director: 'Florian Henckel von Donnersmarck',
    year: 2006,
    id: 7092,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Lives_of_Others',
  },
  {
    title: 'No Country for Old Men',
    director: 'Joel and Ethan Coen',
    year: 2007,
    id: 7093,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/No_Country_for_Old_Men_(film)',
  },
  {
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    year: 2008,
    id: 7094,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Dark_Knight',
  },
  {
    title: 'Slumdog Millionaire',
    director: 'Danny Boyle',
    year: 2008,
    id: 7095,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Slumdog_Millionaire',
  },
  {
    title: 'Avatar',
    director: 'James Cameron',
    year: 2009,
    id: 7096,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Avatar_(2009_film)',
  },
  {
    title: 'Inception',
    director: 'Christopher Nolan',
    year: 2010,
    id: 7097,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Inception',
  },
  {
    title: 'The Intouchables',
    director: 'Olivier Nakache and Éric Toledano',
    year: 2011,
    id: 7098,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Intouchables',
  },
  {
    title: 'Gravity',
    director: 'Alfonso Cuarón',
    year: 2013,
    id: 7099,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Gravity_(2013_film)',
  },
  {
    title: 'Boyhood',
    director: 'Richard Linklater',
    year: 2014,
    id: 7100,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Boyhood_(2014_film)',
  },
  {
    title: 'Mad Max: Fury Road',
    director: 'George Miller',
    year: 2015,
    id: 7101,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mad_Max:_Fury_Road',
  },
  {
    title: 'Get Out',
    director: 'Jordan Peele',
    year: 2017,
    id: 7102,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Get_Out_(film)',
  },
  {
    title: 'Roma',
    director: 'Alfonso Cuarón',
    year: 2018,
    id: 7103,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Roma_(2018_film)',
  },
  {
    title: 'Parasite',
    director: 'Bong Joon-ho',
    year: 2019,
    id: 7104,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Parasite_(2019_film)',
  },
  {
    title: 'Everything Everywhere All at Once',
    director: 'Daniel Kwan and Daniel Scheinert',
    year: 2022,
    id: 7105,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Everything_Everywhere_All_at_Once',
  },
  {
    title: 'Oppenheimer',
    director: 'Christopher Nolan',
    year: 2023,
    id: 7106,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Oppenheimer_(film)',
  },
  {
    title: 'The Oddisey',
    director: 'Christopher Nolan',
    year: 2026,
    id: 7107,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Odyssey_(2026_film)',
  },
];
