import {type Difficulty} from './difficulty.js';
import {UnitEntry} from './question.js';

export interface HistoricalEvent {
  name: string;
  shortName: string;
  value: number;
  topic: string[];
  difficulty: Difficulty;
  id: number;
}

export const historicalEvents: HistoricalEvent[] = [
  {
    name: 'Hammurabi wrote his code of laws',
    shortName: 'Hammurabi',
    value: -1754,
    topic: ['Hammurabi'],
    difficulty: 'medium',
    id: 0,
  },  // c. 1754 BC
  {
    name: 'Tutankhamun ruled Egypt',
    shortName: 'Tutankhamun',
    value: -1332,
    topic: ['Tutankhamun'],
    difficulty: 'easy',
    id: 1,
  },  // c. 1332 BC
  {
    name: 'The Trojan War was fought',
    shortName: 'Trojan War',
    value: -1184,
    topic: ['Troy'],
    difficulty: 'easy',
    id: 2,
  },  // traditional dating, c. 1184 BC
  {
    name: 'The first Olympic Games were held',
    shortName: 'Olympics',
    value: -776,
    topic: ['Olympic'],
    difficulty: 'easy',
    id: 3,
  },
  {
    name: 'Rome was founded',
    shortName: 'Rome',
    value: -753,
    topic: ['Rome'],
    difficulty: 'easy',
    id: 4,
  },  // traditional dating
  {
    name: 'The Roman Republic was established',
    shortName: 'Roman Republic',
    value: -509,
    topic: ['Rome'],
    difficulty: 'easy',
    id: 5,
  },
  {
    name: 'The Battle of Marathon was fought',
    shortName: 'Marathon',
    value: -490,
    topic: ['Marathon'],
    difficulty: 'hard',
    id: 6,
  },
  {
    name: 'The Battle of Thermopylae was fought',
    shortName: 'Thermopylae',
    value: -480,
    topic: ['Thermopylae'],
    difficulty: 'hard',
    id: 7,
  },
  {
    name: 'Alexander the Great conquered Persia',
    shortName: 'Alexander Conquers Persia',
    value: -331,
    topic: ['Alexander the Great'],
    difficulty: 'medium',
    id: 8,
  },
  {
    name: 'The Great Wall of China was begun',
    shortName: 'Great Wall of China',
    value: -221,
    topic: ['China'],
    difficulty: 'medium',
    id: 9,
  },  // under Qin Shi Huang
  {
    name: 'Hannibal crossed the Alps',
    shortName: 'Hannibal at the Alps',
    value: -218,
    topic: ['Hannibal'],
    difficulty: 'medium',
    id: 10,
  },
  {
    name: 'Carthage was destroyed by Rome',
    shortName: 'Carthage destroyed',
    value: -146,
    topic: ['Rome', 'Carthage'],
    difficulty: 'hard',
    id: 11,
  },
  {
    name: 'Julius Caesar was assassinated',
    shortName: 'Julius Caesar killed',
    value: -44,
    topic: ['Julius Caesar'],
    difficulty: 'easy',
    id: 12,
  },
  {
    name: 'The Battle of Actium was fought',
    shortName: 'Actium',
    value: -31,
    topic: ['Actium'],
    difficulty: 'hard',
    id: 13,
  },
  {
    name: 'The Roman Empire was founded by Augustus',
    shortName: 'Roman Empire',
    value: -27,
    topic: ['Rome'],
    difficulty: 'medium',
    id: 14,
  },
  {
    name: 'Jesus was crucified',
    shortName: 'Jesus crucified',
    value: 30,
    topic: ['Jesus'],
    difficulty: 'easy',
    id: 15,
  },  // c. AD 30
  {
    name: 'Vesuvius destroyed Pompeii',
    shortName: 'Vesuvius erupted',
    value: 79,
    topic: ['Pompeii'],
    difficulty: 'medium',
    id: 16,
  },
  {
    name: 'Constantine legalized Christianity',
    shortName: 'Christianity legalized',
    value: 313,
    topic: ['Constantine'],
    difficulty: 'medium',
    id: 17,
  },  // Edict of Milan
  {
    name: 'The Roman Empire split in two',
    shortName: 'Roman Empire split',
    value: 395,
    topic: ['Rome'],
    difficulty: 'hard',
    id: 18,
  },
  {
    name: 'Rome was sacked by the Visigoths',
    shortName: 'Visigoths sack Rome',
    value: 410,
    topic: ['Rome'],
    difficulty: 'hard',
    id: 19,
  },
  {
    name: 'The Western Roman Empire fell',
    shortName: 'Western Roman Empire fell',
    value: 476,
    topic: ['Rome'],
    difficulty: 'easy',
    id: 20,
  },
  {
    name: 'Muhammad made the Hijra to Medina',
    shortName: 'Muhammad Hijra',
    value: 622,
    topic: ['Muhammad'],
    difficulty: 'easy',
    id: 21,
  },
  {
    name: 'The Battle of Tours halted the Umayyad advance',
    shortName: 'Battle of Tours',
    value: 732,
    topic: ['Umayyad'],
    difficulty: 'hard',
    id: 22,
  },
  {
    name: 'Charlemagne was crowned emperor',
    shortName: 'Charlemagne crowned',
    value: 800,
    topic: ['Charlemagne'],
    difficulty: 'medium',
    id: 23,
  },
  {
    name: 'The Vikings discovered America',
    shortName: 'Vikings in America',
    value: 1000,
    topic: [],
    difficulty: 'easy',
    id: 24,
  },  // c. 1000, Leif Erikson
  {
    name: 'The Great Schism split the Christian church',
    shortName: 'Christian church split',
    value: 1054,
    topic: [],
    difficulty: 'medium',
    id: 25,
  },
  {
    name: 'The Battle of Hastings was fought',
    shortName: 'Hastings',
    value: 1066,
    topic: [],
    difficulty: 'medium',
    id: 26,
  },
  {
    name: 'The First Crusade captured Jerusalem',
    shortName: 'Jerusalem captured',
    value: 1099,
    topic: ['Jerusalem'],
    difficulty: 'easy',
    id: 27,
  },
  {
    name: 'The University of Oxford began teaching',
    shortName: 'University of Oxford',
    value: 1096,
    topic: ['University of Oxford'],
    difficulty: 'hard',
    id: 28,
  },  // c. 1096
  {
    name: 'The Magna Carta was signed',
    shortName: 'Magna Carta',
    value: 1215,
    topic: [],
    difficulty: 'medium',
    id: 29,
  },
  {
    name: 'Genghis Khan\'s Mongols sacked Beijing',
    shortName: 'Mongols sack Beijing',
    value: 1215,
    topic: ['Genghis Khan'],
    difficulty: 'easy',
    id: 30,
  },
  {
    name: 'Marco Polo set out for China',
    shortName: 'Marco Polo',
    value: 1271,
    topic: ['Marco Polo'],
    difficulty: 'medium',
    id: 31,
  },
  {
    name: 'The Black Death reached Europe',
    shortName: 'Black Death at Europe',
    value: 1347,
    topic: ['Black Death'],
    difficulty: 'easy',
    id: 32,
  },
  {
    name: 'The Hundred Years\' War began',
    shortName: 'Hunded Years War',
    value: 1337,
    topic: ['Hundred Years\' War'],
    difficulty: 'hard',
    id: 33,
  },
  {
    name: 'The Battle of Agincourt was fought',
    shortName: 'Agincourt',
    value: 1415,
    topic: ['Agincourt'],
    difficulty: 'hard',
    id: 34,
  },
  {
    name: 'Joan of Arc lifted the siege of Orléans',
    shortName: 'Siege of Orléans',
    value: 1429,
    topic: ['Joan of Arc'],
    difficulty: 'medium',
    id: 35,
  },
  {
    name: 'Johannes Gutenberg printed his Bible',
    shortName: 'Gutenberg prints Bible',
    value: 1455,
    topic: ['Johannes Gutenberg'],
    difficulty: 'medium',
    id: 36,
  },  // c. 1455
  {
    name: 'Constantinople fell to the Ottomans',
    shortName: 'Ottomans conquer Constantinople',
    value: 1453,
    topic: ['Constantinople'],
    difficulty: 'hard',
    id: 37,
  },
  {
    name: 'America was discovered (by Columbus)',
    shortName: 'Columbus at America',
    value: 1492,
    topic: ['Christopher Columbus'],
    difficulty: 'easy',
    id: 38,
  },
  {
    name: 'Vasco da Gama reached India by sea',
    shortName: 'Vasco da Gama at India',
    value: 1498,
    topic: ['Vasco da Gama'],
    difficulty: 'medium',
    id: 39,
  },
  {
    name: 'Michelangelo finished the statue of David',
    shortName: 'Michelangelo\'s David',
    value: 1504,
    topic: ['Michelangelo'],
    difficulty: 'easy',
    id: 40,
  },
  {
    name: 'Martin Luther posted his 95 Theses',
    shortName: 'Luther\'s 95 Theses',
    value: 1517,
    topic: ['Martin Luther'],
    difficulty: 'easy',
    id: 41,
  },
  {
    name: 'Magellan\'s expedition circumnavigated the globe',
    shortName: 'Magellan\'s expedition',
    value: 1522,
    topic: ['Ferdinand Magellan'],
    difficulty: 'medium',
    id: 42,
  },
  {
    name: 'The Aztec Empire fell to Cortés',
    shortName: 'Aztec Empire falls',
    value: 1521,
    topic: ['Hernán Cortés', 'Aztec Empire'],
    difficulty: 'medium',
    id: 43,
  },
  {
    name: 'The Inca Empire fell to Pizarro',
    shortName: 'Inca Empire falls',
    value: 1533,
    topic: ['Francisco Pizarro'],
    difficulty: 'medium',
    id: 44,
  },
  {
    name: 'Copernicus published his heliocentric theory',
    shortName: 'Copernicus\' Theory',
    value: 1543,
    topic: ['Nicolaus Copernicus'],
    difficulty: 'medium',
    id: 45,
  },
  {
    name: 'The Spanish Armada was defeated',
    shortName: 'Spanish Armada defeated',
    value: 1588,
    topic: ['Spanish Armada'],
    difficulty: 'hard',
    id: 46,
  },
  {
    name: 'Shakespeare\'s Hamlet was first performed',
    shortName: 'Hamlet performed',
    value: 1601,
    topic: ['Shakespeare'],
    difficulty: 'easy',
    id: 47,
  },  // c. 1600-1601 TODO: Move to books or arts?
  {
    name: 'Jamestown was founded',
    shortName: 'Jamestown founded',
    value: 1607,
    topic: ['Jamestown'],
    difficulty: 'hard',
    id: 48,
  },
  {
    name: 'Galileo first pointed a telescope at the sky',
    shortName: 'Galileo looks at sky',
    value: 1609,
    topic: ['Galileo Galilei'],
    difficulty: 'easy',
    id: 49,
  },
  {
    name: 'The Thirty Years\' War began',
    shortName: 'Thirty Years\' War',
    value: 1618,
    topic: ['Thirty Years\' War'],
    difficulty: 'medium',
    id: 50,
  },
  {
    name: 'The Taj Mahal was completed',
    shortName: 'Taj Mahal',
    value: 1653,
    topic: ['Taj Mahal'],
    difficulty: 'easy',
    id: 51,
  },
  {
    name: 'The Great Fire of London burned',
    shortName: 'Great Fire of London',
    value: 1666,
    topic: [],
    difficulty: 'hard',
    id: 52,
  },
  {
    name: 'Newton published the Principia',
    shortName: 'Newton\'s Principia',
    value: 1687,
    topic: ['Isaac Newton'],
    difficulty: 'medium',
    id: 53,
  },
  {
    name: 'The Glorious Revolution took place in England',
    shortName: 'Gloruous Revolution',
    value: 1688,
    topic: [],
    difficulty: 'medium',
    id: 54,
  },
  {
    name: 'St. Petersburg was founded',
    shortName: 'St. Petersburg founded',
    value: 1703,
    topic: ['St. Petersburg'],
    difficulty: 'hard',
    id: 55,
  },
  {
    name: 'The Boston Tea Party took place',
    shortName: 'Boston Tea Party',
    value: 1773,
    topic: ['Boston Tea Party'],
    difficulty: 'hard',
    id: 56,
  },
  {
    name: 'The United States declared independence',
    shortName: 'United States independence',
    value: 1776,
    topic: [],
    difficulty: 'easy',
    id: 57,
  },
  {
    // TODO: Inventions?
    name: 'The Montgolfier brothers flew the first hot air balloon',
    shortName: 'Hot air ballon',
    value: 1783,
    topic: ['Montgolfier'],
    difficulty: 'hard',
    id: 58,
  },
  {
    name: 'The United States Constitution was signed',
    shortName: 'United States Constitution',
    value: 1787,
    topic: [],
    difficulty: 'medium',
    id: 59,
  },
  {
    name: 'The French Revolution began',
    shortName: 'French Revolution',
    value: 1789,
    topic: [],
    difficulty: 'easy',
    id: 60,
  },
  {
    name: 'The guillotine claimed Louis XVI',
    shortName: 'Louis XVI guillotined',
    value: 1793,
    topic: ['Louis XVI'],
    difficulty: 'medium',
    id: 61,
  },
  {
    name: 'Napoleon crowned himself emperor',
    shortName: 'Napoleon crowned',
    value: 1804,
    topic: ['Napoleon Bonaparte'],
    difficulty: 'medium',
    id: 62,
  },
  {
    name: 'The Battle of Trafalgar was fought',
    shortName: 'Trafalgar',
    value: 1805,
    topic: ['Trafalgar'],
    difficulty: 'hard',
    id: 63,
  },
  {
    name: 'Napoleon invaded Russia',
    shortName: 'Napoleon at Russia',
    value: 1812,
    topic: ['Napoleon Bonaparte'],
    difficulty: 'medium',
    id: 64,
  },
  {
    name: 'The Battle of Waterloo was fought',
    shortName: 'Waterloo',
    value: 1815,
    topic: ['Waterloo'],
    difficulty: 'hard',
    id: 65,
  },
  {
    // TODO: inventions?
    name: 'The first passenger railway opened',
    shortName: 'Passenger railway',
    value: 1825,
    topic: [],
    difficulty: 'medium',
    id: 66,
  },  // Stockton & Darlington
  {
    name: 'Slavery was abolished in the British Empire',
    shortName: 'British abolish Slavery',
    value: 1833,
    topic: ['Great Britain'],
    difficulty: 'hard',
    id: 67,
  },
  {
    name: 'The California Gold Rush began',
    shortName: 'California Gold Rush',
    value: 1848,
    topic: ['California'],
    difficulty: 'medium',
    id: 68,
  },
  {
    name: 'The American Civil War began',
    shortName: 'American Civil War',
    value: 1861,
    topic: [],
    difficulty: 'easy',
    id: 69,
  },
  {
    name: 'Lincoln issued the Emancipation Proclamation',
    shortName: 'Lincoln Emancipation Proclamation',
    value: 1863,
    topic: ['Abraham Lincoln'],
    difficulty: 'medium',
    id: 70,
  },
  {
    name: 'Lincoln was assassinated',
    shortName: 'Lincoln killed',
    value: 1865,
    topic: ['Abraham Lincoln'],
    difficulty: 'easy',
    id: 71,
  },
  {
    // TODO: inventions
    name: 'The transatlantic telegraph cable was completed',
    shortName: 'Transatlantic telegraph',
    value: 1866,
    topic: [],
    difficulty: 'easy',
    id: 72,
  },
  {
    // TODO: inventions
    name: 'The transcontinental railroad was completed',
    shortName: 'Transcontinental railroad',
    value: 1869,
    topic: [],
    difficulty: 'easy',
    id: 73,
  },
  {
    name: 'The Suez Canal opened',
    shortName: 'Suez Canal opened',
    value: 1869,
    topic: [],
    id: 74,
    difficulty: 'medium'
  },
  {
    name: 'Krakatoa erupted',
    shortName: 'Krakatoa',
    value: 1883,
    topic: [],
    id: 75,
    difficulty: 'hard'
  },
  {
    name: 'The first modern Olympic Games were held',
    shortName: 'Modern Olympics held',
    value: 1896,
    topic: ['Olympic Games'],
    difficulty: 'medium',
    id: 76,
  },
  {
    name: 'The first movie was screened by the Lumière brothers',
    shortName: 'First move screened',
    value: 1895,
    topic: ['Lumière'],
    difficulty: 'hard',
    id: 77,
  },
  {
    name: 'Marconi sent the first transatlantic radio signal',
    shortName: 'Transatlantic radio signal',
    value: 1901,
    topic: ['Guglielmo Marconi'],
    difficulty: 'hard',
    id: 78,
  },
  {
    name: 'The Wright brothers flew the first airplane',
    shortName: 'Wrigths\' airplane',
    value: 1903,
    topic:
        ['Wilbur Wright (Wright brothers)', 'Orville Wright (Wright brothers)'],
    difficulty: 'medium',
    id: 79,
  },
  {
    name: 'Einstein published his theory of special relativity',
    shortName: 'Einstein\'s relativity',
    value: 1905,
    topic: ['Albert Einstein'],
    difficulty: 'medium',
    id: 80,
  },
  {
    name: 'The San Francisco earthquake struck',
    shortName: 'San Francisco earthquake',
    value: 1906,
    topic: [],
    difficulty: 'medium',
    id: 81,
  },
  {
    name: 'The Titanic sank',
    shortName: 'Titanic sank',
    value: 1912,
    topic: ['Titanic'],
    difficulty: 'easy',
    id: 82,
  },
  {
    name: 'World War I began',
    shortName: 'WWI began',
    value: 1914,
    topic: ['WWI'],
    difficulty: 'easy',
    id: 83
  },
  {
    name: 'The Panama Canal opened',
    shortName: 'Panama canal opened',
    value: 1914,
    topic: ['Panama'],
    difficulty: 'medium',
    id: 84,
  },
  {
    name: 'The Russian Revolution overthrew the Tsar',
    shortName: 'Tsar overthrown',
    value: 1917,
    topic: ['Nicholas II'],
    difficulty: 'medium',
    id: 85,
  },
  {
    name: 'World War I ended',
    shortName: 'WWI ended',
    value: 1918,
    topic: ['WWI'],
    difficulty: 'easy',
    id: 86
  },
  {
    name: 'The Spanish flu pandemic swept the world',
    shortName: 'Spanish flu pandemic',
    value: 1918,
    topic: ['Spanish Flu'],
    difficulty: 'medium',
    id: 87,
  },
  {
    name: 'Women won the right to vote in the United States',
    shortName: 'Women vote in United States',
    value: 1920,
    topic: [],
    difficulty: 'hard',
    id: 88,
  },
  {
    name: 'Tutankhamun\'s tomb was discovered',
    shortName: 'Tutankhamun\'s tomb discovered',
    value: 1922,
    topic: ['Tutankhamun'],
    difficulty: 'medium',
    id: 89,
  },
  {
    name: 'The Wall Street Crash triggered the Great Depression',
    shortName: 'Great Depression',
    value: 1929,
    topic: [],
    difficulty: 'easy',
    id: 90,
  },
  {
    name: 'Hitler came to power in Germany',
    shortName: 'Hitler rose to power',
    value: 1933,
    topic: ['Adolf Hitler'],
    difficulty: 'medium',
    id: 91,
  },
  {
    name: 'The Hindenburg disaster occurred',
    shortName: 'Hindenburg disaster',
    value: 1937,
    topic: [],
    difficulty: 'hard',
    id: 92,
  },
  {
    name: 'World War II began',
    shortName: 'WWII began',
    value: 1939,
    topic: ['WWII'],
    difficulty: 'easy',
    id: 93,
  },
  {
    name: 'Pearl Harbor was attacked',
    shortName: 'Pearl Harbor attacked',
    value: 1941,
    topic: ['Pearl Harbor'],
    difficulty: 'medium',
    id: 94,
  },
  {
    name: 'The D-Day landings took place in Normandy',
    shortName: 'D-Day landings in Normandy',
    value: 1944,
    topic: [],
    difficulty: 'hard',
    id: 95,
  },
  {
    name: 'The first atomic bomb was dropped on Hiroshima',
    shortName: 'Hiroshima bombed',
    value: 1945,
    topic: ['Hiroshima'],
    difficulty: 'easy',
    id: 96,
  },
  {
    name: 'World War II ended',
    shortName: 'WWII ended',
    value: 1945,
    topic: ['WWII'],
    difficulty: 'easy',
    id: 97,
  },
  {
    name: 'The United Nations was founded',
    shortName: 'UN',
    value: 1945,
    topic: ['United Nations'],
    difficulty: 'medium',
    id: 98,
  },
  {
    name: 'India gained independence',
    shortName: 'Indian independence',
    value: 1947,
    topic: [],
    difficulty: 'medium',
    id: 99,
  },
  {
    // TODO: science
    name: 'The sound barrier was broken',
    shortName: 'Sound barrier',
    value: 1947,
    topic: [],
    difficulty: 'hard',
    id: 100,
  },
  {
    name: 'The state of Israel was founded',
    shortName: 'Israel',
    value: 1948,
    topic: ['Israel'],
    difficulty: 'easy',
    id: 101,
  },
  {
    name: 'NATO was founded',
    shortName: 'NATO',
    value: 1949,
    topic: ['NATO'],
    difficulty: 'easy',
    id: 102,
  },
  {
    name: 'The People\'s Republic of China was proclaimed',
    shortName: 'Replublic of China proclaimed',
    value: 1949,
    topic: ['China'],
    difficulty: 'medium',
    id: 103,
  },
  {
    name: 'The Korean War began',
    shortName: 'Korean War began',
    value: 1950,
    topic: [],
    difficulty: 'medium',
    id: 104,
  },
  {
    // TODO: discoveries
    name: 'The structure of DNA was discovered',
    shortName: 'DNA structure',
    value: 1953,
    topic: ['DNA'],
    difficulty: 'easy',
    id: 105,
  },
  {
    name: 'Mount Everest was first climbed',
    shortName: 'Mount Everest climbed',
    value: 1953,
    topic: [],
    difficulty: 'medium',
    id: 106,
  },
  {
    name: 'Rosa Parks refused to give up her seat',
    shortName: 'Rosa Parks refused',
    value: 1955,
    topic: ['Rosa Parks'],
    difficulty: 'medium',
    id: 107,
  },
  {
    name: 'The Treaty of Rome created the European Economic Community',
    shortName: 'European Economic Community',
    value: 1957,
    topic: [],
    difficulty: 'hard',
    id: 108,
  },
  {
    name: 'Yuri Gagarin became the first human in space',
    shortName: 'Gagarin in Space',
    value: 1961,
    topic: ['Yuri Gagarin'],
    difficulty: 'medium',
    id: 109,
  },
  {
    name: 'The Cuban Missile Crisis brought the world to the brink',
    shortName: 'Cuban Missile Crisis',
    value: 1962,
    topic: [],
    difficulty: 'easy',
    id: 110,
  },
  {
    name: 'Martin Luther King gave his "I Have a Dream" speech',
    shortName: 'I Have a Dream',
    value: 1963,
    topic: ['Martin Luther King Jr.'],
    difficulty: 'medium',
    id: 111,
  },
  {
    name: 'John F. Kennedy was assassinated',
    shortName: 'Kennedy killed',
    value: 1963,
    topic: ['John F. Kennedy'],
    difficulty: 'easy',
    id: 112,
  },
  {
    name: 'The Beatles appeared on The Ed Sullivan Show',
    shortName: 'Beatles on The Ed Sullivan Show',
    value: 1964,
    topic: ['Beatles', 'John Lennon', 'Paul McCartney'],
    difficulty: 'medium',
    id: 113,
  },
  {
    name: 'The Civil Rights Act was signed (United States)',
    shortName: 'Civil Rights Act',
    value: 1964,
    topic: [],
    difficulty: 'medium',
    id: 114,
  },
  {
    // TODO: science
    name: 'The first heart transplant was performed',
    shortName: 'Heart transplant',
    value: 1967,
    topic: [],
    difficulty: 'medium',
    id: 115,
  },
  {
    name: 'Martin Luther King was assassinated',
    shortName: 'Martin Luther King killed',
    value: 1968,
    topic: ['Martin Luther King Jr.'],
    difficulty: 'medium',
    id: 116,
  },
  {
    // TODO: science
    name: 'Humans landed on the moon',
    shortName: 'Humans on the moon',
    value: 1969,
    topic: [],
    difficulty: 'easy',
    id: 117,
  },
  {
    name: 'Woodstock took place',
    shortName: 'Woodstock',
    value: 1969,
    topic: [],
    difficulty: 'medium',
    id: 118,
  },
  {
    name: 'The Watergate scandal broke',
    shortName: 'Watergate scandal',
    value: 1972,
    topic: [],
    difficulty: 'medium',
    id: 119,
  },
  {
    name: 'Nixon resigned as US president',
    shortName: 'Nixon resigned',
    value: 1974,
    topic: ['Richard Nixon'],
    difficulty: 'medium',
    id: 120,
  },
  {
    name: 'The Vietnam War ended',
    shortName: 'Vietnam War ended',
    value: 1975,
    topic: [],
    difficulty: 'easy',
    id: 121,
  },
  {
    // TODO: science
    name: 'The first test-tube baby was born',
    shortName: 'Test-tube baby',
    value: 1978,
    topic: [],
    difficulty: 'medium',
    id: 122,
  },
  {
    name: 'Margaret Thatcher became UK prime minister',
    shortName: 'Thatcher took office',
    value: 1979,
    topic: ['Margaret Thatcher'],
    difficulty: 'easy',
    id: 123,
  },
  {
    name: 'Smallpox was declared eradicated',
    shortName: 'Smallpox eradicated',
    value: 1980,
    topic: [],
    difficulty: 'medium',
    id: 124,
  },
  {
    name: 'John Lennon was shot',
    shortName: 'Lennon killed',
    value: 1980,
    topic: ['John Lennon'],
    difficulty: 'easy',
    id: 125,
  },
  {
    name: 'MTV started broadcasting',
    shortName: 'MTV',
    value: 1981,
    topic: ['MTV'],
    difficulty: 'medium',
    id: 126,
  },
  {
    // TODO: inventions?
    name: 'The IBM PC was launched',
    shortName: 'IBM PC',
    value: 1981,
    topic: ['IBM'],
    difficulty: 'medium',
    id: 127,
  },
  {
    name: 'Live Aid was broadcast worldwide',
    shortName: 'Live Aid',
    value: 1985,
    topic: [],
    difficulty: 'hard',
    id: 128,
  },
  {
    name: 'The Chernobyl disaster occurred',
    shortName: 'Chernobyl',
    value: 1986,
    topic: ['Chernobyl'],
    difficulty: 'medium',
    id: 129,
  },
  {
    name: 'The Challenger space shuttle exploded',
    shortName: 'Challenger shuttle exploded',
    value: 1986,
    topic: [],
    difficulty: 'hard',
    id: 130,
  },
  {
    name: 'The Berlin Wall fell',
    shortName: 'Berlin Wall fell',
    value: 1989,
    topic: ['Berlin Wall'],
    difficulty: 'easy',
    id: 131,
  },
  {
    name: 'Nelson Mandela was released from prison',
    shortName: 'Mandela released',
    value: 1990,
    topic: ['Nelson Mandela'],
    difficulty: 'hard',
    id: 132,
  },
  {
    // TODO: science
    name: 'The Hubble Space Telescope was launched',
    shortName: 'Hubble Space Telescope',
    value: 1990,
    topic: [],
    difficulty: 'hard',
    id: 133,
  },
  {
    name: 'The Soviet Union collapsed',
    shortName: 'Soviet Union fell',
    value: 1991,
    topic: ['Soviet Union'],
    difficulty: 'medium',
    id: 134,
  },
  {
    name: 'The European Union was established',
    shortName: 'European Union established',
    value: 1993,
    topic: ['European Union'],
    difficulty: 'hard',
    id: 135,
  },  // Maastricht Treaty in force
  {
    name: 'Nelson Mandela became president of South Africa',
    shortName: 'Mandela took office',
    value: 1994,
    topic: ['Nelson Mandela'],
    difficulty: 'hard',
    id: 136,
  },
  {
    // TODO: Science
    name: 'Dolly the sheep was cloned',
    shortName: 'Dolly the sheep',
    value: 1996,
    topic: [],
    difficulty: 'easy',
    id: 138,
  },
  {
    name: 'Hong Kong was returned to China',
    shortName: 'Hong Kong returned',
    value: 1997,
    topic: ['China', 'Hong Kong'],
    difficulty: 'easy',
    id: 139,
  },
  {
    name: 'The euro was introduced',
    shortName: 'Euro introduced',
    value: 1999,
    topic: [],
    difficulty: 'medium',
    id: 140,
  },
  {
    name: 'The September 11 attacks occurred in New York City',
    shortName: 'September 11',
    value: 2001,
    topic: [],
    difficulty: 'easy',
    id: 141,
  },
  {
    name: 'The Indian Ocean tsunami struck',
    shortName: 'Indian Ocean tsunami',
    value: 2004,
    topic: [],
    difficulty: 'medium',
    id: 142,
  },
  {
    name: 'The global financial crisis erupted',
    shortName: 'Global financial crisis',
    value: 2008,
    topic: [],
    difficulty: 'medium',
    id: 143,
  },
  {
    name: 'Barack Obama became US president',
    shortName: 'Obama took office',
    value: 2009,
    topic: ['Barack Obama'],
    difficulty: 'easy',
    id: 144,
  },
  {
    name: 'The Arab Spring began',
    shortName: 'Arab Spring',
    value: 2010,
    topic: [],
    difficulty: 'medium',
    id: 145,
  },
  {
    name: 'The Fukushima nuclear disaster occurred',
    shortName: 'Fukushima disaster',
    value: 2011,
    topic: [],
    difficulty: 'medium',
    id: 146,
  },
  {
    // TODO: Science
    name: 'The Higgs boson was discovered',
    shortName: 'Higgs boson',
    value: 2012,
    topic: [],
    difficulty: 'medium',
    id: 147,
  },
  {
    // TODO: Science
    name: 'gravitational waves were first detected',
    shortName: 'Gravitational waves',
    value: 2015,
    topic: [],
    difficulty: 'hard',
    id: 148,
  },
  {
    name: 'The United Kingdom voted for Brexit',
    shortName: 'Brexit',
    value: 2016,
    topic: ['Brexit'],
    difficulty: 'medium',
    id: 149,
  },
  {
    // TODO: Science
    name: 'The first image of a black hole was published',
    shortName: 'Black hole image',
    value: 2019,
    topic: [],
    difficulty: 'hard',
    id: 150,
  },
  {
    name: 'The COVID-19 pandemic began',
    shortName: 'COVID-19',
    value: 2020,
    topic: [],
    difficulty: 'easy',
    id: 151,
  },
];
