export const historicalEvents = [
  {name: 'the Great Pyramid of Giza was built', value: -2560},  // c. 2560 BC
  {name: 'Stonehenge was erected', value: -2500},               // c. 2500 BC
  {name: 'Hammurabi wrote his code of laws', value: -1754},     // c. 1754 BC
  {name: 'Tutankhamun ruled Egypt', value: -1332},              // c. 1332 BC
  {
    name: 'the Trojan War was fought',
    value: -1184
  },  // traditional dating, c. 1184 BC
  {name: 'the first Olympic Games were held', value: -776},
  {name: 'Rome was founded', value: -753},  // traditional dating
  {name: 'the Roman Republic was established', value: -509},
  {name: 'the Battle of Marathon was fought', value: -490},
  {name: 'the Battle of Thermopylae was fought', value: -480},
  {name: 'the Parthenon was completed', value: -432},
  {name: 'Alexander the Great conquered Persia', value: -331},
  {
    name: 'the Great Wall of China was begun',
    value: -221
  },  // under Qin Shi Huang
  {name: 'Hannibal crossed the Alps', value: -218},
  {name: 'Carthage was destroyed by Rome', value: -146},
  {name: 'Julius Caesar was assassinated', value: -44},
  {name: 'the Battle of Actium was fought', value: -31},
  {name: 'the Roman Empire was founded by Augustus', value: -27},
  {name: 'Jesus was crucified', value: 30},  // c. AD 30
  {name: 'Vesuvius destroyed Pompeii', value: 79},
  {name: 'the Colosseum was completed', value: 80},
  {name: 'Constantine legalized Christianity', value: 313},  // Edict of Milan
  {name: 'the Roman Empire split in two', value: 395},
  {name: 'Rome was sacked by the Visigoths', value: 410},
  {name: 'the Western Roman Empire fell', value: 476},
  {name: 'Muhammad made the Hijra to Medina', value: 622},
  {name: 'the Battle of Tours halted the Umayyad advance', value: 732},
  {name: 'Charlemagne was crowned emperor', value: 800},
  {
    name: 'the Vikings discovered America',
    value: 1000
  },  // c. 1000, Leif Erikson
  {name: 'the Great Schism split the Christian church', value: 1054},
  {name: 'the Battle of Hastings was fought', value: 1066},
  {name: 'the First Crusade captured Jerusalem', value: 1099},
  {name: 'the University of Oxford began teaching', value: 1096},  // c. 1096
  {name: 'the Magna Carta was signed', value: 1215},
  {name: 'Genghis Khan\'s Mongols sacked Beijing', value: 1215},
  {name: 'Marco Polo set out for China', value: 1271},
  {name: 'the Black Death reached Europe', value: 1347},
  {name: 'the Hundred Years\' War began', value: 1337},
  {name: 'the Battle of Agincourt was fought', value: 1415},
  {name: 'Joan of Arc lifted the siege of Orléans', value: 1429},
  {name: 'Gutenberg printed his Bible', value: 1455},  // c. 1455
  {name: 'Constantinople fell to the Ottomans', value: 1453},
  {name: 'America was discovered (by Columbus)', value: 1492},
  {name: 'Vasco da Gama reached India by sea', value: 1498},
  {name: 'Michelangelo finished the statue of David', value: 1504},
  {name: 'Michelangelo completed the Sistine Chapel ceiling', value: 1512},
  {name: 'Martin Luther posted his 95 Theses', value: 1517},
  {name: 'Magellan\'s expedition circumnavigated the globe', value: 1522},
  {name: 'the Aztec Empire fell to Cortés', value: 1521},
  {name: 'the Inca Empire fell to Pizarro', value: 1533},
  {name: 'Copernicus published his heliocentric theory', value: 1543},
  {name: 'the Spanish Armada was defeated', value: 1588},
  {
    name: 'Shakespeare\'s Hamlet was first performed',
    value: 1601
  },  // c. 1600-1601
  {name: 'Jamestown was founded', value: 1607},
  {name: 'Galileo first pointed a telescope at the sky', value: 1609},
  {name: 'the Mayflower landed at Plymouth', value: 1620},
  {name: 'the Thirty Years\' War began', value: 1618},
  {name: 'the Taj Mahal was completed', value: 1653},
  {name: 'the Great Fire of London burned', value: 1666},
  {name: 'Newton published the Principia', value: 1687},
  {name: 'the Glorious Revolution took place in England', value: 1688},
  {name: 'St. Petersburg was founded', value: 1703},
  {name: 'the steam engine was patented by James Watt', value: 1769},
  {name: 'the Boston Tea Party took place', value: 1773},
  {name: 'America declared independence', value: 1776},
  {
    name: 'the Montgolfier brothers flew the first hot air balloon',
    value: 1783
  },
  {name: 'the US Constitution was signed', value: 1787},
  {name: 'the French Revolution began', value: 1789},
  {name: 'the guillotine claimed Louis XVI', value: 1793},
  {name: 'the smallpox vaccine was invented', value: 1796},
  {name: 'Napoleon crowned himself emperor', value: 1804},
  {name: 'the Battle of Trafalgar was fought', value: 1805},
  {name: 'Napoleon invaded Russia', value: 1812},
  {name: 'the Battle of Waterloo was fought', value: 1815},
  {
    name: 'the first passenger railway opened',
    value: 1825
  },  // Stockton & Darlington
  {name: 'the first photograph was taken', value: 1826},  // Niépce
  {name: 'slavery was abolished in the British Empire', value: 1833},
  {name: 'the telegraph was demonstrated by Morse', value: 1844},
  {name: 'the California Gold Rush began', value: 1848},
  {name: 'the Communist Manifesto was published', value: 1848},
  {name: 'Darwin published On the Origin of Species', value: 1859},
  {name: 'the American Civil War began', value: 1861},
  {name: 'Lincoln issued the Emancipation Proclamation', value: 1863},
  {name: 'Lincoln was assassinated', value: 1865},
  {name: 'the transatlantic telegraph cable was completed', value: 1866},
  {name: 'the transcontinental railroad was completed', value: 1869},
  {name: 'the Suez Canal opened', value: 1869},
  {name: 'the telephone was invented', value: 1876},
  {name: 'the light bulb was perfected by Edison', value: 1879},
  {name: 'Krakatoa erupted', value: 1883},
  {name: 'the Eiffel Tower was completed', value: 1889},
  {name: 'the first modern Olympic Games were held', value: 1896},
  {name: 'X-rays were discovered', value: 1895},
  {name: 'the first movie was screened by the Lumière brothers', value: 1895},
  {name: 'Marconi sent the first transatlantic radio signal', value: 1901},
  {name: 'the Wright brothers flew the first airplane', value: 1903},
  {name: 'Einstein published his theory of special relativity', value: 1905},
  {name: 'the San Francisco earthquake struck', value: 1906},
  {name: 'the Model T Ford went on sale', value: 1908},
  {name: 'the Titanic sank', value: 1912},
  {name: 'World War I began', value: 1914},
  {name: 'the Panama Canal opened', value: 1914},
  {name: 'the Russian Revolution overthrew the Tsar', value: 1917},
  {name: 'World War I ended', value: 1918},
  {name: 'the Spanish flu pandemic swept the world', value: 1918},
  {name: 'women won the right to vote in the US', value: 1920},
  {name: 'Tutankhamun\'s tomb was discovered', value: 1922},
  {name: 'penicillin was discovered', value: 1928},
  {name: 'the Wall Street Crash triggered the Great Depression', value: 1929},
  {name: 'the Empire State Building was completed', value: 1931},
  {name: 'Hitler came to power in Germany', value: 1933},
  {name: 'the Hindenburg disaster occurred', value: 1937},
  {name: 'the Golden Gate Bridge opened', value: 1937},
  {name: 'World War II began', value: 1939},
  {name: 'Pearl Harbor was attacked', value: 1941},
  {name: 'the D-Day landings took place in Normandy', value: 1944},
  {name: 'the first atomic bomb was dropped on Hiroshima', value: 1945},
  {name: 'World War II ended', value: 1945},
  {name: 'the United Nations was founded', value: 1945},
  {name: 'India gained independence', value: 1947},
  {name: 'the transistor was invented', value: 1947},
  {name: 'the sound barrier was broken', value: 1947},
  {name: 'the state of Israel was founded', value: 1948},
  {name: 'NATO was founded', value: 1949},
  {name: 'the People\'s Republic of China was proclaimed', value: 1949},
  {name: 'the Korean War began', value: 1950},
  {name: 'the structure of DNA was discovered', value: 1953},
  {name: 'Mount Everest was first climbed', value: 1953},
  {name: 'the polio vaccine was introduced', value: 1955},
  {name: 'Rosa Parks refused to give up her seat', value: 1955},
  {name: 'Sputnik became the first satellite in space', value: 1957},
  {
    name: 'the Treaty of Rome created the European Economic Community',
    value: 1957
  },
  {name: 'the laser was invented', value: 1960},
  {name: 'Yuri Gagarin became the first human in space', value: 1961},
  {name: 'the Berlin Wall was built', value: 1961},
  {
    name: 'the Cuban Missile Crisis brought the world to the brink',
    value: 1962
  },
  {name: 'Martin Luther King gave his "I Have a Dream" speech', value: 1963},
  {name: 'John F. Kennedy was assassinated', value: 1963},
  {name: 'the Beatles appeared on The Ed Sullivan Show', value: 1964},
  {name: 'the Civil Rights Act was signed', value: 1964},
  {name: 'the first heart transplant was performed', value: 1967},
  {name: 'Martin Luther King was assassinated', value: 1968},
  {name: 'men landed on the moon', value: 1969},
  {name: 'Woodstock took place', value: 1969},
  {name: 'the first pocket calculator went on sale', value: 1971},
  {name: 'the Watergate scandal broke', value: 1972},
  {name: 'the first mobile phone call was made', value: 1973},
  {name: 'the Sydney Opera House opened', value: 1973},
  {name: 'Nixon resigned as US president', value: 1974},
  {name: 'the Vietnam War ended', value: 1975},
  {name: 'Microsoft was founded', value: 1975},
  {name: 'Apple was founded', value: 1976},
  {name: 'the first Star Wars film premiered', value: 1977},
  {name: 'the first test-tube baby was born', value: 1978},
  {name: 'Margaret Thatcher became UK prime minister', value: 1979},
  {name: 'smallpox was declared eradicated', value: 1980},
  {name: 'John Lennon was shot', value: 1980},
  {name: 'MTV started broadcasting', value: 1981},
  {name: 'the IBM PC was launched', value: 1981},
  {name: 'the first space shuttle was launched', value: 1981},
  {name: 'the first CD went on sale', value: 1982},
  {name: 'the Macintosh was introduced', value: 1984},
  {name: 'Live Aid was broadcast worldwide', value: 1985},
  {name: 'the Chernobyl disaster occurred', value: 1986},
  {name: 'the Challenger space shuttle exploded', value: 1986},
  {name: 'the Berlin Wall fell', value: 1989},
  {name: 'the World Wide Web was invented', value: 1989},
  {name: 'Nelson Mandela was released from prison', value: 1990},
  {name: 'the Hubble Space Telescope was launched', value: 1990},
  {name: 'the Soviet Union collapsed', value: 1991},
  {
    name: 'the European Union was established',
    value: 1993
  },  // Maastricht Treaty in force
  {name: 'Nelson Mandela became president of South Africa', value: 1994},
  {name: 'the Channel Tunnel opened', value: 1994},
  {name: 'Amazon was founded', value: 1994},
  {name: 'Dolly the sheep was cloned', value: 1996},
  {name: 'Hong Kong was returned to China', value: 1997},
  {name: 'Google was founded', value: 1998},
  {name: 'the euro was introduced', value: 1999},
  {name: 'the September 11 attacks occurred', value: 2001},
  {name: 'the Indian Ocean tsunami struck', value: 2004},
  {name: 'the global financial crisis erupted', value: 2008},
  {name: 'Barack Obama became US president', value: 2009},
  {name: 'the Arab Spring began', value: 2010},
  {name: 'the Fukushima nuclear disaster occurred', value: 2011},
  {name: 'the Higgs boson was discovered', value: 2012},
  {name: 'gravitational waves were first detected', value: 2015},
  {name: 'the UK voted for Brexit', value: 2016},
  {name: 'the first image of a black hole was published', value: 2019},
  {name: 'the COVID-19 pandemic began', value: 2020},
  {name: 'ChatGPT was released', value: 2022},
];
