import {type Difficulty} from './difficulty.js';

export interface Painting {
  title: string;
  artist: string;
  year: number;  // Conventional completion year; for works painted over a
                 // range, the commonly cited end year
  difficulty: Difficulty;
}

export const paintings: Painting[] = [
  {
    title: 'The Arnolfini Portrait',
    artist: 'Jan van Eyck',
    year: 1434,
    difficulty: 'hard',
  },
  {
    title: 'Primavera',
    artist: 'Sandro Botticelli',
    year: 1482,
    difficulty: 'medium',
  },
  {
    title: 'The Birth of Venus',
    artist: 'Sandro Botticelli',
    year: 1486,
    difficulty: 'easy',
  },
  {
    title: 'The Last Supper',
    artist: 'Leonardo da Vinci',
    year: 1498,
    difficulty: 'easy',
  },
  {
    title: 'The Garden of Earthly Delights',
    artist: 'Hieronymus Bosch',
    year: 1510,
    difficulty: 'hard',
  },
  {
    title: 'The School of Athens',
    artist: 'Raphael',
    year: 1511,
    difficulty: 'medium',
  },
  {
    title: 'The Creation of Adam (Sistine Chapel)',
    artist: 'Michelangelo',
    year: 1512,
    difficulty: 'easy',
  },
  {
    title: 'Sistine Madonna',
    artist: 'Raphael',
    year: 1512,
    difficulty: 'medium',
  },
  {
    title: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: 1517,
    difficulty: 'easy',
  },
  {
    title: 'The Assumption of the Virgin',
    artist: 'Titian',
    year: 1518,
    difficulty: 'hard',
  },
  {
    title: 'The Ambassadors',
    artist: 'Hans Holbein the Younger',
    year: 1533,
    difficulty: 'hard',
  },
  {
    title: 'Venus of Urbino',
    artist: 'Titian',
    year: 1538,
    difficulty: 'hard',
  },
  {
    title: 'Netherlandish Proverbs',
    artist: 'Pieter Bruegel the Elder',
    year: 1559,
    difficulty: 'hard',
  },
  {
    title: 'The Tower of Babel',
    artist: 'Pieter Bruegel the Elder',
    year: 1563,
    difficulty: 'medium',
  },
  {
    title: 'Hunters in the Snow',
    artist: 'Pieter Bruegel the Elder',
    year: 1565,
    difficulty: 'hard',
  },
  {
    title: 'The Burial of the Count of Orgaz',
    artist: 'El Greco',
    year: 1588,
    difficulty: 'hard',
  },
  {
    title: 'The Calling of Saint Matthew',
    artist: 'Caravaggio',
    year: 1600,
    difficulty: 'medium',
  },
  {
    title: 'The Supper at Emmaus',
    artist: 'Caravaggio',
    year: 1601,
    difficulty: 'hard',
  },
  {
    title: 'The Elevation of the Cross',
    artist: 'Peter Paul Rubens',
    year: 1611,
    difficulty: 'medium',
  },
  {
    title: 'Judith Slaying Holofernes',
    artist: 'Artemisia Gentileschi',
    year: 1613,
    difficulty: 'hard',
  },
  {
    title: 'The Anatomy Lesson of Dr Nicolaes Tulp',
    artist: 'Rembrandt',
    year: 1632,
    difficulty: 'medium',
  },
  {
    title: 'The Night Watch',
    artist: 'Rembrandt',
    year: 1642,
    difficulty: 'easy',
  },
  {
    title: 'Las Meninas',
    artist: 'Diego Velázquez',
    year: 1656,
    difficulty: 'medium',
  },
  {
    title: 'The Milkmaid',
    artist: 'Johannes Vermeer',
    year: 1658,
    difficulty: 'easy',
  },
  {
    title: 'View of Delft',
    artist: 'Johannes Vermeer',
    year: 1661,
    difficulty: 'medium',
  },
  {
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: 1665,
    difficulty: 'easy',
  },
  {
    title: 'Self-Portrait with Two Circles',
    artist: 'Rembrandt',
    year: 1669,
    difficulty: 'medium',
  },
  {
    title: 'The Naked Maja',
    artist: 'Francisco Goya',
    year: 1800,
    difficulty: 'medium',
  },
  {
    title: 'Napoleon Crossing the Alps',
    artist: 'Jacques-Louis David',
    year: 1801,
    difficulty: 'hard',
  },
  {
    title: 'The Colossus',
    artist: 'Francisco Goya',
    year: 1812,
    difficulty: 'medium',
  },
  {
    title: 'The Third of May 1808',
    artist: 'Francisco Goya',
    year: 1814,
    difficulty: 'medium',
  },
  {
    title: 'Wanderer above the Sea of Fog',
    artist: 'Caspar David Friedrich',
    year: 1818,
    difficulty: 'easy',
  },
  {
    title: 'Saturn Devouring His Son',
    artist: 'Francisco Goya',
    year: 1823,
    difficulty: 'medium',
  },
  {
    title: 'Liberty Leading the People',
    artist: 'Eugène Delacroix',
    year: 1830,
    difficulty: 'medium',
  },
  {
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    year: 1831,
    difficulty: 'easy',
  },
  {
    title: 'The Fighting Temeraire',
    artist: 'J. M. W. Turner',
    year: 1839,
    difficulty: 'medium',
  },
  {
    title: 'Rain, Steam and Speed',
    artist: 'J. M. W. Turner',
    year: 1844,
    difficulty: 'hard',
  },
  {
    title: 'The Gleaners',
    artist: 'Jean-François Millet',
    year: 1857,
    difficulty: 'hard',
  },
  {
    title: 'The Angelus',
    artist: 'Jean-François Millet',
    year: 1859,
    difficulty: 'hard',
  },
  {
    title: 'Olympia',
    artist: 'Édouard Manet',
    year: 1863,
    difficulty: 'medium',
  },
  {
    title: 'Luncheon on the Grass',
    artist: 'Édouard Manet',
    year: 1863,
    difficulty: 'medium',
  },
  {
    title: 'The Origin of the World',
    artist: 'Gustave Courbet',
    year: 1866,
    difficulty: 'hard',
  },
  {
    title: 'Whistler\'s Mother',
    artist: 'James McNeill Whistler',
    year: 1871,
    difficulty: 'hard',
  },
  {
    title: 'Impression, Sunrise',
    artist: 'Claude Monet',
    year: 1872,
    difficulty: 'medium',
  },
  {
    title: 'The Dance Class',
    artist: 'Edgar Degas',
    year: 1874,
    difficulty: 'medium',
  },
  {
    title: 'Bal du moulin de la Galette',
    artist: 'Pierre-Auguste Renoir',
    year: 1876,
    difficulty: 'medium',
  },
  {
    title: 'Luncheon of the Boating Party',
    artist: 'Pierre-Auguste Renoir',
    year: 1881,
    difficulty: 'medium',
  },
  {
    title: 'A Bar at the Folies-Bergère',
    artist: 'Édouard Manet',
    year: 1882,
    difficulty: 'hard',
  },
  {
    title: 'The Potato Eaters',
    artist: 'Vincent van Gogh',
    year: 1885,
    difficulty: 'easy',
  },
  {
    title: 'A Sunday Afternoon on the Island of La Grande Jatte',
    artist: 'Georges Seurat',
    year: 1886,
    difficulty: 'hard',
  },
  {
    title: 'Vase with Sunflowers',
    artist: 'Vincent van Gogh',
    year: 1888,
    difficulty: 'easy',
  },
  {
    title: 'Café Terrace at Night',
    artist: 'Vincent van Gogh',
    year: 1888,
    difficulty: 'medium',
  },
  {
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: 1889,
    difficulty: 'easy',
  },
  {
    title: 'Wheatfield with Crows',
    artist: 'Vincent van Gogh',
    year: 1890,
    difficulty: 'medium',
  },
  {
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: 1893,
    difficulty: 'easy',
  },
  {
    title: 'At the Moulin Rouge',
    artist: 'Henri de Toulouse-Lautrec',
    year: 1895,
    difficulty: 'medium',
  },
  {
    title: 'The Card Players',
    artist: 'Paul Cézanne',
    year: 1895,
    difficulty: 'medium',
  },
  {
    title: 'Boulevard Montmartre at Night',
    artist: 'Camille Pissarro',
    year: 1897,
    difficulty: 'hard',
  },
  {
    title: 'The Sleeping Gypsy',
    artist: 'Henri Rousseau',
    year: 1897,
    difficulty: 'hard',
  },
  {
    title: 'Where Do We Come From? What Are We? Where Are We Going?',
    artist: 'Paul Gauguin',
    year: 1898,
    difficulty: 'hard',
  },
  {
    title: 'Water Lilies (first series)',
    artist: 'Claude Monet',
    year: 1900,
    difficulty: 'easy',
  },
  {
    title: 'The Old Guitarist',
    artist: 'Pablo Picasso',
    year: 1904,
    difficulty: 'easy',
  },
  {
    title: 'Le bonheur de vivre',
    artist: 'Henri Matisse',
    year: 1906,
    difficulty: 'hard',
  },
  {
    title: 'Les Demoiselles d\'Avignon',
    artist: 'Pablo Picasso',
    year: 1907,
    difficulty: 'easy',
  },
  {
    title: 'Portrait of Adele Bloch-Bauer I',
    artist: 'Gustav Klimt',
    year: 1907,
    difficulty: 'medium',
  },
  {
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    year: 1908,
    difficulty: 'easy',
  },
  {
    title: 'The Dance',
    artist: 'Henri Matisse',
    year: 1910,
    difficulty: 'medium',
  },
  {
    title: 'I and the Village',
    artist: 'Marc Chagall',
    year: 1911,
    difficulty: 'medium',
  },
  {
    title: 'Nude Descending a Staircase, No. 2',
    artist: 'Marcel Duchamp',
    year: 1912,
    difficulty: 'hard',
  },
  {
    title: 'Composition VII',
    artist: 'Wassily Kandinsky',
    year: 1913,
    difficulty: 'medium',
  },
  {
    title: 'Black Square',
    artist: 'Kazimir Malevich',
    year: 1915,
    difficulty: 'hard',
  },
  {
    title: 'The Treachery of Images (Ceci n\'est pas une pipe)',
    artist: 'René Magritte',
    year: 1929,
    difficulty: 'easy',
  },
  {
    title: 'The Great Masturbator',
    artist: 'Salvador Dalí',
    year: 1929,
    difficulty: 'hard',
  },
  {
    title: 'American Gothic',
    artist: 'Grant Wood',
    year: 1930,
    difficulty: 'hard',
  },
  {
    title: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    year: 1931,
    difficulty: 'easy',
  },
  {
    title: 'Guernica',
    artist: 'Pablo Picasso',
    year: 1937,
    difficulty: 'easy',
  },
  {
    title: 'Portrait of Dora Maar',
    artist: 'Pablo Picasso',
    year: 1937,
    difficulty: 'medium',
  },
  {
    title: 'The Two Fridas',
    artist: 'Frida Kahlo',
    year: 1939,
    difficulty: 'medium',
  },
  {
    title: 'Self-Portrait with Thorn Necklace and Hummingbird',
    artist: 'Frida Kahlo',
    year: 1940,
    difficulty: 'easy',
  },
  {
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: 1942,
    difficulty: 'easy',
  },
  {
    title: 'Broadway Boogie Woogie',
    artist: 'Piet Mondrian',
    year: 1943,
    difficulty: 'medium',
  },
  {
    title: 'The Broken Column',
    artist: 'Frida Kahlo',
    year: 1944,
    difficulty: 'medium',
  },
  {
    title: 'No. 5, 1948',
    artist: 'Jackson Pollock',
    year: 1948,
    difficulty: 'easy',
  },
  {
    title: 'Christina\'s World',
    artist: 'Andrew Wyeth',
    year: 1948,
    difficulty: 'hard',
  },
  {
    title: 'Campbell\'s Soup Cans',
    artist: 'Andy Warhol',
    year: 1962,
    difficulty: 'easy',
  },
  {
    title: 'Marilyn Diptych',
    artist: 'Andy Warhol',
    year: 1962,
    difficulty: 'easy',
  },
  {
    title: 'Whaam!',
    artist: 'Roy Lichtenstein',
    year: 1963,
    difficulty: 'medium',
  },
  {
    title: 'The Son of Man',
    artist: 'René Magritte',
    year: 1964,
    difficulty: 'medium',
  },
  {
    title: 'A Bigger Splash',
    artist: 'David Hockney',
    year: 1967,
    difficulty: 'medium',
  },
  {
    title: 'Portrait of an Artist (Pool with Two Figures)',
    artist: 'David Hockney',
    year: 1972,
    difficulty: 'hard',
  },
  {
    title: 'Untitled (Skull)',
    artist: 'Jean-Michel Basquiat',
    year: 1981,
    difficulty: 'hard',
  },
  {
    title: 'Kerze',
    artist: 'Gerhard Richter',
    year: 1982,
    difficulty: 'medium',
  },
  {
    title: 'Betty',
    artist: 'Gerhard Richter',
    year: 1988,
    difficulty: 'medium',
  },
  {
    title: 'The Death of Pablo Escobar',
    artist: 'Fernando Botero',
    year: 1999,
    difficulty: 'medium',
  },
  {
    title: 'Balloon Girl (There Is Always Hope)',
    artist: 'Banksy',
    year: 2002,
    difficulty: 'easy',
  },
];
