import {type Difficulty} from './difficulty.js';

export interface Painting {
  title: string;
  artist: string;
  year: number;  // Conventional completion year; for works painted over a
                 // range, the commonly cited end year
  id: number;
  difficulty: Difficulty;
  link: string;
}

export const paintings: Painting[] = [
  {
    title: 'The Arnolfini Portrait',
    artist: 'Jan van Eyck',
    year: 1434,
    id: 5000,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Arnolfini_Portrait',
  },
  {
    title: 'Primavera',
    artist: 'Sandro Botticelli',
    year: 1482,
    id: 5001,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Primavera_(Botticelli)',
  },
  {
    title: 'The Birth of Venus',
    artist: 'Sandro Botticelli',
    year: 1486,
    id: 5002,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Birth_of_Venus',
  },
  {
    title: 'The Last Supper',
    artist: 'Leonardo da Vinci',
    year: 1498,
    id: 5003,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Last_Supper_(Leonardo)',
  },
  {
    title: 'The Garden of Earthly Delights',
    artist: 'Hieronymus Bosch',
    year: 1510,
    id: 5004,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Garden_of_Earthly_Delights',
  },
  {
    title: 'The School of Athens',
    artist: 'Raphael',
    year: 1511,
    id: 5005,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_School_of_Athens',
  },
  {
    title: 'The Creation of Adam (Sistine Chapel)',
    artist: 'Michelangelo',
    year: 1512,
    id: 5006,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Creation_of_Adam',
  },
  {
    title: 'Sistine Madonna',
    artist: 'Raphael',
    year: 1512,
    id: 5007,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Sistine_Madonna',
  },
  {
    title: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: 1517,
    id: 5008,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Mona_Lisa',
  },
  {
    title: 'The Assumption of the Virgin',
    artist: 'Titian',
    year: 1518,
    id: 5009,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Assumption_of_the_Virgin_(Titian)',
  },
  {
    title: 'The Ambassadors',
    artist: 'Hans Holbein the Younger',
    year: 1533,
    id: 5010,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Ambassadors_(Holbein)',
  },
  {
    title: 'Venus of Urbino',
    artist: 'Titian',
    year: 1538,
    id: 5011,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Venus_of_Urbino',
  },
  {
    title: 'Netherlandish Proverbs',
    artist: 'Pieter Bruegel the Elder',
    year: 1559,
    id: 5012,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Netherlandish_Proverbs',
  },
  {
    title: 'The Tower of Babel',
    artist: 'Pieter Bruegel the Elder',
    year: 1563,
    id: 5013,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Tower_of_Babel_(Bruegel)',
  },
  {
    title: 'Hunters in the Snow',
    artist: 'Pieter Bruegel the Elder',
    year: 1565,
    id: 5014,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Hunters_in_the_Snow',
  },
  {
    title: 'The Burial of the Count of Orgaz',
    artist: 'El Greco',
    year: 1588,
    id: 5015,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Burial_of_the_Count_of_Orgaz',
  },
  {
    title: 'The Calling of Saint Matthew',
    artist: 'Caravaggio',
    year: 1600,
    id: 5016,
    difficulty: 'medium',
    link:
        'https://en.wikipedia.org/wiki/The_Calling_of_St_Matthew_(Caravaggio)',
  },
  {
    title: 'The Supper at Emmaus',
    artist: 'Caravaggio',
    year: 1601,
    id: 5017,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Supper_at_Emmaus_(Caravaggio,_London)',
  },
  {
    title: 'The Elevation of the Cross',
    artist: 'Peter Paul Rubens',
    year: 1611,
    id: 5018,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Elevation_of_the_Cross_(Rubens)',
  },
  {
    title: 'Judith Slaying Holofernes',
    artist: 'Artemisia Gentileschi',
    year: 1613,
    id: 5019,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/Judith_Slaying_Holofernes_(Artemisia_Gentileschi)',
  },
  {
    title: 'The Anatomy Lesson of Dr Nicolaes Tulp',
    artist: 'Rembrandt',
    year: 1632,
    id: 5020,
    difficulty: 'medium',
    link:
        'https://en.wikipedia.org/wiki/The_Anatomy_Lesson_of_Dr._Nicolaes_Tulp',
  },
  {
    title: 'The Night Watch',
    artist: 'Rembrandt',
    year: 1642,
    id: 5021,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Night_Watch',
  },
  {
    title: 'Las Meninas',
    artist: 'Diego Velázquez',
    year: 1656,
    id: 5022,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Las_Meninas',
  },
  {
    title: 'The Milkmaid',
    artist: 'Johannes Vermeer',
    year: 1658,
    id: 5023,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)',
  },
  {
    title: 'View of Delft',
    artist: 'Johannes Vermeer',
    year: 1661,
    id: 5024,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/View_of_Delft',
  },
  {
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: 1665,
    id: 5025,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring',
  },
  {
    title: 'Self-Portrait with Two Circles',
    artist: 'Rembrandt',
    year: 1669,
    id: 5026,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Self-Portrait_with_Two_Circles',
  },
  {
    title: 'The Naked Maja',
    artist: 'Francisco Goya',
    year: 1800,
    id: 5027,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/La_maja_desnuda',
  },
  {
    title: 'Napoleon Crossing the Alps',
    artist: 'Jacques-Louis David',
    year: 1801,
    id: 5028,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Napoleon_Crossing_the_Alps',
  },
  {
    title: 'The Colossus',
    artist: 'Francisco Goya',
    year: 1812,
    id: 5029,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Colossus_(painting)',
  },
  {
    title: 'The Third of May 1808',
    artist: 'Francisco Goya',
    year: 1814,
    id: 5030,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Third_of_May_1808',
  },
  {
    title: 'Wanderer above the Sea of Fog',
    artist: 'Caspar David Friedrich',
    year: 1818,
    id: 5031,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Wanderer_above_the_Sea_of_Fog',
  },
  {
    title: 'Saturn Devouring His Son',
    artist: 'Francisco Goya',
    year: 1823,
    id: 5032,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Saturn_Devouring_His_Son',
  },
  {
    title: 'Liberty Leading the People',
    artist: 'Eugène Delacroix',
    year: 1830,
    id: 5033,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Liberty_Leading_the_People',
  },
  {
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    year: 1831,
    id: 5034,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa',
  },
  {
    title: 'The Fighting Temeraire',
    artist: 'J. M. W. Turner',
    year: 1839,
    id: 5035,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Fighting_Temeraire',
  },
  {
    title: 'Rain, Steam and Speed',
    artist: 'J. M. W. Turner',
    year: 1844,
    id: 5036,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/Rain,_Steam_and_Speed_–_The_Great_Western_Railway',
  },
  {
    title: 'The Gleaners',
    artist: 'Jean-François Millet',
    year: 1857,
    id: 5037,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Gleaners',
  },
  {
    title: 'The Angelus',
    artist: 'Jean-François Millet',
    year: 1859,
    id: 5038,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Angelus_(painting)',
  },
  {
    title: 'Olympia',
    artist: 'Édouard Manet',
    year: 1863,
    id: 5039,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Olympia_(Manet)',
  },
  {
    title: 'Luncheon on the Grass',
    artist: 'Édouard Manet',
    year: 1863,
    id: 5040,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Le_Déjeuner_sur_l%27herbe',
  },
  {
    title: 'The Origin of the World',
    artist: 'Gustave Courbet',
    year: 1866,
    id: 5041,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/L%27Origine_du_monde',
  },
  {
    title: 'Whistler\'s Mother',
    artist: 'James McNeill Whistler',
    year: 1871,
    id: 5042,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Whistler%27s_Mother',
  },
  {
    title: 'Impression, Sunrise',
    artist: 'Claude Monet',
    year: 1872,
    id: 5043,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Impression,_Sunrise',
  },
  {
    title: 'The Dance Class',
    artist: 'Edgar Degas',
    year: 1874,
    id: 5044,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Dance_Class_(Degas)',
  },
  {
    title: 'Bal du moulin de la Galette',
    artist: 'Pierre-Auguste Renoir',
    year: 1876,
    id: 5045,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Bal_du_moulin_de_la_Galette',
  },
  {
    title: 'Luncheon of the Boating Party',
    artist: 'Pierre-Auguste Renoir',
    year: 1881,
    id: 5046,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Luncheon_of_the_Boating_Party',
  },
  {
    title: 'A Bar at the Folies-Bergère',
    artist: 'Édouard Manet',
    year: 1882,
    id: 5047,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/A_Bar_at_the_Folies-Bergère',
  },
  {
    title: 'The Potato Eaters',
    artist: 'Vincent van Gogh',
    year: 1885,
    id: 5048,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Potato_Eaters',
  },
  {
    title: 'A Sunday Afternoon on the Island of La Grande Jatte',
    artist: 'Georges Seurat',
    year: 1886,
    id: 5049,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte',
  },
  {
    title: 'Vase with Sunflowers',
    artist: 'Vincent van Gogh',
    year: 1888,
    id: 5050,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Sunflowers_(Van_Gogh_series)',
  },
  {
    title: 'Café Terrace at Night',
    artist: 'Vincent van Gogh',
    year: 1888,
    id: 5051,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Café_Terrace_at_Night',
  },
  {
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: 1889,
    id: 5052,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Starry_Night',
  },
  {
    title: 'Wheatfield with Crows',
    artist: 'Vincent van Gogh',
    year: 1890,
    id: 5053,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Wheatfield_with_Crows',
  },
  {
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: 1893,
    id: 5054,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Scream',
  },
  {
    title: 'At the Moulin Rouge',
    artist: 'Henri de Toulouse-Lautrec',
    year: 1895,
    id: 5055,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/At_the_Moulin_Rouge',
  },
  {
    title: 'The Card Players',
    artist: 'Paul Cézanne',
    year: 1895,
    id: 5056,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Card_Players',
  },
  {
    title: 'Boulevard Montmartre at Night',
    artist: 'Camille Pissarro',
    year: 1897,
    id: 5057,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Boulevard_Montmartre_at_Night',
  },
  {
    title: 'The Sleeping Gypsy',
    artist: 'Henri Rousseau',
    year: 1897,
    id: 5058,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Sleeping_Gypsy',
  },
  {
    title: 'Where Do We Come From? What Are We? Where Are We Going?',
    artist: 'Paul Gauguin',
    year: 1898,
    id: 5059,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/Where_Do_We_Come_From%3F_What_Are_We%3F_Where_Are_We_Going%3F',
  },
  {
    title: 'Water Lilies (first series)',
    artist: 'Claude Monet',
    year: 1900,
    id: 5060,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Water_Lilies_(Monet_series)',
  },
  {
    title: 'The Old Guitarist',
    artist: 'Pablo Picasso',
    year: 1904,
    id: 5061,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Old_Guitarist',
  },
  {
    title: 'Le bonheur de vivre',
    artist: 'Henri Matisse',
    year: 1906,
    id: 5062,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Le_Bonheur_de_vivre',
  },
  {
    title: 'Les Demoiselles d\'Avignon',
    artist: 'Pablo Picasso',
    year: 1907,
    id: 5063,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Les_Demoiselles_d%27Avignon',
  },
  {
    title: 'Portrait of Adele Bloch-Bauer I',
    artist: 'Gustav Klimt',
    year: 1907,
    id: 5064,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Portrait_of_Adele_Bloch-Bauer_I',
  },
  {
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    year: 1908,
    id: 5065,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Kiss_(Klimt)',
  },
  {
    title: 'The Dance',
    artist: 'Henri Matisse',
    year: 1910,
    id: 5066,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Dance_(Matisse)',
  },
  {
    title: 'I and the Village',
    artist: 'Marc Chagall',
    year: 1911,
    id: 5067,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/I_and_the_Village',
  },
  {
    title: 'Nude Descending a Staircase, No. 2',
    artist: 'Marcel Duchamp',
    year: 1912,
    id: 5068,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Nude_Descending_a_Staircase,_No._2',
  },
  {
    title: 'Composition VII',
    artist: 'Wassily Kandinsky',
    year: 1913,
    id: 5069,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Composition_VII',
  },
  {
    title: 'Black Square',
    artist: 'Kazimir Malevich',
    year: 1915,
    id: 5070,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Black_Square_(painting)',
  },
  {
    title: 'The Treachery of Images (Ceci n\'est pas une pipe)',
    artist: 'René Magritte',
    year: 1929,
    id: 5071,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Treachery_of_Images',
  },
  {
    title: 'The Great Masturbator',
    artist: 'Salvador Dalí',
    year: 1929,
    id: 5072,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Great_Masturbator',
  },
  {
    title: 'American Gothic',
    artist: 'Grant Wood',
    year: 1930,
    id: 5073,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/American_Gothic',
  },
  {
    title: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    year: 1931,
    id: 5074,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/The_Persistence_of_Memory',
  },
  {
    title: 'Guernica',
    artist: 'Pablo Picasso',
    year: 1937,
    id: 5075,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Guernica_(Picasso)',
  },
  {
    title: 'Portrait of Dora Maar',
    artist: 'Pablo Picasso',
    year: 1937,
    id: 5076,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Portrait_of_Dora_Maar',
  },
  {
    title: 'The Two Fridas',
    artist: 'Frida Kahlo',
    year: 1939,
    id: 5077,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Two_Fridas',
  },
  {
    title: 'Self-Portrait with Thorn Necklace and Hummingbird',
    artist: 'Frida Kahlo',
    year: 1940,
    id: 5078,
    difficulty: 'easy',
    link:
        'https://en.wikipedia.org/wiki/Self-Portrait_with_Thorn_Necklace_and_Hummingbird',
  },
  {
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: 1942,
    id: 5079,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Nighthawks_(painting)',
  },
  {
    title: 'Broadway Boogie Woogie',
    artist: 'Piet Mondrian',
    year: 1943,
    id: 5080,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Broadway_Boogie_Woogie',
  },
  {
    title: 'The Broken Column',
    artist: 'Frida Kahlo',
    year: 1944,
    id: 5081,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Broken_Column',
  },
  {
    title: 'No. 5, 1948',
    artist: 'Jackson Pollock',
    year: 1948,
    id: 5082,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/No._5,_1948',
  },
  {
    title: 'Christina\'s World',
    artist: 'Andrew Wyeth',
    year: 1948,
    id: 5083,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Christina%27s_World',
  },
  {
    title: 'Campbell\'s Soup Cans',
    artist: 'Andy Warhol',
    year: 1962,
    id: 5084,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Campbell%27s_Soup_Cans',
  },
  {
    title: 'Marilyn Diptych',
    artist: 'Andy Warhol',
    year: 1962,
    id: 5085,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Marilyn_Diptych',
  },
  {
    title: 'Whaam!',
    artist: 'Roy Lichtenstein',
    year: 1963,
    id: 5086,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Whaam!',
  },
  {
    title: 'The Son of Man',
    artist: 'René Magritte',
    year: 1964,
    id: 5087,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Son_of_Man',
  },
  {
    title: 'A Bigger Splash',
    artist: 'David Hockney',
    year: 1967,
    id: 5088,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/A_Bigger_Splash',
  },
  {
    title: 'Portrait of an Artist (Pool with Two Figures)',
    artist: 'David Hockney',
    year: 1972,
    id: 5089,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/Portrait_of_an_Artist_(Pool_with_Two_Figures)',
  },
  {
    title: 'Untitled (Skull)',
    artist: 'Jean-Michel Basquiat',
    year: 1981,
    id: 5090,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Untitled_(Skull)',
  },
  {
    title: 'Kerze',
    artist: 'Gerhard Richter',
    year: 1982,
    id: 5091,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Candle_(Richter)',
  },
  {
    title: 'Betty',
    artist: 'Gerhard Richter',
    year: 1988,
    id: 5092,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Betty_(Richter)',
  },
  {
    title: 'The Death of Pablo Escobar',
    artist: 'Fernando Botero',
    year: 1999,
    id: 5093,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Death_of_Pablo_Escobar',
  },
  {
    title: 'Balloon Girl (There Is Always Hope)',
    artist: 'Banksy',
    year: 2002,
    id: 5094,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Girl_with_Balloon',
  },
];
