import {type Difficulty} from './difficulty.js';

export interface Painting {
  title: string;
  artist: string;
  year: number;  // Conventional completion year; for works painted over a
                 // range, the commonly cited end year
  id: number;
  difficulty: Difficulty;
}

export const paintings: Painting[] = [
  {
    title: 'The Arnolfini Portrait',
    artist: 'Jan van Eyck',
    year: 1434,
    id: 5000,
    difficulty: 'hard',
  },
  {
    title: 'Primavera',
    artist: 'Sandro Botticelli',
    year: 1482,
    id: 5001,
    difficulty: 'medium',
  },
  {
    title: 'The Birth of Venus',
    artist: 'Sandro Botticelli',
    year: 1486,
    id: 5002,
    difficulty: 'easy',
  },
  {
    title: 'The Last Supper',
    artist: 'Leonardo da Vinci',
    year: 1498,
    id: 5003,
    difficulty: 'easy',
  },
  {
    title: 'The Garden of Earthly Delights',
    artist: 'Hieronymus Bosch',
    year: 1510,
    id: 5004,
    difficulty: 'hard',
  },
  {
    title: 'The School of Athens',
    artist: 'Raphael',
    year: 1511,
    id: 5005,
    difficulty: 'medium',
  },
  {
    title: 'The Creation of Adam (Sistine Chapel)',
    artist: 'Michelangelo',
    year: 1512,
    id: 5006,
    difficulty: 'easy',
  },
  {
    title: 'Sistine Madonna',
    artist: 'Raphael',
    year: 1512,
    id: 5007,
    difficulty: 'medium',
  },
  {
    title: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: 1517,
    id: 5008,
    difficulty: 'easy',
  },
  {
    title: 'The Assumption of the Virgin',
    artist: 'Titian',
    year: 1518,
    id: 5009,
    difficulty: 'hard',
  },
  {
    title: 'The Ambassadors',
    artist: 'Hans Holbein the Younger',
    year: 1533,
    id: 5010,
    difficulty: 'hard',
  },
  {
    title: 'Venus of Urbino',
    artist: 'Titian',
    year: 1538,
    id: 5011,
    difficulty: 'hard',
  },
  {
    title: 'Netherlandish Proverbs',
    artist: 'Pieter Bruegel the Elder',
    year: 1559,
    id: 5012,
    difficulty: 'hard',
  },
  {
    title: 'The Tower of Babel',
    artist: 'Pieter Bruegel the Elder',
    year: 1563,
    id: 5013,
    difficulty: 'medium',
  },
  {
    title: 'Hunters in the Snow',
    artist: 'Pieter Bruegel the Elder',
    year: 1565,
    id: 5014,
    difficulty: 'hard',
  },
  {
    title: 'The Burial of the Count of Orgaz',
    artist: 'El Greco',
    year: 1588,
    id: 5015,
    difficulty: 'hard',
  },
  {
    title: 'The Calling of Saint Matthew',
    artist: 'Caravaggio',
    year: 1600,
    id: 5016,
    difficulty: 'medium',
  },
  {
    title: 'The Supper at Emmaus',
    artist: 'Caravaggio',
    year: 1601,
    id: 5017,
    difficulty: 'hard',
  },
  {
    title: 'The Elevation of the Cross',
    artist: 'Peter Paul Rubens',
    year: 1611,
    id: 5018,
    difficulty: 'medium',
  },
  {
    title: 'Judith Slaying Holofernes',
    artist: 'Artemisia Gentileschi',
    year: 1613,
    id: 5019,
    difficulty: 'hard',
  },
  {
    title: 'The Anatomy Lesson of Dr Nicolaes Tulp',
    artist: 'Rembrandt',
    year: 1632,
    id: 5020,
    difficulty: 'medium',
  },
  {
    title: 'The Night Watch',
    artist: 'Rembrandt',
    year: 1642,
    id: 5021,
    difficulty: 'easy',
  },
  {
    title: 'Las Meninas',
    artist: 'Diego Velázquez',
    year: 1656,
    id: 5022,
    difficulty: 'medium',
  },
  {
    title: 'The Milkmaid',
    artist: 'Johannes Vermeer',
    year: 1658,
    id: 5023,
    difficulty: 'easy',
  },
  {
    title: 'View of Delft',
    artist: 'Johannes Vermeer',
    year: 1661,
    id: 5024,
    difficulty: 'medium',
  },
  {
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: 1665,
    id: 5025,
    difficulty: 'easy',
  },
  {
    title: 'Self-Portrait with Two Circles',
    artist: 'Rembrandt',
    year: 1669,
    id: 5026,
    difficulty: 'medium',
  },
  {
    title: 'The Naked Maja',
    artist: 'Francisco Goya',
    year: 1800,
    id: 5027,
    difficulty: 'medium',
  },
  {
    title: 'Napoleon Crossing the Alps',
    artist: 'Jacques-Louis David',
    year: 1801,
    id: 5028,
    difficulty: 'hard',
  },
  {
    title: 'The Colossus',
    artist: 'Francisco Goya',
    year: 1812,
    id: 5029,
    difficulty: 'medium',
  },
  {
    title: 'The Third of May 1808',
    artist: 'Francisco Goya',
    year: 1814,
    id: 5030,
    difficulty: 'medium',
  },
  {
    title: 'Wanderer above the Sea of Fog',
    artist: 'Caspar David Friedrich',
    year: 1818,
    id: 5031,
    difficulty: 'easy',
  },
  {
    title: 'Saturn Devouring His Son',
    artist: 'Francisco Goya',
    year: 1823,
    id: 5032,
    difficulty: 'medium',
  },
  {
    title: 'Liberty Leading the People',
    artist: 'Eugène Delacroix',
    year: 1830,
    id: 5033,
    difficulty: 'medium',
  },
  {
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    year: 1831,
    id: 5034,
    difficulty: 'easy',
  },
  {
    title: 'The Fighting Temeraire',
    artist: 'J. M. W. Turner',
    year: 1839,
    id: 5035,
    difficulty: 'medium',
  },
  {
    title: 'Rain, Steam and Speed',
    artist: 'J. M. W. Turner',
    year: 1844,
    id: 5036,
    difficulty: 'hard',
  },
  {
    title: 'The Gleaners',
    artist: 'Jean-François Millet',
    year: 1857,
    id: 5037,
    difficulty: 'hard',
  },
  {
    title: 'The Angelus',
    artist: 'Jean-François Millet',
    year: 1859,
    id: 5038,
    difficulty: 'hard',
  },
  {
    title: 'Olympia',
    artist: 'Édouard Manet',
    year: 1863,
    id: 5039,
    difficulty: 'medium',
  },
  {
    title: 'Luncheon on the Grass',
    artist: 'Édouard Manet',
    year: 1863,
    id: 5040,
    difficulty: 'medium',
  },
  {
    title: 'The Origin of the World',
    artist: 'Gustave Courbet',
    year: 1866,
    id: 5041,
    difficulty: 'hard',
  },
  {
    title: 'Whistler\'s Mother',
    artist: 'James McNeill Whistler',
    year: 1871,
    id: 5042,
    difficulty: 'hard',
  },
  {
    title: 'Impression, Sunrise',
    artist: 'Claude Monet',
    year: 1872,
    id: 5043,
    difficulty: 'medium',
  },
  {
    title: 'The Dance Class',
    artist: 'Edgar Degas',
    year: 1874,
    id: 5044,
    difficulty: 'medium',
  },
  {
    title: 'Bal du moulin de la Galette',
    artist: 'Pierre-Auguste Renoir',
    year: 1876,
    id: 5045,
    difficulty: 'medium',
  },
  {
    title: 'Luncheon of the Boating Party',
    artist: 'Pierre-Auguste Renoir',
    year: 1881,
    id: 5046,
    difficulty: 'medium',
  },
  {
    title: 'A Bar at the Folies-Bergère',
    artist: 'Édouard Manet',
    year: 1882,
    id: 5047,
    difficulty: 'hard',
  },
  {
    title: 'The Potato Eaters',
    artist: 'Vincent van Gogh',
    year: 1885,
    id: 5048,
    difficulty: 'easy',
  },
  {
    title: 'A Sunday Afternoon on the Island of La Grande Jatte',
    artist: 'Georges Seurat',
    year: 1886,
    id: 5049,
    difficulty: 'hard',
  },
  {
    title: 'Vase with Sunflowers',
    artist: 'Vincent van Gogh',
    year: 1888,
    id: 5050,
    difficulty: 'easy',
  },
  {
    title: 'Café Terrace at Night',
    artist: 'Vincent van Gogh',
    year: 1888,
    id: 5051,
    difficulty: 'medium',
  },
  {
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: 1889,
    id: 5052,
    difficulty: 'easy',
  },
  {
    title: 'Wheatfield with Crows',
    artist: 'Vincent van Gogh',
    year: 1890,
    id: 5053,
    difficulty: 'medium',
  },
  {
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: 1893,
    id: 5054,
    difficulty: 'easy',
  },
  {
    title: 'At the Moulin Rouge',
    artist: 'Henri de Toulouse-Lautrec',
    year: 1895,
    id: 5055,
    difficulty: 'medium',
  },
  {
    title: 'The Card Players',
    artist: 'Paul Cézanne',
    year: 1895,
    id: 5056,
    difficulty: 'medium',
  },
  {
    title: 'Boulevard Montmartre at Night',
    artist: 'Camille Pissarro',
    year: 1897,
    id: 5057,
    difficulty: 'hard',
  },
  {
    title: 'The Sleeping Gypsy',
    artist: 'Henri Rousseau',
    year: 1897,
    id: 5058,
    difficulty: 'hard',
  },
  {
    title: 'Where Do We Come From? What Are We? Where Are We Going?',
    artist: 'Paul Gauguin',
    year: 1898,
    id: 5059,
    difficulty: 'hard',
  },
  {
    title: 'Water Lilies (first series)',
    artist: 'Claude Monet',
    year: 1900,
    id: 5060,
    difficulty: 'easy',
  },
  {
    title: 'The Old Guitarist',
    artist: 'Pablo Picasso',
    year: 1904,
    id: 5061,
    difficulty: 'easy',
  },
  {
    title: 'Le bonheur de vivre',
    artist: 'Henri Matisse',
    year: 1906,
    id: 5062,
    difficulty: 'hard',
  },
  {
    title: 'Les Demoiselles d\'Avignon',
    artist: 'Pablo Picasso',
    year: 1907,
    id: 5063,
    difficulty: 'easy',
  },
  {
    title: 'Portrait of Adele Bloch-Bauer I',
    artist: 'Gustav Klimt',
    year: 1907,
    id: 5064,
    difficulty: 'medium',
  },
  {
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    year: 1908,
    id: 5065,
    difficulty: 'easy',
  },
  {
    title: 'The Dance',
    artist: 'Henri Matisse',
    year: 1910,
    id: 5066,
    difficulty: 'medium',
  },
  {
    title: 'I and the Village',
    artist: 'Marc Chagall',
    year: 1911,
    id: 5067,
    difficulty: 'medium',
  },
  {
    title: 'Nude Descending a Staircase, No. 2',
    artist: 'Marcel Duchamp',
    year: 1912,
    id: 5068,
    difficulty: 'hard',
  },
  {
    title: 'Composition VII',
    artist: 'Wassily Kandinsky',
    year: 1913,
    id: 5069,
    difficulty: 'medium',
  },
  {
    title: 'Black Square',
    artist: 'Kazimir Malevich',
    year: 1915,
    id: 5070,
    difficulty: 'hard',
  },
  {
    title: 'The Treachery of Images (Ceci n\'est pas une pipe)',
    artist: 'René Magritte',
    year: 1929,
    id: 5071,
    difficulty: 'easy',
  },
  {
    title: 'The Great Masturbator',
    artist: 'Salvador Dalí',
    year: 1929,
    id: 5072,
    difficulty: 'hard',
  },
  {
    title: 'American Gothic',
    artist: 'Grant Wood',
    year: 1930,
    id: 5073,
    difficulty: 'hard',
  },
  {
    title: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    year: 1931,
    id: 5074,
    difficulty: 'easy',
  },
  {
    title: 'Guernica',
    artist: 'Pablo Picasso',
    year: 1937,
    id: 5075,
    difficulty: 'easy',
  },
  {
    title: 'Portrait of Dora Maar',
    artist: 'Pablo Picasso',
    year: 1937,
    id: 5076,
    difficulty: 'medium',
  },
  {
    title: 'The Two Fridas',
    artist: 'Frida Kahlo',
    year: 1939,
    id: 5077,
    difficulty: 'medium',
  },
  {
    title: 'Self-Portrait with Thorn Necklace and Hummingbird',
    artist: 'Frida Kahlo',
    year: 1940,
    id: 5078,
    difficulty: 'easy',
  },
  {
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: 1942,
    id: 5079,
    difficulty: 'easy',
  },
  {
    title: 'Broadway Boogie Woogie',
    artist: 'Piet Mondrian',
    year: 1943,
    id: 5080,
    difficulty: 'medium',
  },
  {
    title: 'The Broken Column',
    artist: 'Frida Kahlo',
    year: 1944,
    id: 5081,
    difficulty: 'medium',
  },
  {
    title: 'No. 5, 1948',
    artist: 'Jackson Pollock',
    year: 1948,
    id: 5082,
    difficulty: 'easy',
  },
  {
    title: 'Christina\'s World',
    artist: 'Andrew Wyeth',
    year: 1948,
    id: 5083,
    difficulty: 'hard',
  },
  {
    title: 'Campbell\'s Soup Cans',
    artist: 'Andy Warhol',
    year: 1962,
    id: 5084,
    difficulty: 'easy',
  },
  {
    title: 'Marilyn Diptych',
    artist: 'Andy Warhol',
    year: 1962,
    id: 5085,
    difficulty: 'easy',
  },
  {
    title: 'Whaam!',
    artist: 'Roy Lichtenstein',
    year: 1963,
    id: 5086,
    difficulty: 'medium',
  },
  {
    title: 'The Son of Man',
    artist: 'René Magritte',
    year: 1964,
    id: 5087,
    difficulty: 'medium',
  },
  {
    title: 'A Bigger Splash',
    artist: 'David Hockney',
    year: 1967,
    id: 5088,
    difficulty: 'medium',
  },
  {
    title: 'Portrait of an Artist (Pool with Two Figures)',
    artist: 'David Hockney',
    year: 1972,
    id: 5089,
    difficulty: 'hard',
  },
  {
    title: 'Untitled (Skull)',
    artist: 'Jean-Michel Basquiat',
    year: 1981,
    id: 5090,
    difficulty: 'hard',
  },
  {
    title: 'Kerze',
    artist: 'Gerhard Richter',
    year: 1982,
    id: 5091,
    difficulty: 'medium',
  },
  {
    title: 'Betty',
    artist: 'Gerhard Richter',
    year: 1988,
    id: 5092,
    difficulty: 'medium',
  },
  {
    title: 'The Death of Pablo Escobar',
    artist: 'Fernando Botero',
    year: 1999,
    id: 5093,
    difficulty: 'medium',
  },
  {
    title: 'Balloon Girl (There Is Always Hope)',
    artist: 'Banksy',
    year: 2002,
    id: 5094,
    difficulty: 'easy',
  },
];
