import {type Difficulty} from './difficulty.js';

export interface Structure {
  name: string;
  country: string;  // Uses an en dash ("A–B") for cross-border structures
  place?: string;   // Country-specific location (city, region); omitted for
                    // city-states and country-wide structures
  year: number;     // Conventional completion year; negative values are BC
  approximate?: boolean;  // True for ancient structures dated by archaeology
                          // rather than records
  id: number;
  difficulty: Difficulty;
  link: string;
}

export const structures: Structure[] = [
  {
    name: 'Great Pyramid of Giza',
    place: 'Giza',
    country: 'Egypt',
    year: -2560,
    approximate: true,
    id: 6000,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza',
  },
  {
    name: 'Stonehenge',
    place: 'Wiltshire',
    country: 'United Kingdom',
    year: -2500,
    approximate: true,
    id: 6001,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Stonehenge',
  },
  {
    name: 'Abu Simbel temples',
    place: 'Nubia',
    country: 'Egypt',
    year: -1244,
    approximate: true,
    id: 6002,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Abu_Simbel_temples',
  },
  {
    name: 'Temple of Karnak (Great Hypostyle Hall)',
    place: 'Luxor',
    country: 'Egypt',
    year: -1224,
    approximate: true,
    id: 6003,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Karnak',
  },
  {
    name: 'Parthenon',
    place: 'Athens',
    country: 'Greece',
    year: -432,
    id: 6004,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Parthenon',
  },
  {
    name: 'Great Wall of China (Qin unification)',
    country: 'China',
    year: -206,
    approximate: true,
    id: 6005,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Great_Wall_of_China',
  },
  {
    name: 'Petra (Al-Khazneh / Treasury)',
    place: 'Petra',
    country: 'Jordan',
    year: -100,
    approximate: true,
    id: 6006,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Petra',
  },
  {
    name: 'Pont du Gard',
    place: 'Occitanie',
    country: 'France',
    year: 60,
    approximate: true,
    id: 6007,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Pont_du_Gard',
  },
  {
    name: 'Colosseum',
    place: 'Rome',
    country: 'Italy',
    year: 80,
    id: 6008,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Colosseum',
  },
  {
    name: 'Pantheon',
    place: 'Rome',
    country: 'Italy',
    year: 126,
    id: 6009,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Pantheon,_Rome',
  },
  {
    name: 'Teotihuacan (Pyramid of the Sun)',
    place: 'near Mexico City',
    country: 'Mexico',
    year: 200,
    approximate: true,
    id: 6010,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Pyramid_of_the_Sun',
  },
  {
    name: 'Hagia Sophia',
    place: 'Istanbul',
    country: 'Turkey',
    year: 537,
    id: 6011,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Hagia_Sophia',
  },
  {
    name: 'Horyu-ji temple',
    place: 'Nara',
    country: 'Japan',
    year: 607,
    id: 6012,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Horyu-ji',
  },
  {
    name: 'Dome of the Rock',
    place: 'Jerusalem',
    country: 'Israel/Palestine',
    year: 691,
    id: 6013,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Dome_of_the_Rock',
  },
  {
    name: 'Borobudur',
    place: 'Java',
    country: 'Indonesia',
    year: 825,
    approximate: true,
    id: 6014,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Borobudur',
  },
  {
    name: 'Great Mosque of Córdoba (final expansion)',
    place: 'Córdoba',
    country: 'Spain',
    year: 987,
    id: 6015,
    difficulty: 'hard',
    link:
        'https://en.wikipedia.org/wiki/Mosque%E2%80%93Cathedral_of_C%C3%B3rdoba',
  },
  {
    name: 'Chichen Itza (El Castillo)',
    place: 'Yucatán',
    country: 'Mexico',
    year: 1000,
    approximate: true,
    id: 6016,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/El_Castillo,_Chichen_Itza',
  },
  {
    name: 'Tower of London (White Tower)',
    place: 'London',
    country: 'United Kingdom',
    year: 1078,
    id: 6017,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Tower_of_London',
  },
  {
    name: 'Angkor Wat',
    place: 'Siem Reap',
    country: 'Cambodia',
    year: 1150,
    approximate: true,
    id: 6018,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Angkor_Wat',
  },
  {
    name: 'Westminster Abbey (present church)',
    place: 'London',
    country: 'United Kingdom',
    year: 1269,
    id: 6019,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Westminster_Abbey',
  },
  {
    name: 'Notre-Dame de Paris',
    place: 'Paris',
    country: 'France',
    year: 1345,
    id: 6020,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Notre-Dame_de_Paris',
  },
  {
    name: 'Alhambra (Nasrid palaces)',
    place: 'Granada',
    country: 'Spain',
    year: 1358,
    approximate: true,
    id: 6021,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Alhambra',
  },
  {
    name: 'Leaning Tower of Pisa',
    place: 'Pisa',
    country: 'Italy',
    year: 1372,
    id: 6022,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa',
  },
  {
    name: 'Golden Pavilion (Kinkaku-ji)',
    place: 'Kyoto',
    country: 'Japan',
    year: 1397,
    id: 6023,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Kinkaku-ji',
  },
  {
    name: 'Charles Bridge',
    place: 'Prague',
    country: 'Czech Republic',
    year: 1402,
    id: 6024,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Charles_Bridge',
  },
  {
    name: 'Duomo di Milano (consecration)',
    place: 'Milan',
    country: 'Italy',
    year: 1418,
    id: 6025,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Milan_Cathedral',
  },
  {
    name: 'Forbidden City',
    place: 'Beijing',
    country: 'China',
    year: 1420,
    id: 6026,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Forbidden_City',
  },
  {
    name: 'Brunelleschi\'s Dome (Florence Cathedral)',
    place: 'Florence',
    country: 'Italy',
    year: 1436,
    id: 6027,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Florence_Cathedral',
  },
  {
    name: 'Machu Picchu',
    place: 'Cusco Region',
    country: 'Peru',
    year: 1450,
    approximate: true,
    id: 6028,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Machu_Picchu',
  },
  {
    name: 'Topkapi Palace',
    place: 'Istanbul',
    country: 'Turkey',
    year: 1465,
    id: 6029,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Topkap%C4%B1_Palace',
  },
  {
    name: 'Kremlin walls and towers',
    place: 'Moscow',
    country: 'Russia',
    year: 1495,
    id: 6030,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Moscow_Kremlin',
  },
  {
    name: 'Moai statues of Easter Island (peak period)',
    place: 'Easter Island',
    country: 'Chile',
    year: 1500,
    approximate: true,
    id: 6031,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Moai',
  },
  {
    name: 'St. Basil\'s Cathedral',
    place: 'Moscow',
    country: 'Russia',
    year: 1561,
    id: 6032,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Saint_Basil%27s_Cathedral',
  },
  {
    name: 'Rialto Bridge',
    place: 'Venice',
    country: 'Italy',
    year: 1591,
    id: 6033,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Rialto_Bridge',
  },
  {
    name: 'Himeji Castle (main keep)',
    place: 'Himeji',
    country: 'Japan',
    year: 1609,
    id: 6034,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Himeji_Castle',
  },
  {
    name: 'Blue Mosque',
    place: 'Istanbul',
    country: 'Turkey',
    year: 1616,
    id: 6035,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Blue_Mosque,_Istanbul',
  },
  {
    name: 'St. Peter\'s Basilica',
    country: 'Vatican City',
    year: 1626,
    id: 6036,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/St._Peter%27s_Basilica',
  },
  {
    name: 'Taj Mahal',
    place: 'Agra',
    country: 'India',
    year: 1653,
    id: 6037,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Taj_Mahal',
  },
  {
    name: 'Palace of Versailles (main expansion)',
    place: 'Versailles',
    country: 'France',
    year: 1682,
    id: 6038,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Palace_of_Versailles',
  },
  {
    name: 'Potala Palace (rebuilt)',
    place: 'Lhasa, Tibet',
    country: 'China',
    year: 1694,
    id: 6039,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Potala_Palace',
  },
  {
    name: 'St. Paul\'s Cathedral',
    place: 'London',
    country: 'United Kingdom',
    year: 1710,
    id: 6040,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/St_Paul%27s_Cathedral,_London',
  },
  {
    name: 'Schönbrunn Palace',
    place: 'Vienna',
    country: 'Austria',
    year: 1749,
    id: 6041,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Sch%C3%B6nbrunn_Palace',
  },
  {
    name: 'Brandenburg Gate',
    place: 'Berlin',
    country: 'Germany',
    year: 1791,
    id: 6042,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Brandenburg_Gate',
  },
  {
    name: 'The White House',
    place: 'Washington, D.C.',
    country: 'USA',
    year: 1800,
    id: 6043,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/White_House',
  },
  {
    name: 'United States Capitol (original building)',
    place: 'Washington, D.C.',
    country: 'USA',
    year: 1826,
    id: 6044,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/United_States_Capitol',
  },
  {
    name: 'Arc de Triomphe',
    place: 'Paris',
    country: 'France',
    year: 1836,
    id: 6045,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Arc_de_Triomphe',
  },
  {
    name: 'Buckingham Palace (as royal residence)',
    place: 'London',
    country: 'United Kingdom',
    year: 1837,
    id: 6046,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Buckingham_Palace',
  },
  {
    name: 'Big Ben (Elizabeth Tower)',
    place: 'London',
    country: 'United Kingdom',
    year: 1859,
    id: 6047,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Big_Ben',
  },
  {
    name: 'Houses of Parliament (Palace of Westminster, rebuilt)',
    place: 'London',
    country: 'United Kingdom',
    year: 1870,
    id: 6048,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Palace_of_Westminster',
  },
  {
    name: 'Brooklyn Bridge',
    place: 'New York',
    country: 'USA',
    year: 1883,
    id: 6049,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Brooklyn_Bridge',
  },
  {
    name: 'Neuschwanstein Castle',
    place: 'Bavaria',
    country: 'Germany',
    year: 1886,
    id: 6050,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Neuschwanstein_Castle',
  },
  {
    name: 'Statue of Liberty',
    place: 'New York',
    country: 'USA',
    year: 1886,
    id: 6051,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Statue_of_Liberty',
  },
  {
    name: 'Eiffel Tower',
    place: 'Paris',
    country: 'France',
    year: 1889,
    id: 6052,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Eiffel_Tower',
  },
  {
    name: 'Tower Bridge',
    place: 'London',
    country: 'United Kingdom',
    year: 1894,
    id: 6053,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Tower_Bridge',
  },
  {
    name: 'Reichstag building',
    place: 'Berlin',
    country: 'Germany',
    year: 1894,
    id: 6054,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Reichstag_building',
  },
  {
    name: 'Flatiron Building',
    place: 'New York',
    country: 'USA',
    year: 1902,
    id: 6055,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Flatiron_Building',
  },
  {
    name: 'Grand Central Terminal',
    place: 'New York',
    country: 'USA',
    year: 1913,
    id: 6056,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Grand_Central_Terminal',
  },
  {
    name: 'Panama Canal',
    country: 'Panama',
    year: 1914,
    id: 6057,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Panama_Canal',
  },
  {
    name: 'Trans-Siberian Railway',
    country: 'Russia',
    year: 1916,
    id: 6058,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Trans-Siberian_Railway',
  },
  {
    name: 'Lincoln Memorial',
    place: 'Washington, D.C.',
    country: 'USA',
    year: 1922,
    id: 6059,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Lincoln_Memorial',
  },
  {
    name: 'Chrysler Building',
    place: 'New York',
    country: 'USA',
    year: 1930,
    id: 6060,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Chrysler_Building',
  },
  {
    name: 'Empire State Building',
    place: 'New York',
    country: 'USA',
    year: 1931,
    id: 6061,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Empire_State_Building',
  },
  {
    name: 'Christ the Redeemer',
    place: 'Rio de Janeiro',
    country: 'Brazil',
    year: 1931,
    id: 6062,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)',
  },
  {
    name: 'Sydney Harbour Bridge',
    place: 'Sydney',
    country: 'Australia',
    year: 1932,
    id: 6063,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Sydney_Harbour_Bridge',
  },
  {
    name: 'Hoover Dam',
    place: 'Nevada–Arizona border',
    country: 'USA',
    year: 1936,
    id: 6064,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Hoover_Dam',
  },
  {
    name: 'Golden Gate Bridge',
    place: 'San Francisco',
    country: 'USA',
    year: 1937,
    id: 6065,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Golden_Gate_Bridge',
  },
  {
    name: 'Fallingwater',
    place: 'Pennsylvania',
    country: 'USA',
    year: 1937,
    id: 6066,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Fallingwater',
  },
  {
    name: 'Mount Rushmore',
    place: 'South Dakota',
    country: 'USA',
    year: 1941,
    id: 6067,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Mount_Rushmore',
  },
  {
    name: 'The Pentagon',
    place: 'Arlington, Virginia',
    country: 'USA',
    year: 1943,
    id: 6068,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/The_Pentagon',
  },
  {
    name: 'United Nations Headquarters',
    place: 'New York',
    country: 'USA',
    year: 1952,
    id: 6069,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Headquarters_of_the_United_Nations',
  },
  {
    name: 'Seagram Building',
    place: 'New York',
    country: 'USA',
    year: 1958,
    id: 6070,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Seagram_Building',
  },
  {
    name: 'Atomium',
    place: 'Brussels',
    country: 'Belgium',
    year: 1958,
    id: 6071,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Atomium',
  },
  {
    name: 'Guggenheim Museum',
    place: 'New York',
    country: 'USA',
    year: 1959,
    id: 6072,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Solomon_R._Guggenheim_Museum',
  },
  {
    name: 'Brasília (Congresso Nacional)',
    place: 'Brasília',
    country: 'Brazil',
    year: 1960,
    id: 6073,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/National_Congress_of_Brazil',
  },
  {
    name: 'Berlin Wall',
    place: 'Berlin',
    country: 'Germany',
    year: 1961,
    id: 6074,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Berlin_Wall',
  },
  {
    name: 'Space Needle',
    place: 'Seattle',
    country: 'USA',
    year: 1962,
    id: 6075,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Space_Needle',
  },
  {
    name: 'Gateway Arch',
    place: 'St. Louis',
    country: 'USA',
    year: 1965,
    id: 6076,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Gateway_Arch',
  },
  {
    name: 'Habitat 67',
    place: 'Montreal',
    country: 'Canada',
    year: 1967,
    id: 6077,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Habitat_67',
  },
  {
    name: 'Madison Square Garden (current)',
    place: 'New York',
    country: 'USA',
    year: 1968,
    id: 6078,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Madison_Square_Garden',
  },
  {
    name: 'Transamerica Pyramid',
    place: 'San Francisco',
    country: 'USA',
    year: 1972,
    id: 6079,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Transamerica_Pyramid',
  },
  {
    name: 'World Trade Center (Twin Towers)',
    place: 'New York',
    country: 'USA',
    year: 1973,
    id: 6080,
    difficulty: 'easy',
    link:
        'https://en.wikipedia.org/wiki/World_Trade_Center_(1973%E2%80%932001)',
  },
  {
    name: 'Sydney Opera House',
    place: 'Sydney',
    country: 'Australia',
    year: 1973,
    id: 6081,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Sydney_Opera_House',
  },
  {
    name: 'Sears Tower (Willis Tower)',
    place: 'Chicago',
    country: 'USA',
    year: 1973,
    id: 6082,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Willis_Tower',
  },
  {
    name: 'CN Tower',
    place: 'Toronto',
    country: 'Canada',
    year: 1976,
    id: 6083,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/CN_Tower',
  },
  {
    name: 'Centre Pompidou',
    place: 'Paris',
    country: 'France',
    year: 1977,
    id: 6084,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Centre_Pompidou',
  },
  {
    name: 'Lotus Temple',
    place: 'New Delhi',
    country: 'India',
    year: 1986,
    id: 6085,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Lotus_Temple',
  },
  {
    name: 'Louvre Pyramid',
    place: 'Paris',
    country: 'France',
    year: 1989,
    id: 6086,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Louvre_Pyramid',
  },
  {
    name: 'Bank of China Tower',
    place: 'Hong Kong',
    country: 'China',
    year: 1990,
    id: 6087,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Bank_of_China_Tower,_Hong_Kong',
  },
  {
    name: 'Channel Tunnel',
    place: 'beneath the English Channel',
    country: 'United Kingdom–France',
    year: 1994,
    id: 6088,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Channel_Tunnel',
  },
  {
    name: 'Kansai International Airport (artificial island)',
    place: 'Osaka',
    country: 'Japan',
    year: 1994,
    id: 6089,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Kansai_International_Airport',
  },
  {
    name: 'Guggenheim Museum Bilbao',
    place: 'Bilbao',
    country: 'Spain',
    year: 1997,
    id: 6090,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Guggenheim_Museum_Bilbao',
  },
  {
    name: 'Petronas Towers',
    place: 'Kuala Lumpur',
    country: 'Malaysia',
    year: 1998,
    id: 6091,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Petronas_Towers',
  },
  {
    name: 'Burj Al Arab',
    place: 'Dubai',
    country: 'United Arab Emirates',
    year: 1999,
    id: 6092,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Burj_Al_Arab',
  },
  {
    name: 'Øresund Bridge',
    place: 'across the Øresund strait',
    country: 'Denmark–Sweden',
    year: 2000,
    id: 6093,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/%C3%98resund_Bridge',
  },
  {
    name: 'London Eye',
    place: 'London',
    country: 'United Kingdom',
    year: 2000,
    id: 6094,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/London_Eye',
  },
  {
    name: 'Walt Disney Concert Hall',
    place: 'Los Angeles',
    country: 'USA',
    year: 2003,
    id: 6095,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Walt_Disney_Concert_Hall',
  },
  {
    name: 'Millau Viaduct',
    place: 'Aveyron',
    country: 'France',
    year: 2004,
    id: 6096,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Millau_Viaduct',
  },
  {
    name: 'Taipei 101',
    place: 'Taipei',
    country: 'Taiwan',
    year: 2004,
    id: 6097,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Taipei_101',
  },
  {
    name: 'Allianz Arena',
    place: 'Munich',
    country: 'Germany',
    year: 2005,
    id: 6098,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Allianz_Arena',
  },
  {
    name: 'Wembley Stadium (new)',
    place: 'London',
    country: 'United Kingdom',
    year: 2007,
    id: 6099,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Wembley_Stadium',
  },
  {
    name: 'Beijing National Stadium (Bird\'s Nest)',
    place: 'Beijing',
    country: 'China',
    year: 2008,
    id: 6100,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Beijing_National_Stadium',
  },
  {
    name: 'Burj Khalifa',
    place: 'Dubai',
    country: 'United Arab Emirates',
    year: 2010,
    id: 6101,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Burj_Khalifa',
  },
  {
    name: 'Marina Bay Sands',
    country: 'Singapore',
    year: 2010,
    id: 6102,
    difficulty: 'medium',
    link: 'https://en.wikipedia.org/wiki/Marina_Bay_Sands',
  },
  {
    name: 'The Shard',
    place: 'London',
    country: 'United Kingdom',
    year: 2012,
    id: 6103,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/The_Shard',
  },
  {
    name: 'One World Trade Center',
    place: 'New York',
    country: 'USA',
    year: 2014,
    id: 6104,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/One_World_Trade_Center',
  },
  {
    name: 'Gotthard Base Tunnel',
    place: 'Uri–Ticino',
    country: 'Switzerland',
    year: 2016,
    id: 6105,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Gotthard_Base_Tunnel',
  },
  {
    name: 'Elbphilharmonie',
    place: 'Hamburg',
    country: 'Germany',
    year: 2017,
    id: 6106,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Elbphilharmonie',
  },
  {
    name: 'Crossrail / Elizabeth Line',
    place: 'London',
    country: 'United Kingdom',
    year: 2022,
    id: 6107,
    difficulty: 'hard',
    link: 'https://en.wikipedia.org/wiki/Elizabeth_line',
  },
  {
    name: 'Sagrada Família (tallest tower completed)',
    place: 'Barcelona',
    country: 'Spain',
    year: 2023,
    id: 6108,
    difficulty: 'easy',
    link: 'https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia',
  }
];
